Signal/src/textsecure/Messages/TSMessagesManager.m
Signal/src/view controllers/GroupModel.m
Signal/src/view controllers/MessagesViewController.m

• more descriptive info message strings on group update
• UI of info messages doesn't display multiliners well, but the info string will be stored for use by future UI improvments.

more descriptive info message strings

---

Signal/src/Storyboard/Storyboard.storyboard
Signal/src/view controllers/RegistrationViewController.h

-prepping work flow with tyler

Regscreen newassets 325

---

Signal/src/Storyboard/Storyboard.storyboard

built constraints for _1.0_registration screen

---

Signal/src/Storyboard/Storyboard.storyboard

reorganized storyboard views

---

Signal.xcodeproj/project.pbxproj
Signal/src/textsecure/Messages/Attachements/TSAttachmentStream.h
Signal/src/textsecure/Messages/Attachements/TSAttachmentStream.m
Signal/src/textsecure/Messages/TSMessagesManager+attachments.m
Signal/src/view controllers/MessagesViewController.h
Signal/src/view controllers/MessagesViewController.m
Signal/src/view controllers/TSAttachmentAdapter.m
Signal/src/view controllers/TSMessageAdapter.m
Signal/src/view controllers/TSVideoAttachmentAdapter.h
Signal/src/view controllers/TSVideoAttachmentAdapter.m

- take video
- send video
- video playing full screen
- attachment receiving of video/audio

Video attachments 229

---

Signal/src/Storyboard/Storyboard.storyboard
Signal/src/environment/PreferencesUtil.m
Signal/src/view controllers/SettingsTableViewController.m

image quality is average by default instead of checking if the user has configured a preference for image quality. i've also removed ability to configure image quality in the settings page.

average image quality

---

Signal/src/view controllers/MessageComposeTableViewController.m

In the messages composer, users can search within their contacts by their name or by their phone number. Now, messaging numbers not in the "contacts" book is enabled. If a user searches for a phone number that has >7 digits in it, then we can fire up iMessage to this number with a link to install Signal (link not inputted yet) in the message.

to unknown contact sends install signal link via SMS PR 1/2

---

Signal/src/Storyboard/Storyboard.storyboard
Signal/src/textsecure/Storage/TSDatabaseView.m
Signal/src/view controllers/UITests/SignalsViewController.m

the archive functionality should be all messages

changing archive to all

---

Signal/src/AppDelegate.m
Signal/src/view controllers/MessageComposeTableViewController.h
Signal/src/view controllers/MessageComposeTableViewController.m

Added pull to refresh on compose page

---

Signal/src/Storyboard/Storyboard.storyboard

temporarily positioned and styled

constrained safe words

---

Signal/src/AppDelegate.m
Signal/src/Storyboard/Storyboard.storyboard

2.0 3.0 3.1 navbar

---

Signal/src/Storyboard/Storyboard.storyboard

i suspect row height for these cells is being set dynamically in the code

refined settings style

---

Signal/src/view controllers/MessageComposeTableViewController.m

I finished the issues that persisted since my last PR.
Changes made:
- MFMessageComposeViewControllerDelegate delegate implemented, so the inability to cancel out of an iMessage screen should be fixed
- plus sign removed from when a user is typing
- clarified that users send the text to their friend explicitly to invite them to use Signal; not meant to replace the main SMS app
- included link to install Signal in the message

implement SMS delegate + polishing regular SMS invites

---

Signal/Images.xcassets/Image.imageset/Contents.json
Signal/Images.xcassets/active-box@1x.imageset/Contents.json
Signal/Images.xcassets/active-box@1x.imageset/active-box@1x.pdf
Signal/Images.xcassets/active-check@1x.imageset/Contents.json
Signal/Images.xcassets/active-check@1x.imageset/active-check@1x.pdf
Signal/Images.xcassets/add-contact@1x.imageset/Contents.json
Signal/Images.xcassets/add-contact@1x.imageset/add-contact@1x.pdf
Signal/Images.xcassets/build-conversation@1x.imageset/Contents.json
Signal/Images.xcassets/build-conversation@1x.imageset/build-conversation@1x.pdf
Signal/Images.xcassets/delete message@1x.imageset/Contents.json
Signal/Images.xcassets/delete message@1x.imageset/delete message@1x.pdf
Signal/Images.xcassets/empty-group-avatar@1x.imageset/Contents.json
Signal/Images.xcassets/empty-group-avatar@1x.imageset/empty-group-avatar@1x.pdf
Signal/Images.xcassets/group-info@1x.imageset/Contents.json
Signal/Images.xcassets/group-info@1x.imageset/group-info@1x.pdf
Signal/Images.xcassets/inactive-box@1x.imageset/Contents.json
Signal/Images.xcassets/inactive-box@1x.imageset/inactive-box@1x.pdf
Signal/Images.xcassets/inactive-check@1x.imageset/Contents.json
Signal/Images.xcassets/inactive-check@1x.imageset/inactive-check@1x.pdf
Signal/Images.xcassets/inactive-inbox@1x.imageset/Contents.json
Signal/Images.xcassets/inactive-inbox@1x.imageset/inactive-inbox@1x.pdf
Signal/Images.xcassets/mark-as-checked@1x.imageset/Contents.json
Signal/Images.xcassets/mark-as-checked@1x.imageset/mark-as-checked@1x.pdf
Signal/Images.xcassets/open-contact@1x.imageset/Contents.json
Signal/Images.xcassets/open-contact@1x.imageset/open-contact@1x.pdf
Signal/Images.xcassets/settings@1x.imageset/Contents.json
Signal/Images.xcassets/settings@1x.imageset/settings@1x.pdf
Signal/src/Storyboard/Storyboard.storyboard

added icon assets

---

Signal/src/Storyboard/Storyboard.storyboard
Signal/src/view controllers/MessagesViewController.m
Signal/src/view controllers/UITests/SignalsViewController.h
Signal/src/view controllers/UITests/SignalsViewController.m

note that this screws some things up with the view but will allow tyler to fix

Integrate assets

---

Signal/src/Storyboard/Storyboard.storyboard

adds a context tab bar to the bottom of the conversations view.

constrained conversations context icons

---

Signal/Images.xcassets/archive-active@1x.imageset/Contents.json
Signal/Images.xcassets/archive-active@1x.imageset/archive-active@1x.pdf
Signal/Images.xcassets/archive-inactive@1x.imageset/Contents.json
Signal/Images.xcassets/archive-inactive@1x.imageset/archive-inactive@1x.pdf
Signal/Images.xcassets/inbox-active@1x.imageset/Contents.json
Signal/Images.xcassets/inbox-active@1x.imageset/inbox-active@1x.pdf
Signal/Images.xcassets/inbox-inactive@1x.imageset/Contents.json
Signal/Images.xcassets/inbox-inactive@1x.imageset/inbox-inactive@1x.pdf
Signal/Images.xcassets/new-conversation-icon@1x.imageset/Contents.json
Signal/Images.xcassets/new-conversation-icon@1x.imageset/new-conversation-icon@1x.pdf
Signal/Images.xcassets/settings-icon@1x.imageset/Contents.json
Signal/Images.xcassets/settings-icon@1x.imageset/settings-icon@1x.pdf
Signal/Images.xcassets/settings@1x.imageset/settings@1x.pdf
Signal/src/Storyboard/Storyboard.storyboard

includes refined inbox/archive contextual buttons

added navigation icons

---

Signal/Images.xcassets/contact-add@1x.imageset/Contents.json
Signal/Images.xcassets/contact-add@1x.imageset/contact-add@1x.pdf
Signal/Images.xcassets/contact-call@1x.imageset/Contents.json
Signal/Images.xcassets/contact-call@1x.imageset/contact-call@1x.pdf
Signal/Images.xcassets/contact-launch@1x.imageset/Contents.json
Signal/Images.xcassets/contact-launch@1x.imageset/contact-launch@1x.pdf
Signal/Images.xcassets/contact-options-action@1x.imageset/Contents.json
Signal/Images.xcassets/contact-options-action@1x.imageset/contact-options-action@1x.pdf
Signal/Images.xcassets/contact-security@1x.imageset/Contents.json
Signal/Images.xcassets/contact-security@1x.imageset/contact-security@1x.pdf
Signal/Images.xcassets/group-options@1x.imageset/Contents.json
Signal/Images.xcassets/group-options@1x.imageset/group-options@1x.pdf
Signal/Images.xcassets/open-contact@1x.imageset/open-contact@1x.pdf
Signal/src/Storyboard/Storyboard.storyboard

contact-add@1x / contact-launch@1x
contact-call@1x
contact-security@1x
----
Update
Leave
Members

added icons

---

Signal/src/Storyboard/Storyboard.storyboard

note to @corbett, hook up the spinners in the primary buttons to indicate the user is waiting for a server response

proofed _1.0 and _1.1 screens, need spinner activity

---

Signal/src/Storyboard/Storyboard.storyboard
Signal/src/view controllers/SettingsTableViewController.h
Signal/src/view controllers/SettingsTableViewController.m

fix settings

---

Signal/src/textsecure/Messages/TSInfoMessage.m
Signal/src/textsecure/Messages/TSMessagesManager+attachments.m
Signal/src/view controllers/MessagesViewController.m

audio support isn't there yet, and may be punted for launch. @joyceyan and @jackflips did some great prototyping work in #456 for future support.

Remove audio

---

Signal/Images.xcassets/add-conversation.imageset/Contents.json
Signal/Images.xcassets/add-conversation.imageset/add-conversation.pdf
Signal/Images.xcassets/contact-options-action.imageset/Contents.json
Signal/Images.xcassets/contact-options-action.imageset/contact-options-action.pdf
Signal/Images.xcassets/signal-navigation-icon.imageset/Contents.json
Signal/Images.xcassets/signal-navigation-icon.imageset/signal-navigation-icon.pdf
Signal/src/Storyboard/Storyboard.storyboard
Signal/src/view controllers/MessagesViewController.m

note: i changed the message bubble font in the code.

improved navigation and security screen

---

Signal/src/view controllers/AboutTableViewController.m
Signal/src/view controllers/AdvancedSettingsTableViewController.m
Signal/src/view controllers/ContactDetailTableViewController.m
Signal/src/view controllers/ContactsTableViewController.m
Signal/src/view controllers/CountryCodeViewController.m
Signal/src/view controllers/FingerprintViewController.m
Signal/src/view controllers/FullImageViewController.m
Signal/src/view controllers/InCallViewController.m
Signal/src/view controllers/MediaSettingsTableViewController.m
Signal/src/view controllers/MessageComposeTableViewController.m
Signal/src/view controllers/MessagesViewController.m
Signal/src/view controllers/NewGroupViewController.m
Signal/src/view controllers/PresentIdentityQRCodeViewController.m
Signal/src/view controllers/PrivacySettingsTableViewController.m
Signal/src/view controllers/RegistrationViewController.m
Signal/src/view controllers/ScanIdentityBarcodeViewController.m
Signal/src/view controllers/SettingsTableViewController.m
Signal/src/view controllers/ShowGroupMembersViewController.m
Signal/src/view controllers/SignalsNavigationController.m
Signal/src/view controllers/UITests/SignalsViewController.m

disables translucency of nav bars

translucency

---

Signal/src/view controllers/InboxTableViewCell.h
Signal/src/view controllers/InboxTableViewCell.m
Signal/src/view controllers/UITests/SignalsViewController.m

swiping on a thread will open up a delete button that you can press to delete a thread. the api only allows text titles for the custom actions so i did my best to incorporate tyler's design. ows_redColor is used!

swipe to delete implemented

---

Signal/src/Storyboard/Storyboard.storyboard
Signal/src/view controllers/InboxTableViewCell.m

• fixes empty group avatar issue

fixed empty group avatar issue

---

README.md

Showing BitHub price in README.md

---

Signal/src/view controllers/MessagesViewController.m

Fixes #1151 
*most* of our time when scrolling around a message view is in this
method. Doubly so when these are media items.
remove interaction from cache when it is deleted/updated
// FREEBIE

Cache instantiated interactions

---

Signal/src/view controllers/NewGroupViewController.m

Fix intermittent crash when creating group with image

---

Signal/src/environment/VersionMigrations.m

* iphone 6, ios 9.3
Solves #1145 
@FredericJacobs It seems like you've already done the migration legwork. I just extracted it, checked some edge cases, and added some logging. Was there anything else that came to mind?
// FREEBIE

Bloom filter migration check for file before deleting

---

Signal/src/view controllers/InboxTableViewCell.m
Signal/src/view controllers/NewGroupViewController.m

* iPhone 6, iOS 9.3.1
- fixes #756
//FREEBIE

Prevent skewed group image (#756)

---

Signal/Signal-Info.plist

Mark encryption as exempt, per Moxie's instruction.
Bump release number
// FREEBIE

[legal] Mark encryption as exempt, per Moxie's instruction.

---

Signal/src/view controllers/MessagesViewController.m
Signal/src/view controllers/UITests/SignalsViewController.m

Fixes #1179 to make sure text box is proper size and makes sure to pop the keyboard when draft text is present.

Reset compose view on thread switch

---

Podfile.lock
Signal/Signal-Info.plist
Signal/src/contact/ContactsManager.m

* requires update to SignalServiceKit
* updated Pod Dependencies
* bumped version
Fixes #1201
// FREEBIE

Fixes avatar not showing for single contact thread

---

.travis.yml
Podfile
Podfile.lock
Signal.xcodeproj/project.pbxproj

CocoaPods 1.0 update and Travis-CI compatibility

---

Podfile
Podfile.lock
Signal.xcworkspace/xcshareddata/Signal.xcscmblueprint
Signal/Signal-Info.plist
Signal/src/view controllers/UITests/SignalsViewController.m

Fix crash after deleting message

---

Signal/Signal-Info.plist
Signal/src/contact/ContactsManager.h
Signal/src/contact/ContactsManager.m

Trying to address a long standing intermittent crash when accessing [ContactsManager allContacts], which accounts for 7-8% of over all crashes.
A follow up to #1207, which didn't seem to help much.

Atomic contacts

---

Signal/src/view controllers/MessagesViewController.m

Attempt to fix #1225
* centralize observers relevant to a "visible UI"
* collocate init/teardown of observers
// FREEBIE

Only call UI modifying observers when UI is present

---

.github/ISSUE_TEMPLATE.md

crash reporting instructions in issue template

---

Signal/Signal-Info.plist

bump release target to 2.3.4

---

Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m

This might FIX #1111, but I think there are actually a handful of other things breaking our layout.
// FREEBIE

Set explicit height for all media types. Audio is the only special case.

---

Signal/Signal-Info.plist

bump release target to 2.3.6.0

---

Signal/src/view controllers/MessagesViewController.m

Must tap directly on bubble to launch fullscreen media view

---

Podfile.lock

Fix double sends in group thread when accepting keychange

---

Signal/src/view controllers/MessagesViewController.m

Input toolbar fits textsize

---

Podfile.lock
Signal/src/environment/VersionMigrations.m

Re-enable attachment cleanup migration after fixing it in SSK

---

Podfile
Podfile.lock
Signal/Images.xcassets/AppIcon.appiconset/Contents.json
Signal/Signal-Info.plist

We already support receiving them from Desktop (mp3)
Plus some Xcode 8 turds in the image assets.
// FREEBIE

Support for receiving voice messages from android (aac)

---

Signal/src/view controllers/ShowGroupMembersViewController.m

prevent clickability of the group header cell in the group members view
fixes #1327

Disable group header interaction

---

Podfile.lock
Signal/Signal-Info.plist

* Don't attempt to send a message unless we've successfully built device-messages
* Only process message exception when we're done with retries.
// FREEBIE

Fix multiple keychange errors

---

Podfile.lock
Signal.xcodeproj/project.pbxproj
Signal/Signal-Prefix.pch
Signal/src/environment/DebugLogger.m
Signal/src/util/OWSScrubbingLogFormatter.h
Signal/src/util/OWSScrubbingLogFormatter.m
Signal/test/util/OWSScrubbingLogFormatterTest.m

Phone number are still logged in TTY for development.
fixes #1339
// FREEBIE

More logging, scrub phone numbers from file logs

---

Podfile.lock
Signal/Signal-Info.plist

Fix set timer in group thread.

---

Signal/src/views/OWSExpirationTimerView.m

Remove observers on dealloc

---

Signal/Signal-Info.plist
Signal/src/view controllers/MessagesViewController.m

fix delivery receipts for disappearing messages

---

Signal.xcodeproj/project.pbxproj
Signal/src/Signal-Bridging-Header.h
Signal/src/Storyboard/Storyboard.storyboard
Signal/src/view controllers/FingerprintViewController.m
Signal/src/view controllers/MessagesViewController.m
Signal/src/views/CopyableLabel.swift
Signal/src/views/OWSExpirationTimerView.m

copyable safety numbers

---

Podfile
Podfile.lock
Signal/Signal-Info.plist
Signal/src/views/OWSIncomingMessageCollectionViewCell.xib

Incoming audio is not being displayed.
I missed a bottom constraint when customizing incoming message bubbles to include timer icon in footer, but beacuse other message types explicitly set bubble height it wasn't an issue except for audio. 
// FREEBIE

Fix hidden incoming audio

---

Podfile
Podfile.lock

Update SSL to 1.0.2j

---

Podfile.lock
Signal/Signal-Info.plist

previously fixed in: SSK:91fcd01632a81f2aa67d2d94b97c68d519e6881a
But got lost in a rebase after moving TSMessagesManager+sendMessage to
OWSMessageSender.
// FREEBIE

[SSK] Don't send empty message to self after changing disappearing timer

---

Podfile.lock

[SSK] Update to prevent session corruption

---

Signal/Signal-Info.plist
Signal/src/Models/OWSMessagesBubblesSizeCalculator.m
Signal/src/util/NumberUtil.m
Signal/src/view controllers/MessagesViewController.m
Signal/test/Models/MesssagesBubblesSizeCalculatorTest.swift

Fix crash on nil message

---

BUILDING.md

- [-] I have tested my contribution on these devices:
* no need
Adds comment to the BUILDING.md file on running carthage, which is necessary to build the project
// FREEBIE

Adds comment on running carthage, which is necessary to build the project

---

Podfile.lock
Signal/Signal-Info.plist

[SSK] Fix crash on messaging unregistered user

---

Podfile.lock
Signal/Signal-Info.plist

[SSK] Send group messages as long as one recipient is found

---

Signal/src/Storyboard/Main.storyboard

failed to update storyboard when class was renamed.
// FREEBIE

Fix fingerprint Label copying

---

README.md

n/a (documentation change only)
The results of #1442 should probably be referenced in the README. This just adds a link to the wiki.
(Whether that should live in BUILDING.md instead of the wiki is perhaps another question)

Update README with link to development guide

---

Signal/src/view controllers/MessagesViewController.m

* iPhone SE, iOS 9.3.5
This is behavior that I am expecting that is builtin to the default Messages app as well as Whatsapp. I tried experimenting with `UIKeyboardType` but that is a red herring. I tested with a non-US keyboard (Arabic).
These gifs are pre and post patch respectively. My apologies for the speed. It turns out converting mov files to gifs and getting a nice balance of speed and optimization is quite an annoying process.
Let me know if there is anything else you need from me!

Switch back to the default keyboard after sending

---

Signal.xcodeproj/project.pbxproj
Signal/src/Storyboard/Main.storyboard
Signal/src/view controllers/MessageComposeTableViewController.m
Signal/src/views/NoSignalContactsView.swift
Signal/src/views/NoSignalContactsView.xib
Signal/translations/en.lproj/Localizable.strings

"No Contacts" screen uses new invite flow

---

Signal/src/view controllers/SignalsViewController.m

Fix peek from inbox

---

Signal/Signal-Info.plist
Signal/src/contact/OWSContactsManager.h
Signal/src/contact/OWSContactsManager.m
Signal/src/view controllers/NewGroupViewController.m
Signal/src/view controllers/ShowGroupMembersViewController.m
Signal/src/views/ContactTableViewCell.m

The broken code addressed in 8211d45 was duplicated a couple of places. This commit ferrets out the rest of them and centralizes the logic in the ContactsManager.

Fix crash in group listing / new group views

---

Podfile.lock
Signal/src/view controllers/MessagesViewController.m

Seems these crashes were introduced when transitioning from
DJWActionSheet -> UIAlertController
// FREEBIE

Fix crash when attaching media

---

Signal/src/Storyboard/Main.storyboard

Make disappearing messages button visible in German

---

Podfile
Podfile.lock

Incorporates: https://github.com/WhisperSystems/SignalProtocolKit/commit/714f5ebe199ecc999b33c6f97a4bb57e2db90e75
// FREEBIE

[SPK] Update SignalProtocolKit (AxolotlKit)

---

Podfile.lock

[SSK] Fix contact sync when no thread to self exists

---

Podfile
Podfile.lock
Signal/Signal-Info.plist

[SSK] Avoid bricking signal if a key is temporarily unreadable

---

.travis.yml
Podfile
Podfile.lock
Signal.xcodeproj/project.pbxproj
Signal/Signal-Info.plist
Signal/src/Jobs/MessageFetcherJob.swift
Signal/src/Signal-Bridging-Header.h
Signal/src/network/PushManager.m

see more at https://whispersystems.org/blog/doodles-stickers-censorship/

Censorship circumvention

---

Podfile
Podfile.lock
Signal/Signal-Prefix.pch
Signal/src/AppDelegate.m
Signal/src/Models/OWSMessagesBubblesSizeCalculator.h
Signal/src/network/PushManager.h
Signal/src/network/PushManager.m

Update SignalServiceKit pod.

---

MAINTAINING.md

Improve instructions on how to build WebRTC.

---

Signal/src/util/OWSLogger.h
Signal/src/util/OWSLogger.m

Add method to flush logs.

---

Signal/src/view controllers/CallViewController.swift

Improve buttons in call view.

---

Signal/src/view controllers/CallViewController.swift

Show call duration for connected calls.

Add call duration to call view.

---

Signal/src/AppDelegate.m

Hmm, I need to find the time to revisit #1584

Elaborate logging in app delegate.

---

Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
Signal/src/view controllers/CallViewController.swift

Disable unused CallKit buttons.

---

Signal/src/view controllers/MessagesViewController.m

Initiate a Redphone call unless *both* parties have opted into WebRTC calling.
TODO: this is going to be weird when two parties are *just* enabling
webrtc for the first time. We might want to do something as drastic as
refetch contact information before initiating the call.
// FREEBIE

Respect WebRTC calling preference

---

Podfile.lock

[SSK] Disable resetting unreadable storage

---

Signal/src/call/CallAudioService.swift
Signal/src/call/CallService.swift
Signal/src/call/NonCallKitCallUIAdaptee.swift
Signal/src/call/SignalCall.swift
Signal/src/call/Speakerbox/CallKitCallManager.swift
Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
Signal/src/call/UserInterface/CallUIAdapter.swift
Signal/src/view controllers/CallViewController.swift

* Hide speakerphone button if local video is enabled.
* Auto-enable speakerphone if local video is enabled.
* Combine button rows on call screen.
* Move mute and "toggle video" buttons down by "hang up" button if remote video is present.
* Various cleanup and bug fixes.
// FREEBIE

Reworked call view’s remote video mode.

---

Signal.xcodeproj/project.pbxproj
Signal/src/Signal-Bridging-Header.h
Signal/src/view controllers/CallViewController.swift
Signal/src/views/OWSAnyTouchGestureRecognizer.h
Signal/src/views/OWSAnyTouchGestureRecognizer.m

Show/hide call view controls in remote video mode if user taps screen.

---

Signal/src/call/CallService.swift
Signal/src/call/NonCallKitCallUIAdaptee.swift
Signal/src/call/PeerConnectionClient.swift
Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
Signal/src/call/UserInterface/CallUIAdapter.swift
Signal/src/view controllers/CallViewController.swift
Signal/translations/en.lproj/Localizable.strings

* Prevent screen from dimming or device from locking during video call.
* Remove camera constraints.
* Improve thread safety in call ui adapter and adaptees.
* I've moved the activity in these classes to the main thread.
* Show alert when user tries to activate local video without camera permissions.

Charlesmchen/webrtc/video refinements 

---

Signal/src/call/CallService.swift

Disable local video in background.

---

Signal/src/view controllers/CallViewController.swift

Add drop shadows to text in call view.

---

Scripts/HardResetGit.sh

Hard reset git script.

---

Signal/src/call/CallAudioService.swift

Ensure audio state when call connects.

---

Signal/src/call/CallService.swift

Log reconnect events as such.

---

Signal/src/call/CallAudioService.swift

Specify AVAudioSession modes for calls.

---

Signal/src/views/OWSAnyTouchGestureRecognizer.m

Prevent system edge swipe gestures from showing/hiding call controls.

---

Signal/src/view controllers/AdvancedSettingsTableViewController.m

Only show CallKit footer when showing the CallKit cell

---

Signal/src/view controllers/CallViewController.swift

Show hidden call view controls when app reactivates.

---

Signal/src/AppDelegate.m
Signal/src/call/CallService.swift
Signal/src/call/OutboundCallInitiator.swift
Signal/src/phone/PhoneManager.h
Signal/src/phone/PhoneManager.m

Fix bug in the busy logic.

---

Signal/src/call/CallService.swift
Signal/src/call/PeerConnectionClient.swift
Signal/test/call/PeerConnectionClientTest.swift

This PR rolls up a number of unrelated fixes.
I'll discuss them in inline comments.

Charlesmchen/call thread safety4 

---

Signal/src/view controllers/CallViewController.swift
Signal/translations/en.lproj/Localizable.strings

Add “signal” copy to call view.

---

Podfile.lock

https://github.com/WhisperSystems/SignalServiceKit/pull/106

Update SSK to reflect charlesmchen/messagesFromMeAreAlreadyAutoRead.

---

Signal/src/view controllers/CallViewController.swift

Fix bad frames in remote video.

---

Signal/src/call/CallService.swift

Prevent device lock during calls.

---

Signal/src/view controllers/SignalsViewController.m

Fix layout issue with inbox unread count on home view.

---

Signal/src/view controllers/AdvancedSettingsTableViewController.m

Don't show callkit description pre-iOS10

---

Podfile.lock

[SSK] log when messages are marked as read locally

---

Signal/Signal-Prefix.pch
Signal/src/contact/OWSContactsManager.h
Signal/src/contact/OWSContactsManager.m
Signal/src/view controllers/MessageComposeTableViewController.m
Signal/src/view controllers/NewGroupViewController.m

https://github.com/WhisperSystems/Signal-iOS/issues/1724

Update views that show contacts to reflect updates.

---

Signal/src/call/CallService.swift

previously a followup call could get clobbered by the previous calls
timeout
// FREEBIE

Only time out the intended call

---

.gitmodules

* Merge feature/webrtc into master.
* Move submodule reference from https:// to git://

Update Carthage submodule.

---

Signal/src/view controllers/AdvancedSettingsTableViewController.m

I've verified that very recent activity shows up in submitted logs after this change.

Flush logs before submitting logs.

---

BUILDING.md

path changed in the webrtc repository
// FREEBIE

Update build script path

---

Cartfile.resolved
Podfile.lock

See: https://github.com/WhisperSystems/Signal-Carthage/pull/2

Update Cocoapods and Carthage submodule.

---

Signal.xcodeproj/project.pbxproj
Signal/src/Models/TSMessageAdapaters/TSMessageAdapter.m
Signal/src/Models/TSMessageAdapaters/TSPhotoAdapter.m
Signal/src/view controllers/AttachmentSharing.h
Signal/src/view controllers/AttachmentSharing.m
Signal/src/view controllers/FullImageViewController.m
Signal/src/view controllers/MessagesViewController.m
Signal/translations/en.lproj/Localizable.strings

Add sharing of attachments.

---

Signal/src/Models/TSMessageAdapaters/TSPhotoAdapter.m
Signal/src/view controllers/FullImageViewController.m

Improve image scaling quality.

---

Signal/src/view controllers/CodeVerificationViewController.m
Signal/src/view controllers/RegistrationViewController.m

Further refine the registration and verification views.

---

Signal/src/environment/Migrations/OWS102MoveLoggingPreferenceToUserDefaults.m

fix potential deadlock

---

MAINTAINING.md

transperancy → transparency
* iDevice A, iOS X.Y.Z
* iDevice B, iOS Z.Y

Fix typo in Maintaining doc - FREEBIE

---

Signal/src/AppDelegate.m

See: https://github.com/WhisperSystems/Signal-iOS-Private/pull/2#discussion_r101145821

Simplify the prekey check on app launch and activation.

---

Signal/src/call/CallAudioService.swift
Signal/src/call/CallService.swift

Also add vibration for remote hangup so you're not talking to dead air.

Call sounds - connecting, outgoing ring, busy sound.

---

Signal/src/call/CallAudioService.swift

Fix build break.

---

Signal/src/call/PeerConnectionClient.swift

Instruments showed a reduction from ~65% -> ~45% while on audio only
call on iPhone5c.

stop videoCapture until video track is enabled to save some battery

---

Signal/src/view controllers/CallViewController.swift

proximity sensor

---

Signal/src/Models/OWSContactAvatarBuilder.m

* iPhone 5s, iOS 10.2
Fixes #1519 by restricting the initials to alphanumeric characters.

Restrict default avatars to alphanumeric initials (#1519)

---

Signal/src/view controllers/MessagesViewController.m

Basically, ensure that `sendMessageAttachment:` does its work on the main thread.

Fix thread-safety assert when sending video attachments.

---

Signal/translations/en.lproj/Localizable.strings

clarify call integration copy

---

Signal/src/Storyboard/Main.storyboard
Signal/src/view controllers/InboxTableViewCell.xib

Just noticed this...
// FREEBIE

Maintain AR when scaling avatar

---

BUILDING.md
Cartfile
Cartfile.resolved
Makefile
Podfile
Podfile.lock
Signal.xcodeproj/project.pbxproj
Signal.xcworkspace/xcshareddata/Signal.xcscmblueprint

and update build instructions
If it looks good, I'll ff-merge the corresponding Carthage submodule commit.

move zxing to framework

---

Signal/src/environment/Release.m
Signal/src/view controllers/CountryCodeViewController.m
Signal/test/phone/PhoneNumberTest.m

* Filtering wasn't working; it has been fixed.
* I've added support for arbitrary partial matches and matching based on country code and calling code.

Fix filtering of country codes in registration flow.

---

Signal/src/util/DisplayableTextFilter.swift

We don't want to log here normally, only when we detect weird strings.

Invert logging condition.

---

Signal/src/view controllers/MessagesViewController.m

Fix sending attachments from the camera.

---

Podfile
Podfile.lock
Signal.xcodeproj/project.pbxproj
Signal/Signal-Prefix.pch
Signal/src/AppDelegate.m
Signal/src/util/Pastelog.h
Signal/src/util/Pastelog.m
Signal/src/view controllers/AdvancedSettingsTableViewController.m

All of this has happened before.
All of this will happen again.
We don't want this as an external dependency - it's just going to slow us down for future changes. 
Updated the copy per @charlesmchen  feedback over at https://github.com/WhisperSystems/PastelogKit/pull/1
finally incorporates @guillett's work to copy-to-pasteboard. (sorry for the delay 🙄 )
Fixes https://github.com/WhisperSystems/Signal-iOS/issues/1338

Intern pastelog

---

Signal/src/Models/OWSCall.m
Signal/src/UserInterface/Notifications/UserNotificationsAdaptee.swift
Signal/src/UserInterface/Strings.swift
Signal/src/environment/NotificationsManager.m
Signal/translations/en.lproj/Localizable.strings

Fixes: https://github.com/WhisperSystems/Signal-iOS/issues/1870

Honor call privacy settings in call notifications.

---

Signal/src/view controllers/MessagesViewController.m

Disable the "scroll to new message" animation.

---

Signal/src/view controllers/AttachmentApprovalViewController.swift
Signal/src/view controllers/ContactsPicker.swift

Use “stop” not “cancel” buttons.

---

Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m

Fix play button for incoming video attachments.

---

Signal/src/view controllers/SignalAttachment.swift

Add animated gif UTI types to attachment.

---

Signal/src/view controllers/AdvancedSettingsTableViewController.m

The intention is to make it easier to confirm that the logs contain the latest entries.

Log submission of logs.

---

Signal/src/view controllers/SignalAttachment.swift

Raise max GIF file size and default image upload quality.

---

Signal/src/environment/NotificationsManager.m

Only enforce CallKit privacy for missed calls if CallKit is present.

---

Signal.xcodeproj/project.pbxproj
Signal/src/util/ThreadUtil.h
Signal/src/util/ThreadUtil.m
Signal/src/view controllers/DebugUITableViewController.h
Signal/src/view controllers/DebugUITableViewController.m
Signal/src/view controllers/MessagesViewController.m

A simple debug UI - simple, but with a lot of room to grow.
* Is shown from conversation view by long-pressing on title in header.
* Currently has one item which sends 100 text messages.
* Is designed to grow - i.e. to have multiples kinds of item, as well as arbitrarily nested hierarchy of pages.

Sketch out debug UI.

---

Signal/src/view controllers/NewGroupViewController.m

Hide keyboard when scrolling the contacts list in new/edit group view.

---

Signal/src/Models/TSMessageAdapaters/TSGenericAttachmentAdapter.m
Signal/src/view controllers/AttachmentSharing.h
Signal/src/view controllers/AttachmentSharing.m
Signal/src/view controllers/DebugUITableViewController.m
Signal/src/view controllers/MessagesViewController.m
Signal/translations/en.lproj/Localizable.strings

See: https://github.com/WhisperSystems/SignalServiceKit/pull/152

Improve support for arbitrary attachments.

---

Signal/src/view controllers/CountryCodeViewController.m

Analogous to https://github.com/WhisperSystems/Signal-iOS/pull/1905

Hide keyboard when scrolling in country code view.

---

Signal/src/ViewControllers/OWSTableViewController.h
Signal/src/ViewControllers/OWSTableViewController.m

Fix invalid assert in the OWS table views.

---

Signal/src/ViewControllers/AddToBlockListViewController.m
Signal/src/ViewControllers/RegistrationViewController.m

Reformat phone number if user changes country code.

---

Signal/src/ViewControllers/MessagesViewController.m

Ensure keyboard doesn't hide "safety numbers changed" interaction.

---

Signal/src/views/ContactTableViewCell.m

Round avatar icons.

---

Signal/src/ViewControllers/MessagesViewController.m
Signal/src/ViewControllers/SignalAttachment.swift

Fix paste when pasteboard has multiple items.

---

Signal/src/ViewControllers/MessagesViewController.m

This is not for v2.10.  I'd like to merge this after and see if any problems emerge over the next sprint.

Reload data and invalidate layout whenever message view will appear.

---

Signal/src/ViewControllers/MessagesViewController.m

Stay scrolled to the bottom during in conversation view during updates.

---

Signal/src/Models/TSMessageAdapaters/TSMessageAdapter.m

Hide the edit menu for attachment until they are uploaded.

---

Signal/src/ViewControllers/MessagesViewController.m

Show attachment approval dialog for all attachments.

---

Podfile.lock
Signal/src/ViewControllers/BlockListUIUtils.h
Signal/src/ViewControllers/MessagesViewController.m
Signal/src/util/ThreadUtil.h
Signal/src/util/ThreadUtil.m
Signal/translations/en.lproj/Localizable.strings

Depends on: https://github.com/WhisperSystems/SignalServiceKit/pull/165/files

Create block offer when non-contacts send you a message.

---

Signal/src/ViewControllers/InboxTableViewCell.h
Signal/src/ViewControllers/InboxTableViewCell.m
Signal/src/ViewControllers/SignalsViewController.m
Signal/translations/en.lproj/Localizable.strings

* Improve thread safety of home view cells.

Show block indicator in home view.

---

Podfile.lock
Signal/src/AppDelegate.m
Signal/src/Jobs/MessageFetcherJob.swift

See: https://github.com/WhisperSystems/SignalServiceKit/pull/164
This change is not for v2.10. We need to dogfood this extensively.

Rework socket manager.

---

Signal/src/ViewControllers/MessagesViewController.m

Send oversize text messages as attachments.

---

Signal/src/AppDelegate.m

local users registration ID in debug log

---

Signal/src/environment/NotificationsManager.m
Signal/src/network/PushManager.m

Improve thread safety in PushManager and NotificationsManager.

---

Signal/src/call/WebRTCCallMessageHandler.swift

Fix calling by using actual session descriptions.

---

Signal/src/ViewControllers/MessagesViewController.m

Fix paste of text.

---

Signal.xcodeproj/project.pbxproj
Signal/src/AppDelegate.m
Signal/src/contact/OWSContactsManager.h
Signal/src/contact/OWSContactsManager.m
Signal/src/util/OWSContactsSyncing.h
Signal/src/util/OWSContactsSyncing.m

Send contacts sync messages whenever the contacts change.

---

Signal/src/ViewControllers/OWSConversationSettingsTableViewController.m

It turns out that if you delete the only view in a storyboard that uses a segue, the segue is deleted as well.  Switch "conversation settings" view to initiate all navigation programmatically without segues.

Fix segues in conversation settings view.

---

Signal/src/ViewControllers/AddToBlockListViewController.m
Signal/src/ViewControllers/MessagesViewController.h
Signal/src/ViewControllers/MessagesViewController.m
Signal/src/ViewControllers/ShowGroupMembersViewController.m
Signal/src/ViewControllers/SignalsViewController.h
Signal/src/ViewControllers/SignalsViewController.m
Signal/src/contact/OWSContactsManager.h
Signal/src/contact/OWSContactsManager.m
Signal/src/environment/Environment.h
Signal/src/environment/Environment.m
Signal/src/views/ContactTableViewCell.h
Signal/src/views/ContactTableViewCell.m
Signal/translations/en.lproj/Localizable.strings

* Use `ContactTableViewCell`.
* Show avatars
* Style contact names as they appear elsewhere.
* Show block status.
* Tapping on a member now offers the following options:
* Contact info (previously the only option).
* Block/unblock this user.
* Send 1:1 message to this user.
* Call this user.

Improve group members view.

---

Signal/src/ViewControllers/OWSConversationSettingsTableViewController.m

Fix “muted until” date format.

---

Signal/src/ViewControllers/InboxTableViewCell.m

Show mute status in home view.

---

Podfile.lock
Signal.xcodeproj/project.pbxproj
Signal/src/Models/TSMessageAdapaters/AttachmentPointerAdapter.swift
Signal/src/Models/TSMessageAdapaters/TSMessageAdapter.m
Signal/src/Signal-Bridging-Header.h
Signal/src/ViewControllers/MessagesViewController.m
Signal/src/views/AttachmentPointerView.swift
Signal/translations/en.lproj/Localizable.strings

download progress. take 2

---

Signal.xcodeproj/project.pbxproj
Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m
Signal/src/ViewControllers/MessagesViewController.h
Signal/src/ViewControllers/MessagesViewController.m
Signal/src/ViewControllers/OWSAudioAttachmentPlayer.h
Signal/src/ViewControllers/OWSAudioAttachmentPlayer.m

* Fix two bugs around play/pause button appearance.
* Fix bugs around stopping playback when leaving view/entering background.
* Fix bugs around cleaning up playback state  when leaving view/entering background.
* Fix audio playback vs. hardware mute button.
* Improve handling of invalid audio attachments.

Add audio attachment player.

---

Signal.xcodeproj/project.pbxproj
Signal/src/ViewControllers/OWSAudioAttachmentPlayer.m
Signal/src/util/NSTimer+OWS.h
Signal/src/util/NSTimer+OWS.m

Fix timer retain cycle.

---

Signal.xcodeproj/project.pbxproj
Signal/Signal.entitlements
Signal/src/ViewControllers/MessagesViewController.m
Signal/src/views/AttachmentPointerView.swift
Signal/translations/en.lproj/Localizable.strings

Choose arbitrary attachments from iCloud/GDrive/Dropbox/etc

---

Signal/src/network/PushManager.m

Increase local notification delay.

---

Signal/src/ViewControllers/MessagesViewController.m

Fix crash unsafely accessing optional media method.

---

Signal/src/ViewControllers/MessagesViewController.m
Signal/translations/en.lproj/Localizable.strings

Resolve the menu item conflicts between message view and media view.

---

Signal/src/ViewControllers/SignalAttachment.swift
Signal/src/util/ThreadUtil.m

always send a filename with attachments

---

Signal/src/ViewControllers/MessagesViewController.m
Signal/src/ViewControllers/SignalAttachment.swift

Validate document attachments, show proper preview

---

Signal/src/ViewControllers/AttachmentApprovalViewController.swift

truncate really long file names in the middle

---

Signal/src/ViewControllers/SendExternalFileViewController.m

Tweak appearance of "export with Signal" UI.

---

Signal/src/AppDelegate.m
Signal/src/ViewControllers/MessagesViewController.m
Signal/translations/en.lproj/Localizable.strings

Improve errors in the 'export with Signal' feature.

---

Signal/src/AppDelegate.m

Ignore “open with Signal” if there is an ongoing call.

---

Signal/src/ViewControllers/MessagesViewController.m

Skip attachment approval dialog for image and video shot by camera.

---

Signal/src/call/CallService.swift

Don't unwrap with ! in CallService.

---

Signal/src/contact/OWSContactsManager.m

Fix database deadlock in contacts manager.

---

Signal/src/ViewControllers/InboxTableViewCell.m

(can't init attributed string with nil)

fix crash when viewing undisplayable text

---

Signal/src/call/CallService.swift

Reconcile audio enabling with call state.

---

Signal.xcodeproj/project.pbxproj
Signal/src/Models/SyncPushTokensJob.swift
Signal/src/call/CallService.swift
Signal/src/call/NonCallKitCallUIAdaptee.swift
Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
Signal/src/util/Promise+retainUntilComplete.swift

See individual commits for notes

better call connectivity

---

Signal/src/contact/SystemContactsFetcher.swift
Signal/src/util/OWSContactsSyncing.m

Fix two hotspots in contact parsing and contact syncing.

---

Signal/src/AppDelegate.m
Signal/src/ViewControllers/AdvancedSettingsTableViewController.m
Signal/src/ViewControllers/SignalsViewController.m

Improve logging around SyncPushTokensJob.

---

Signal/Signal-Prefix.pch
Signal/src/AppDelegate.m
Signal/src/Models/SyncPushTokensJob.swift
Signal/src/ViewControllers/AdvancedSettingsTableViewController.m
Signal/src/ViewControllers/CodeVerificationViewController.m
Signal/src/ViewControllers/MessageComposeTableViewController.m
Signal/src/ViewControllers/NewGroupViewController.m
Signal/src/ViewControllers/RegistrationViewController.m
Signal/src/ViewControllers/SettingsTableViewController.m
Signal/src/ViewControllers/SignalsViewController.m
Signal/src/call/CallService.swift
Signal/src/network/PushManager.m
Signal/src/views/OWSAlerts.swift

Always sync and log push tokens. Apply OWSAlerts in more places.

---

Signal/src/ViewControllers/MessagesViewController.m

Always clear message drafts after sending a text message.

---

Podfile.lock
Signal/src/ViewControllers/MessagesViewController.m
Signal/src/ViewControllers/SignalAttachment.swift
Signal/src/util/ThreadUtil.m

Flag voice messages as such in protos.

---

Signal/src/Storyboard/Main.storyboard
Signal/src/ViewControllers/OWSTableViewController.m
Signal/src/ViewControllers/ShowGroupMembersViewController.m
Signal/src/contact/SystemContactsFetcher.swift
Signal/src/util/UIUtil.m
Signal/translations/en.lproj/Localizable.strings

* properly populate phone fields
* Fix appearence for CNContactViewController
* "Add Contact" vs "Show Contact"

Edit contacts in group list

---

Signal/src/AppDelegate.m

Fix edge case where screen protection is not removed.

---

Signal/src/ViewControllers/ContactsViewHelper.m

Always honor filtering in contact-related views.

---

Podfile.lock
Signal/src/ViewControllers/SelectRecipientViewController.m
Signal/translations/en.lproj/Localizable.strings

See: https://github.com/WhisperSystems/SignalServiceKit/pull/209

Show example phone numbers.

---

Signal/src/ViewControllers/MessagesViewController.m

Remove extra period in voice message file names.

---

Signal/src/ViewControllers/MessagesViewController.m

After sending a text message, the "send" button should revert to mic.

---

Signal/src/ViewControllers/SelectRecipientViewController.m

Disable scrolling if no contacts in “select recipient” views.

---

Signal/src/contact/SystemContactsFetcher.swift

inadvertently moved it to main thread with
354d46e3f484eb82604b3a278dc7ec8d43a6e03a
// FREEBIE

return contact parsing to background thread

---

Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m
Signal/src/ViewControllers/OWSAudioAttachmentPlayer.m
Signal/translations/en.lproj/Localizable.strings

Show alert when user tries to play an invalid audio file.

---

Signal/src/ViewControllers/NewGroupViewController.m
Signal/src/ViewControllers/UpdateGroupViewController.m

Trim whitespace from group names.

---

Signal/src/ViewControllers/BlockListViewController.m
Signal/src/ViewControllers/ContactsViewHelper.h
Signal/src/ViewControllers/ContactsViewHelper.m
Signal/src/ViewControllers/MessageComposeTableViewController.m
Signal/src/ViewControllers/NewGroupViewController.m
Signal/src/ViewControllers/OWSConversationSettingsTableViewController.m
Signal/src/ViewControllers/SelectRecipientViewController.m
Signal/src/ViewControllers/SelectThreadViewController.m
Signal/src/ViewControllers/ShowGroupMembersViewController.m
Signal/src/ViewControllers/UpdateGroupViewController.m

Ensure contact delegate helper is set during initialization.

---

Signal/src/ViewControllers/MessagesViewController.m

Ignore taps on outgoing messages while they are being sent.

---

Signal/src/Models/TSMessageAdapaters/JSQMediaItem+OWS.h
Signal/src/Models/TSMessageAdapaters/JSQMediaItem+OWS.m
Signal/src/Models/TSMessageAdapaters/TSGenericAttachmentAdapter.m
Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m

Align photo and audio bubble widths.

---

Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m

Rework appearance of audio messages.

---

Signal/src/ViewControllers/MessagesViewController.m

Don't hide keyboard when recording a voice message.

---

Signal/src/ViewControllers/SignalAttachment.swift

Work around m4a vs. mp4 issue for voice messages in legacy iOS clients.

---

Signal/src/ViewControllers/OWSConversationSettingsTableViewController.m

Change conversation settings buttons to gray.

---

Podfile.lock
Signal/src/ViewControllers/SelectRecipientViewController.m

Honor the local calling code in select recipient view.

---

Signal/src/ViewControllers/RegistrationViewController.m
Signal/translations/en.lproj/Localizable.strings

Show alerts for missing or invalid phone numbers in registration view.

---

Signal/src/Models/TSMessageAdapaters/JSQMediaItem+OWS.h
Signal/src/Models/TSMessageAdapaters/JSQMediaItem+OWS.m
Signal/src/Models/TSMessageAdapaters/TSAnimatedAdapter.h
Signal/src/Models/TSMessageAdapaters/TSAnimatedAdapter.m
Signal/src/Models/TSMessageAdapaters/TSPhotoAdapter.m
Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m

A slew of optimizations around attachments that, taken together, dramatically improve responsiveness and reduce memory usage.

Lazy load attachments in messages view, etc.

---

Podfile.lock
Signal.xcodeproj/project.pbxproj
Signal/src/ViewControllers/MessagesViewController.m
Signal/src/util/ThreadUtil.h
Signal/src/util/ThreadUtil.m
Signal/translations/en.lproj/Localizable.strings

See: https://github.com/WhisperSystems/SignalServiceKit/pull/224

“Add to contacts” offer.

---

Signal.xcodeproj/project.pbxproj
Signal/src/ViewControllers/DebugUI/DebugUIContacts.h
Signal/src/ViewControllers/DebugUI/DebugUIContacts.m
Signal/src/ViewControllers/DebugUI/DebugUIMessages.h
Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
Signal/src/ViewControllers/DebugUI/DebugUITableViewController.h
Signal/src/ViewControllers/DebugUI/DebugUITableViewController.m

Add debug functions for sending media messages.

---

Signal/src/Signal-Bridging-Header.h
Signal/src/Storyboard/Main.storyboard
Signal/src/UIStoryboard+OWS.swift
Signal/src/ViewControllers/CallViewController.swift
Signal/src/ViewControllers/CountryCodeViewController.m
Signal/src/ViewControllers/ExperienceUpgradesPageViewController.swift
Signal/src/ViewControllers/MessagesViewController.m
Signal/src/ViewControllers/OWSConversationSettingsTableViewController.m
Signal/src/ViewControllers/SettingsTableViewController.h
Signal/src/ViewControllers/SettingsTableViewController.m
Signal/src/ViewControllers/SignalsViewController.m

Replace app settings segue.

---

Podfile.lock
Signal/src/Models/TSMessageAdapaters/TSAnimatedAdapter.m
Signal/src/Models/TSMessageAdapaters/TSPhotoAdapter.m
Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m

See: https://github.com/WhisperSystems/SignalServiceKit/pull/228

Rename audio duration and image size methods in TSAttachmentStream.

---

Podfile.lock
Signal.xcodeproj/project.pbxproj
Signal/src/Jobs/MarkIdentityAsSeenJob.swift
Signal/src/ProfileFetcherJob.swift
Signal/src/Signal-Bridging-Header.h
Signal/src/ViewControllers/MessagesViewController.m

see also: https://github.com/WhisperSystems/SignalServiceKit/pull/231
Incidentally:
* uniform method to get recipients in group/contact thread
* use it to clean up markAsSeenJob

Fetch safety number upon entering thread

---

Signal/src/AppDelegate.m
Signal/src/Signal-Bridging-Header.h
Signal/src/ViewControllers/SettingsTableViewController.m
Signal/src/ViewControllers/SignalsNavigationController.h
Signal/src/ViewControllers/SignalsNavigationController.m
Signal/src/network/PushManager.m

Part two would be to show an indicator that censorship circumvention is active.

Hide the socket status view when censorship circumvention is active.

---

Signal/src/AppDelegate.m
Signal/src/ViewControllers/RegistrationViewController.m

Tweak appearance of registration views.

---

Signal/src/ViewControllers/MessagesViewController.m

Make “send message” button easier to tap.

---

Signal/src/ViewControllers/MessagesViewController.m

Fix issues around initial layout of messages view.

---

Signal/src/ViewControllers/MessagesViewController.h
Signal/src/ViewControllers/MessagesViewController.m
Signal/src/util/ThreadUtil.h
Signal/src/util/ThreadUtil.m

Add “scroll to bottom button”, improve scrolling behavior.

---

Signal/src/Models/OWSMessagesBubblesSizeCalculator.m
Signal/src/UserInterface/Strings.swift
Signal/src/ViewControllers/ConversationView/MessagesViewController.m
Signal/src/views/OWSSystemMessageCell.h
Signal/src/views/OWSSystemMessageCell.m
Signal/src/views/OWSUnreadIndicatorCell.h
Signal/src/views/OWSUnreadIndicatorCell.m
Signal/translations/en.lproj/Localizable.strings

Clean up system message cells, make them tappable, etc.

---

Signal.xcodeproj/project.pbxproj
Signal/src/ViewControllers/DebugUI/DebugUISessionState.h
Signal/src/ViewControllers/DebugUI/DebugUISessionState.m
Signal/src/ViewControllers/DebugUI/DebugUITableViewController.m

Added a debug method to locally simulate a SN change.

debug item: SN change

---

Signal/src/ViewControllers/SignalAttachment.swift

Taking a third run at this.  I keep finding unexpected behavior in the pasteboard.

Fix paste of text fragments.

---

Signal/src/Models/OWSMessagesBubblesSizeCalculator.m
Signal/src/network/PushManager.m
Signal/src/util/ThreadUtil.m
Signal/src/views/OWSSystemMessageCell.m

Clean up usage of fail macro.

---

Signal/src/ViewControllers/DebugUI/DebugUIMessages.m

Remove deprecated info message from debug UI

---

Signal/src/ProfileFetcherJob.swift

Throttle profile fetch and retry on failure.

---

Signal/src/environment/NotificationsManager.m

Throttle notification sounds.

---

Signal/src/environment/NotificationsManager.m

Allow notification sound check from any thread.

---

Podfile
Podfile.lock

Fix OpenSSL cocoapod.

---

Podfile
Podfile.lock

It's legacy from ZRTP.
// FREEBIE

Remove OpenSSL pod.

---

Signal/src/ViewControllers/DebugUI/DebugUIMessages.m

Fake messages aren't actually sent or received, they're just saved in the database.  So they're only useful for testing locally (e.g. perf).

Add debug UI to create fake messages.

---

Signal/src/util/ThreadUtil.m

Don’t show offers in conversation with self.

---

Signal/src/call/CallService.swift

Don't return busy signal to untrusted callers.

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Fix "writes on long-lived read connection" issue.

---

Signal/src/ViewControllers/FingerprintViewScanController.m
Signal/translations/en.lproj/Localizable.strings

clearer copy for SN changes

---

Signal/src/Models/TSMessageAdapaters/TSAnimatedAdapter.m
Signal/src/Models/TSMessageAdapaters/TSPhotoAdapter.m
Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m

Fix “Invalid media attachments” crash.

---

Signal/src/ViewControllers/AboutTableViewController.m

Show long-form app version in about view.

---

Signal/src/ViewControllers/FingerprintViewController.m
Signal/src/ViewControllers/RegistrationViewController.m

Increase font size of phone number to match size of country code.

Tweak font size on registration view.

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Ensure message mapping is up-to-date when app returns from background.

---

Signal/src/ViewControllers/FingerprintViewController.m

Prevent layout from jumping around in fingerprint view.

---

Signal/src/ViewControllers/SettingsTableViewController.m
Signal/translations/en.lproj/Localizable.strings

Seems a little obtuse.
WDYT @charlesmchen

remove unneccessary explanation of UI

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m
Signal/src/ViewControllers/InboxTableViewCell.m

Max out the unread count at 99.

---

Podfile
Podfile.lock
Signal/src/ViewControllers/ConversationView/MessagesViewController.m

see also: https://github.com/WhisperSystems/JSQMessagesViewController/pull/10
Fixes https://github.com/WhisperSystems/Signal-iOS/issues/1634, https://github.com/WhisperSystems/Signal-iOS/issues/1531

[JSQ] Fix: can't dismiss keyboard after sending

---

Signal/src/AppDelegate.m
Signal/src/environment/VersionMigrations.h

Fix upgrade launch screen.

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Invalid message adapter cache when app becomes visible.

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m
Signal/src/ViewControllers/OWSTableViewController.h
Signal/src/ViewControllers/OWSTableViewController.m
Signal/src/ViewControllers/ShowGroupMembersViewController.m
Signal/translations/en.lproj/Localizable.strings

Improve UX for multiple “no longer verified” members of a group.

---

Signal/src/call/CallService.swift
Signal/src/call/SignalCall.swift

Improve logging in CallService.

---

Signal/src/ViewControllers/RegistrationViewController.h
Signal/src/ViewControllers/RegistrationViewController.m

See: https://github.com/WhisperSystems/SignalServiceKit/pull/278

Persist registration values in the keychain for debug builds only.

---

Signal/src/ViewControllers/OWSCountryMetadata.m

Fix crash in manual censorship circumvention logic on iOS 9.

---

Scripts/bump_build_number.py

It's not the most polished script in the world, but it's safe and it'll fail with messages that will be useful for resolving any issue that comes up.

Add script to bump build numbers.

---

Signal/src/ViewControllers/ViewControllerUtils.m

Remove phone number length limit in registration view.

---

Signal/src/ViewControllers/DebugUI/DebugUIContacts.m

Refine fake contact creation.

---

Signal/src/environment/NotificationsManager.m
Signal/src/network/PushManager.h
Signal/src/network/PushManager.m

Don’t reply to “no longer verified”.

---

Signal/src/Models/SyncPushTokensJob.swift

log when starting token sync in prod

---

Signal/src/Models/TSMessageAdapaters/TSMessageAdapter.m
Signal/src/ViewControllers/ConversationView/MessagesViewController.m
Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
Signal/src/views/OWSSystemMessageCell.m

show timestamp after unread indicator

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Prevent "scroll to button" button from blipping.

---

Signal/src/AppDelegate.m
Signal/src/environment/Environment.m

addendum to https://github.com/WhisperSystems/Signal-iOS/pull/2277

Unregistered users should have 0 badge count

---

Signal/src/Models/OWSCall.h
Signal/src/Models/TSMessageAdapaters/TSMessageAdapter.m

No change in behavior, but  now that we have a nice system message design, we don't need this less-than-righteous hack.
Also, fixes assertion check added here: https://github.com/WhisperSystems/Signal-iOS/pull/2280/files#diff-7bb3586101621d594a0d0a80cf3b173bR1843

remove unneccessary hack

---

Signal/src/call/CallAudioService.swift
Signal/src/call/CallService.swift
Signal/src/call/UserInterface/CallUIAdapter.swift
Signal/src/environment/NotificationsManager.m

A couple of changes here - I'll annotate in line

Non-Callkit adapter plays audio from notification when app is in background

---

Signal/src/ViewControllers/SignalsViewController.m

clearer comment

---

Signal/src/environment/Migrations/OWSDatabaseMigrationRunner.m

Fix possible cause of crash on launch.

---

Signal/src/ViewControllers/DebugUI/DebugUIMessages.m

Add options to send 3k debug messages.

---

Signal/src/AppDelegate.m
Signal/src/environment/VersionMigrations.h

Fix missing “database upgrade” label on launch screen.

---

Signal/src/ViewControllers/SettingsTableViewController.m

network status is not tappable

---

Signal.xcodeproj/project.pbxproj
Signal/src/AppDelegate.m
Signal/src/ViewControllers/ConversationView/MessagesViewController.m
Signal/src/ViewControllers/DebugUI/DebugUITableViewController.m
Signal/src/ViewControllers/OWSAudioAttachmentPlayer.m
Signal/src/call/CallService.swift
Signal/src/util/DeviceSleepManager.swift

Block device from sleeping during certain activities.

---

Signal/src/call/CallAudioService.swift

With appropriate logging and now that we've consolidated AudioSession mgmt into a single method, this was pretty straight forward.

Fix bluetooth audio for calls

---

Signal/src/Jobs/MessageFetcherJob.swift
Signal/src/Signal-Bridging-Header.h
Signal/src/ViewControllers/CallViewController.swift

Fix “timer circular reference” leaks.

---

BUILDING.md
Libraries/WebRTC/RTCAudioSession.h
MAINTAINING.md

Take deux
See also: https://github.com/WhisperSystems/signal-webrtc-ios

Update WebRTC to M59 + signal patches

---

Signal.xcodeproj/project.pbxproj
Signal/src/Models/TSMessageAdapaters/AttachmentPointerAdapter.swift
Signal/src/ProfileFetcherJob.swift
Signal/src/ViewControllers/AttachmentApprovalViewController.swift
Signal/src/ViewControllers/ExperienceUpgradesPageViewController.swift
Signal/src/ViewControllers/SignalAttachment.swift
Signal/src/call/CallAudioService.swift
Signal/src/call/CallService.swift
Signal/src/call/NonCallKitCallUIAdaptee.swift
Signal/src/call/OutboundCallInitiator.swift
Signal/src/call/PeerConnectionClient.swift
Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
Signal/src/call/UserInterface/CallUIAdapter.swift
Signal/src/contact/SystemContactsFetcher.swift
Signal/src/environment/ExperienceUpgrades/ExperienceUpgrade.swift
Signal/src/util/OWSAsserts.swift
Signal/src/views/AttachmentPointerView.swift
Signal/src/views/AudioProgressView.swift

Add owsFail free function for swift.

---

Podfile.lock
Signal.xcodeproj/project.pbxproj
Signal/src/Models/OWSMessagesBubblesSizeCalculator.m
Signal/src/ViewControllers/DebugUI/DebugUIDiskUsage.m
Signal/src/environment/VersionMigrations.m
Signal/test/Models/AccountManagerTest.swift
Signal/test/ViewControllers/Signals/TSMessageAdapters/TSMessageAdapterTest.m
Signal/test/contact/ContactsPickerTest.swift

See: https://github.com/WhisperSystems/SignalServiceKit/pull/291

Run orphan cleanup on startup.

---

Signal/src/ViewControllers/CallViewController.swift

Fix another call view leak.

---

Signal/src/ViewControllers/ContactsViewHelper.h
Signal/src/ViewControllers/ContactsViewHelper.m
Signal/src/ViewControllers/OWSConversationSettingsTableViewController.m

Previously we'd show an empty "list" of existing contacts.

Adding to existing contact requires contact access

---

Signal/src/ViewControllers/SignalsViewController.m

Assert that mapping is set whenever accessing

---

Signal/src/ViewControllers/OWSConversationSettingsTableViewController.m

fix: unregistered user shows "add to contacts"

---

Signal/src/ViewControllers/SelectRecipientViewController.m
Signal/src/call/OutboundCallInitiator.swift
SignalServiceKit/src/Contacts/PhoneNumber.h
SignalServiceKit/src/Contacts/PhoneNumber.m
SignalServiceKit/tests/Contacts/PhoneNumberTest.m

See: https://github.com/WhisperSystems/SignalServiceKit/pull/286

[SSK] Try applying national prefixes when parsing phone numbers.

---

BUILDING.md

clarify build instructions

---

README.md
SignalServiceKit/README.md

Instructions, how to use SignalServiceKit

---

Signal.xcodeproj/project.pbxproj
Signal/src/Signal-Bridging-Header.h
Signal/src/call/CallService.swift
Signal/src/call/PeerConnectionClient.swift
Signal/src/util/OWSAsserts.swift
Signal/src/util/OWSSwiftUtils.swift
SignalServiceKit/src/Storage/TSStorageManager.m
SignalServiceKit/src/Util/OWSAnalytics.h
SignalServiceKit/src/Util/OWSAnalytics.m
SignalServiceKit/src/Util/OWSQueues.h

Instrument CallService.

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m
Signal/src/ViewControllers/SignalsViewController.m

Rework database observation in home and message views.

---

Signal/src/AppDelegate.m
Signal/src/environment/Migrations/OWS103EnableVideoCalling.m
Signal/src/environment/VersionMigrations.m
SignalServiceKit/src/Account/TSAccountManager.m
SignalServiceKit/src/Account/TSPreKeyManager.m
SignalServiceKit/src/Contacts/ContactsUpdater.m
SignalServiceKit/src/Messages/Attachments/OWSAttachmentsProcessor.m
SignalServiceKit/src/Messages/OWSMessageSender.m
SignalServiceKit/src/Messages/TSMessagesManager.m
SignalServiceKit/src/Network/API/OWSDeviceProvisioningCodeService.m
SignalServiceKit/src/Network/API/OWSDeviceProvisioningService.m
SignalServiceKit/src/Network/API/OWSDevicesService.m
SignalServiceKit/src/Storage/TSStorageManager.m
SignalServiceKit/src/Util/OWSAnalytics.h
SignalServiceKit/src/Util/OWSAnalytics.m

Streamline analytics properties.

---

Podfile.lock
Signal/src/ViewControllers/CodeVerificationViewController.m
Signal/src/ViewControllers/RegistrationViewController.m

Instrument registration happy path with analytics.

---

Podfile.lock
SignalServiceKit/Example/TSKitiOSTestApp/Podfile.lock
SignalServiceKit/src/Messages/OWSMessageReceiver.m
SignalServiceKit/src/Messages/TSMessagesManager.m

Properly handle too-large messages

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Fix assert in conversation view around nil title.

---

SignalServiceKit/src/Contacts/TSThread.m

Avoid crash when deleting threads - and improve perf.

---

Signal/src/call/CallService.swift
Signal/src/util/OWSAnalytics.swift
SignalServiceKit/src/Util/OWSAnalyticsEvents.h
SignalServiceKit/src/Util/OWSAnalyticsEvents.m

Add more instrumentation to CallService.

---

Signal/src/ViewControllers/DebugUI/DebugUIMessages.m

Add debug UI for creating groups.

---

Signal/src/ViewControllers/DebugUI/DebugUIMessages.m

Include local number when creating debug groups.

---

Signal.xcodeproj/project.pbxproj
Signal/src/ViewControllers/DebugUI/DebugUIMisc.h
Signal/src/ViewControllers/DebugUI/DebugUIMisc.m
Signal/src/ViewControllers/DebugUI/DebugUITableViewController.m

Add debug UI to enable manual censorship circumvention.

---

SignalServiceKit/src/Util/Asserts.h
SignalServiceKit/src/Util/OWSAnalytics.h

Fix asserts in analytics macros.

---

Signal/src/views/OWSOutgoingMessageCollectionViewCell.m

Fix RTL alignment of message footers.

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Ensure size of message mappings range increases monotonically.

---

Signal/src/ViewControllers/CodeVerificationViewController.m
Signal/src/ViewControllers/RegistrationViewController.m

Tweaks to registration views.

---

Signal/translations/bin/auto-genstrings

Modify l10n string extraction script to reflect SSK move.

---

Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
Signal/src/ViewControllers/DebugUI/DebugUIMisc.m
Signal/src/ViewControllers/NewGroupViewController.m
Signal/src/ViewControllers/UpdateGroupViewController.m
SignalServiceKit/src/Messages/OWSBlockingManager.h
SignalServiceKit/src/Messages/OWSMessageSender.h
SignalServiceKit/src/Messages/OWSMessageSender.m
SignalServiceKit/src/Profiles/OWSProfilesManager.h
SignalServiceKit/src/Profiles/OWSProfilesManager.m

Sketch out profile manager.

---

Signal/src/Models/OWSAvatarBuilder.h
Signal/src/Models/OWSAvatarBuilder.m
Signal/src/Models/OWSContactAvatarBuilder.m
Signal/src/Models/OWSGroupAvatarBuilder.m
Signal/src/ViewControllers/CallViewController.swift
Signal/src/ViewControllers/DebugUI/DebugUIContacts.h
Signal/src/ViewControllers/DebugUI/DebugUIContacts.m
Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
Signal/src/ViewControllers/InboxTableViewCell.m
Signal/src/ViewControllers/OWSConversationSettingsTableViewController.m
Signal/src/views/ContactTableViewCell.m

Fixed the avatar flicker in the inbox and added debug actions to create a bunch of contact threads.

fix avatar flash

---

Signal/src/ViewControllers/PrivacySettingsTableViewController.m

Show proper setting for CallKitPrivacy

---

Signal/src/UIView+OWS.m
Signal/src/ViewControllers/RegistrationViewController.m

Remove iOS 9-only APIs from layout code.

---

Signal/src/call/CallService.swift
Signal/src/call/NonCallKitCallUIAdaptee.swift
Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
Signal/src/call/UserInterface/CallUIAdapter.swift

Timer to ensure call screen display

call screen timer

---

Signal/src/ViewControllers/SignalsViewController.m
Signal/src/call/CallService.swift
SignalServiceKit/src/Util/OWSAnalyticsEvents.h
SignalServiceKit/src/Util/OWSAnalyticsEvents.m

Terminate call if call view presentation is delayed.

---

Signal/src/Models/OWSAvatarBuilder.h
Signal/src/Models/OWSAvatarBuilder.m
Signal/src/ViewControllers/DebugUI/DebugUIContacts.m

Perhaps my finest work.
For helping to test loading with a variety of avatars per https://github.com/WhisperSystems/Signal-iOS/pull/2386

Debug UI: (some) random contacts have avatars

---

Signal/src/ViewControllers/SignalsViewController.m

Show threads if possible.

---

SignalServiceKit/tests/Messages/Interactions/TSMessageTest.m
SignalServiceKit/tests/Messages/OWSDisappearingMessageFinderTest.m
SignalServiceKit/tests/Messages/OWSDisappearingMessagesJobTest.m

fix some recently broken tests

---

SignalServiceKit/src/Protocols/ProtoBuf+OWS.m

As written solves a crash, but we'll probably want to revisit the perf implications.

Can only set whitelist on main thread

---

Signal/src/Profiles/OWSProfileManager.m
SignalServiceKit/src/Network/API/Requests/TSSetProfileRequest.m
SignalServiceKit/src/Network/API/TSNetworkManager.m
SignalServiceKit/src/Network/OWSSignalService.h
SignalServiceKit/src/Network/OWSSignalService.m
SignalServiceKit/src/TSConstants.h

upload profile avatar

---

Makefile
SignalServiceKit/Example/TSKitiOSTestApp/TSKitiOSTestApp.xcodeproj/project.pbxproj
SignalServiceKit/tests/TestSupport/Fakes/OWSFakeProfileManager.h
SignalServiceKit/tests/TestSupport/Fakes/OWSFakeProfileManager.m
SignalServiceKit/tests/TestSupport/Fakes/OWSUnitTestEnvironment.m

Included plausible test implementation for an in-memory profile manager.
Note two tests remain failing (they've been failing for a while)

Fix up some tests

---

Signal/src/call/CallService.swift
Signal/src/call/WebRTCCallMessageHandler.swift

Drop stale EndCall/BusyCall messages

---

Signal.xcodeproj/project.pbxproj
Signal/src/MessageSender+Promise.swift
Signal/src/Signal-Bridging-Header.h
Signal/src/ViewControllers/DebugUI/DebugUICalling.swift
Signal/src/ViewControllers/DebugUI/DebugUIPage.h
Signal/src/ViewControllers/DebugUI/DebugUITableViewController.m
Signal/src/call/CallService.swift

For testing stale hangup/busy messages
Extracted MessageSender promise API
Moved call debug actions to their own page

Debug actions for calling

---

Signal/src/Profiles/OWSProfileManager.h
Signal/src/Profiles/OWSProfileManager.m
Signal/src/ViewControllers/ContactsViewHelper.h
Signal/src/ViewControllers/ContactsViewHelper.m

Use profile name/avatar when saving new contact

---

Signal/src/Profiles/OWSProfileManager.h
Signal/src/Profiles/OWSProfileManager.m
Signal/src/ViewControllers/ProfileViewController.m

resize profile avatar

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m

I found and fixed a repro for yet another form of the "stale mappings" bug.  Namely, we need to `beginLongLivedReadTransaction` and `update mappings` in that order and avoid doing any layout after the first step but before the second step is done.

Fix layout glitch in messages view.

---

Signal/src/Profiles/OWSProfileManager.m

Rework concurrency in the profile manager.

---

Signal/src/Profiles/OWSProfileManager.m

Fix “profiles not encoded” bug.

---

Signal/src/Profiles/OWSProfileManager.h
Signal/src/Profiles/OWSProfileManager.m
Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Observe profile changes in conversation view.

---

SignalServiceKit/src/TSConstants.h

Only use staging service in debug builds.

---

Signal/src/Profiles/OWSProfileManager.m

We were opening a write transaction before our sync extensions were
registered. This seems to have caused our views to rebuild themselves
once they did register, which in turn can cause device timeout.
Instead of opening transcations in `init` we should explicitly setup any
state once we know the db to be in a ready state.

Fix slow start crash after upgrade to 2.16

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Fixes a serious perf bug I introduced with earlier work in this release.

Ensure message view range is properly truncated with view is configured.

---

Signal/src/Profiles/OWSProfileManager.h
Signal/src/Profiles/OWSProfileManager.m
Signal/src/ViewControllers/DebugUI/DebugUIMisc.m

Debug action to clobber local profile and key

---

Signal/src/Profiles/OWSProfileManager.h
Signal/src/Profiles/OWSProfileManager.m
Signal/src/ViewControllers/ContactsViewHelper.m

Don't add avatar to new contacts.

---

Signal/src/Profiles/OWSProfileManager.m
Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Fix group profile whitelist check.

---

Signal/src/Profiles/OWSProfileManager.h
Signal/src/Profiles/OWSProfileManager.m
Signal/src/ViewControllers/ProfileViewController.m
Signal/translations/en.lproj/Localizable.strings

Show an error when profile name is too long.

---

Signal/src/Profiles/OWSProfileManager.m

Clear the local profile avatar immediately when we request upload form.

---

Signal.xcodeproj/project.pbxproj
Signal/src/AppDelegate.m
Signal/src/MultiDeviceProfileKeyUpdateJob.swift
Signal/src/Profiles/OWSProfileManager.m
Signal/src/Signal-Bridging-Header.h
Signal/src/ViewControllers/OWSLinkDeviceViewController.m
Signal/src/util/OWSContactsSyncing.h
Signal/src/util/OWSContactsSyncing.m
SignalServiceKit/protobuf/OWSProvisioningProtos.proto
SignalServiceKit/protobuf/OWSSignalServiceProtos.proto
SignalServiceKit/src/Devices/OWSContactsOutputStream.h
SignalServiceKit/src/Devices/OWSContactsOutputStream.m
SignalServiceKit/src/Devices/OWSDeviceProvisioner.h
SignalServiceKit/src/Devices/OWSDeviceProvisioner.m
SignalServiceKit/src/Devices/OWSProvisioningMessage.h
SignalServiceKit/src/Devices/OWSProvisioningMessage.m
SignalServiceKit/src/Devices/OWSProvisioningProtos.pb.h
SignalServiceKit/src/Devices/OWSProvisioningProtos.pb.m
SignalServiceKit/src/Messages/DeviceSyncing/OWSOutgoingSyncMessage.m
SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncContactsMessage.h
SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncContactsMessage.m
SignalServiceKit/src/Messages/OWSSignalServiceProtos.pb.h
SignalServiceKit/src/Messages/OWSSignalServiceProtos.pb.m
SignalServiceKit/src/Messages/TSMessagesManager.m
SignalServiceKit/src/Protocols/ProfileManagerProtocol.h
SignalServiceKit/src/Protocols/ProtoBuf+OWS.h
SignalServiceKit/src/Protocols/ProtoBuf+OWS.m

Syncing both our own and any contact profile keys we know about.
More comments inline.

profile key sync

---

Signal/src/Profiles/OWSProfileManager.m

sync local profile as soon as it's created

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Fix yet another edge case around message view scroll state.

---

Signal/src/views/OWSSystemMessageCell.m

Fix RTL layout of system message cells.

---

Signal/src/AppDelegate.m
Signal/src/Profiles/OWSProfileManager.h
Signal/src/Profiles/OWSProfileManager.m

Re-sync local profile state with service if necessary.

---

SignalServiceKit/src/Messages/TSMessagesManager.m

Don't ignore attachments.

---

SignalServiceKit/src/TSConstants.h

Modify debug builds to use production service.

---

Signal/src/ViewControllers/ProfileViewController.m

Use "skip" not "stop" in profile upgrade nag.

---

Signal.xcodeproj/project.pbxproj
Signal/src/Profiles/OWSProfileManager.h
Signal/src/Profiles/OWSProfileManager.m
Signal/src/ViewControllers/ProfileViewController.m
Signal/src/util/TextFieldHelper.swift

enforce name length limit

---

Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Refine message view's initial range size.

---

Signal/src/Signal-Bridging-Header.h
Signal/src/UserInterface/Strings.swift
Signal/src/ViewControllers/AttachmentApprovalViewController.swift
Signal/src/ViewControllers/AvatarViewHelper.m
Signal/src/ViewControllers/BlockListUIUtils.m
Signal/src/ViewControllers/ContactsPicker.swift
Signal/src/ViewControllers/ContactsViewHelper.m
Signal/src/ViewControllers/CropScaleImageViewController.swift
Signal/src/ViewControllers/OWSLinkDeviceViewController.m
Signal/src/ViewControllers/SelectRecipientViewController.m
Signal/src/util/AppUpdateNag.m
Signal/src/views/OWSAlerts.swift
Signal/src/views/OWSBezierPathView.h
Signal/src/views/OWSBezierPathView.m
Signal/translations/en.lproj/Localizable.strings

- black masking style for avatar cropper
- cancel/done buttons
- no navbar for modal edit
- vertically center image

Revamp avatar cropper to show mask

---

Podfile.lock
Signal/src/ViewControllers/ConversationView/MessagesViewController.m

Depends on https://github.com/WhisperSystems/JSQMessagesViewController/pull/20

[JSQMVC] iOS11 compatability

---

Signal/src/AppDelegate.m
Signal/src/ViewControllers/HomeViewController.m

Move post-registration work from view to app delegate.

---

Signal/src/ViewControllers/ConversationView/ConversationViewController.m
SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.h
SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
SignalServiceKit/src/Messages/OWSMessageSender.m

Don't "scroll to bottom" when messages are sent from desktop.

---

Signal/src/ViewControllers/AppSettingsViewController.m
Signal/src/ViewControllers/ConversationView/ConversationViewController.m
Signal/src/ViewControllers/ModalActivityIndicatorViewController.swift
Signal/src/ViewControllers/NewGroupViewController.m
Signal/src/ViewControllers/SelectRecipientViewController.m

See: https://github.com/WhisperSystems/Signal-iOS/pull/2525

Respond to CR.

---

Signal/src/ViewControllers/AvatarViewHelper.m

This is in line with attachment picking and let's the user find photos
outside of "moments".
Fixes #2552 

Show album organizer for profile picker

---

Signal/src/AppDelegate.m

Startup logging.

---

Signal/src/Profiles/OWSProfileManager.m
Signal/src/Signal-Bridging-Header.h
Signal/src/ViewControllers/ConversationView/ConversationViewController.m
Signal/src/call/CallAudioService.swift
Signal/src/contact/OWSContactsManager.m
Signal/src/contact/SystemContactsFetcher.swift
SignalServiceKit/src/Account/TSAccountManager.m
SignalServiceKit/src/Devices/OWSReadReceiptsProcessor.m
SignalServiceKit/src/Messages/Attachments/OWSAttachmentsProcessor.m
SignalServiceKit/src/Messages/Interactions/TSIncomingMessage.m
SignalServiceKit/src/Messages/OWSBlockingManager.m
SignalServiceKit/src/Messages/OWSIdentityManager.m
SignalServiceKit/src/Network/API/OWSUploadingService.m
SignalServiceKit/src/Network/OWSSignalService.m
SignalServiceKit/src/Network/WebSockets/TSSocketManager.m
SignalServiceKit/src/Storage/TSDatabaseView.m
SignalServiceKit/src/Util/NSNotificationCenter+OWS.h
SignalServiceKit/src/Util/NSNotificationCenter+OWS.m

Post notifications asynchronously.

---

Signal.xcodeproj/project.pbxproj
Signal/src/AppDelegate.m
Signal/src/ViewControllers/ConversationView/ConversationViewController.m
Signal/src/ViewControllers/PrivacySettingsTableViewController.m
Signal/src/environment/OWSPreferences.h
Signal/src/environment/OWSPreferences.m
Signal/src/util/NSAttributedString+OWS.h
Signal/src/util/NSAttributedString+OWS.m
SignalServiceKit/src/Devices/OWSReadReceiptsForLinkedDevicesMessage.h
SignalServiceKit/src/Devices/OWSReadReceiptsForLinkedDevicesMessage.m
SignalServiceKit/src/Devices/OWSReadReceiptsForSenderMessage.h
SignalServiceKit/src/Devices/OWSReadReceiptsForSenderMessage.m
SignalServiceKit/src/Devices/OWSRecordTranscriptJob.h
SignalServiceKit/src/Devices/OWSRecordTranscriptJob.m
SignalServiceKit/src/Messages/Interactions/TSInteraction.h
SignalServiceKit/src/Messages/Interactions/TSInteraction.m
SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.h
SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
SignalServiceKit/src/Messages/OWSMessageHandler.m
SignalServiceKit/src/Messages/OWSMessageManager.m
SignalServiceKit/src/Messages/OWSOutgoingCallMessage.m
SignalServiceKit/src/Messages/OWSReadReceiptManager.h
SignalServiceKit/src/Messages/OWSReadReceiptManager.m
SignalServiceKit/src/Storage/TSStorageManager.m

This PR is now ready for review. 
* Send read receipts to senders.
* Honor "send read receipts" preference.
* Process read receipts from recipients.
* Refactor "mark as read" logic.
* Serialize and apply recipient read receipts received before sync transcript.
* Show recipient read receipts in conversation view.
// FREEBIE

Send, receive & show read receipts to senders/from receivers.

---

Signal/src/AppDelegate.m
Signal/src/ViewControllers/ConversationView/ConversationViewController.m
SignalServiceKit/src/Messages/OWSReadReceiptManager.h
SignalServiceKit/src/Messages/OWSReadReceiptManager.m

Hide all read receipts in UI if not enabled.

---

Signal/src/ViewControllers/ConversationView/ConversationViewController.m

Fix NPE in conversation view.

---

Signal/src/Profiles/OWSProfileManager.m
Signal/src/ViewControllers/HomeViewController.m
Signal/src/util/ThreadUtil.m
SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
SignalServiceKit/src/Messages/OWSProfileKeyMessage.m

I meant to include these changes in https://github.com/WhisperSystems/Signal-iOS/pull/2566

Address deadlocks in profile manager.

---

SignalServiceKit/src/Messages/OWSBatchMessageProcessor.m
SignalServiceKit/src/Messages/OWSMessageReceiver.m
SignalServiceKit/src/Storage/TSStorageManager.m

Fix class rename.

---

Signal/src/ViewControllers/MessageMetadataViewController.swift

Modify message metadata view to observe DB changes.

---

SignalServiceKit/src/Devices/OWSReadReceiptsForSenderMessage.m
SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.h
SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
SignalServiceKit/src/Messages/OWSMessageSender.m
SignalServiceKit/src/Messages/OWSMessageServiceParams.h
SignalServiceKit/src/Messages/OWSMessageServiceParams.m
SignalServiceKit/src/Messages/OWSOutgoingCallMessage.m

Send silent messages where appropriate.

---

Signal/src/ViewControllers/PrivacySettingsTableViewController.m
Signal/translations/en.lproj/Localizable.strings

Rework "send read receipts" setting.

---

Podfile.lock
SignalServiceKit/src/Devices/OWSRecordTranscriptJob.h
SignalServiceKit/src/Devices/OWSRecordTranscriptJob.m
SignalServiceKit/src/Messages/OWSMessageSender.h
SignalServiceKit/src/Messages/OWSMessageSender.m

Simplify processing of messages from linked devices.

---

Signal/src/ViewControllers/RegistrationViewController.m

Nudged the button down a bit now that it has more room to breath.

remove existing account button

---

Signal/translations/en.lproj/Localizable.strings

Update read receipts setting copy.

---

Signal/src/ViewControllers/ConversationView/ConversationViewController.m

Fix assert for empty thread

---

Signal/src/ViewControllers/NewGroupViewController.m
Signal/src/environment/NotificationsManager.m
SignalServiceKit/src/Messages/OWSBlockingManager.m
SignalServiceKit/src/Messages/OWSIdentityManager.m
SignalServiceKit/src/Messages/OWSMessageDecrypter.m
SignalServiceKit/src/Messages/OWSMessageManager.m
SignalServiceKit/src/Messages/OWSReadReceiptManager.m

Move more work off the main thread.

---

SignalServiceKit/src/Messages/OWSReadReceiptManager.m

Fix "mark as read on linked device".

---

Signal/src/ViewControllers/SendExternalFileViewController.m
Signal/src/environment/Environment.h
Signal/src/environment/Environment.m
Signal/src/network/PushManager.m

Show proper thread from notification

---

SignalServiceKit/src/Messages/Attachments/OWSAttachmentsProcessor.m
SignalServiceKit/src/Messages/Interactions/TSInteraction.h
SignalServiceKit/src/Messages/Interactions/TSInteraction.m
SignalServiceKit/src/Messages/OWSDisappearingMessagesJob.m
SignalServiceKit/src/Messages/OWSMessageSender.m
SignalServiceKit/src/Messages/OWSReadReceiptManager.m

More thread safety fixes.

---

Signal/translations/en.lproj/Localizable.strings

Change the "group members" item name.

---

Signal/src/views/OWSFlatButton.swift

Cap the flat button text size.

---

Signal/src/ViewControllers/MessageMetadataViewController.swift

Don't show recipient status group titles for 1:1 threads.

---

SignalServiceKit/src/Messages/OWSReadReceiptManager.m

Refine read receipt processing cycle.

---

Signal/src/ViewControllers/ConversationView/ConversationViewController.m

Increase hot area of scroll down button.

---

Signal/src/ViewControllers/ConversationView/ConversationViewController.m

Cowboy'ing this into the build for tonight's test pass.

Fix scroll down button.

---

Signal/src/ViewControllers/OWSLinkDeviceViewController.m
SignalServiceKit/protobuf/OWSProvisioningProtos.proto
SignalServiceKit/protobuf/OWSSignalServiceProtos.proto
SignalServiceKit/src/Devices/OWSDeviceProvisioner.h
SignalServiceKit/src/Devices/OWSDeviceProvisioner.m
SignalServiceKit/src/Devices/OWSProvisioningMessage.h
SignalServiceKit/src/Devices/OWSProvisioningMessage.m
SignalServiceKit/src/Devices/OWSProvisioningProtos.pb.h
SignalServiceKit/src/Devices/OWSProvisioningProtos.pb.m
SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncConfigurationMessage.h
SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncConfigurationMessage.m
SignalServiceKit/src/Messages/OWSMessageHandler.m
SignalServiceKit/src/Messages/OWSMessageManager.m
SignalServiceKit/src/Messages/OWSProfileKeyMessage.m
SignalServiceKit/src/Messages/OWSSignalServiceProtos.pb.h
SignalServiceKit/src/Messages/OWSSignalServiceProtos.pb.m

Sync configuration settings

---

SignalServiceKit/src/Messages/OWSMessageHandler.m
SignalServiceKit/src/Messages/OWSMessageManager.m
SignalServiceKit/src/Messages/OWSReadReceiptManager.h
SignalServiceKit/src/Messages/OWSReadReceiptManager.m

Sync read receipt configuration upon set

---

SignalServiceKit/src/Messages/OWSReadReceiptManager.m

Persist read receipts to proper collection

---

SignalServiceKit/src/Messages/OWSBlockingManager.h
SignalServiceKit/src/Messages/OWSBlockingManager.m
SignalServiceKit/src/Messages/OWSMessageManager.m

Respond to "sync block list" request.

---

Signal/src/network/GiphyAPI.swift

Use separate Giphy API key for Signal iOS.

---

SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncGroupsRequestMessage.m

Avoid phantom notifications for group info requests

---

Signal/src/call/CallService.swift

When awakened by a voip push, we get some arbitrary amount of background
time to connect the call (in practice this is ~30s) before the app is
suspended.
Though we were properly terminating the call upon being suspended, we
were not notifying the user that they had missed a call.

Suspend while answering shows "Missed Call"

---

Signal.xcodeproj/project.pbxproj
Signal/src/AppDelegate.m
Signal/src/Jobs/MessageFetcherJob.swift
Signal/src/UserInterface/Strings.swift
Signal/src/ViewControllers/ContactsPicker.swift
Signal/src/ViewControllers/ConversationView/ConversationViewController.m
Signal/src/ViewControllers/HomeViewController.m
Signal/src/ViewControllers/InboxTableViewCell.m
Signal/src/ViewControllers/NewContactThreadViewController.m
Signal/src/ViewControllers/NewGroupViewController.m
Signal/src/ViewControllers/OWSConversationSettingsViewController.m
Signal/src/ViewControllers/OWSTableViewController.h
Signal/src/ViewControllers/OWSTableViewController.m
Signal/src/contact/OWSContactsManager.h
Signal/src/contact/OWSContactsManager.m
Signal/src/environment/Environment.h
Signal/src/environment/Environment.m
Signal/src/environment/NotificationsManager.m
Signal/src/network/PushManager.m
Signal/src/util/Searcher.swift
Signal/src/views/ContactTableViewCell.h
Signal/src/views/ContactTableViewCell.m
Signal/src/views/GroupTableViewCell.swift
Signal/test/util/SearcherTest.swift
Signal/translations/en.lproj/Localizable.strings
SignalServiceKit/src/Messages/TSGroupModel.h
SignalServiceKit/src/Messages/TSGroupModel.m

This is useful when you're using censorship circumvention and unable to
receive push notifications.

Pull to refresh on homeview fetches messages.

---

SignalServiceKit/src/Network/WebSockets/TSSocketManager.m

Move write of incoming messages off main thread.

---

Signal/src/ViewControllers/ConversationView/ConversationViewController.m

Add vertical scroll indicator to conversation view.

---

Signal/src/ViewControllers/DebugUI/DebugUIMessages.m

Add actions to debug UI to inject fake incoming messages.

---

Signal/src/ViewControllers/ConversationView/ConversationViewController.m
Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
SignalServiceKit/src/Util/DataSource.m

Fix "can't send same GIF twice" issue.

---

Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.h
Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m
Signal/src/ViewControllers/ConversationView/ConversationViewController.m
Signal/src/ViewControllers/OWSViewController.h
Signal/src/ViewControllers/OWSViewController.m

Revert from numeric to default keyboard after message send.

---

Signal/src/ViewControllers/DebugUI/DebugUIMessages.m

Fix message injection.

---

Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m

Fix broken message cell layout.

---

Signal/src/ViewControllers/ConversationView/ConversationInputTextView.h
Signal/src/ViewControllers/ConversationView/ConversationInputTextView.m
Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.h
Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m
Signal/src/ViewControllers/ConversationView/ConversationViewController.m
Signal/src/ViewControllers/ConversationView/ConversationViewItem.h

This PR finalizes a bunch of changes from the JSQ rewrite.

Clean up conversation view.

---

Signal/src/ViewControllers/ConversationView/ConversationViewController.m

Fix "mark as read."

---

Signal/src/network/GiphyAPI.swift
Signal/src/network/GiphyDownloader.swift

Fix proxying of Giphy requests.

---

Signal/src/AppDelegate.m
Signal/src/environment/VersionMigrations.m

orphan cleanup shouldn't happen until DB is registered

---

Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m

Use proper color when messages fail to send.

---

Signal/src/ViewControllers/ConversationView/ConversationViewController.m

Never hide "failed to send" footer

---

Signal/src/ViewControllers/ConversationView/ConversationCollectionView.m
Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m

Fix layout glitches in JSQ rewrite.

---

Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m

Fix spacing around date headers.

---

Signal/src/ViewControllers/ConversationView/ConversationInputTextView.m
Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.h
Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m

Fixes for input toolbar.

---

Signal/src/ViewControllers/ConversationView/ConversationInputTextView.h
Signal/src/ViewControllers/ConversationView/ConversationInputTextView.m
Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m

Don't send with return key.

---

Signal/src/ViewControllers/GifPicker/GifPickerViewController.swift
Signal/src/ViewControllers/NewContactThreadViewController.m
Signal/src/ViewControllers/NewGroupViewController.m
Signal/src/ViewControllers/SelectThreadViewController.m
Signal/src/ViewControllers/UpdateGroupViewController.m

Update layout of views to reflect keyboard.

---

Signal/src/ViewControllers/ConversationView/Cells/AttachmentUploadView.m
Signal/src/ViewControllers/ConversationView/Cells/OWSAudioMessageView.m
Signal/src/ViewControllers/ConversationView/Cells/OWSGenericAttachmentView.m
Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
Signal/src/ViewControllers/ConversationView/ConversationInputTextView.m

RTL fixes for JSQ rewrite.

---

Signal/src/ViewControllers/ConversationView/ConversationViewController.m

This affects returning from message info or when leaving conversation
settings.

Fix "back button count" flash. Only call once.

---

Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
Signal/src/ViewControllers/MessageDetailViewController.swift
Signal/src/util/DisplayableText.swift

Fix edge cases around oversize test messages.

---

Signal/src/ViewControllers/MessageDetailViewController.swift

Hide MIME types in production builds.

---

Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
SignalServiceKit/src/Messages/Attachments/OWSAttachmentsProcessor.m
SignalServiceKit/src/Messages/Attachments/TSAttachment.h
SignalServiceKit/src/Messages/Attachments/TSAttachment.m
SignalServiceKit/src/Messages/Attachments/TSAttachmentPointer.h
SignalServiceKit/src/Messages/Attachments/TSAttachmentPointer.m
SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.h
SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.m
SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
SignalServiceKit/src/Messages/OWSMessageSender.m

Note this is for the release/2.18

Include size in attachment pointer

---

Signal/src/ViewControllers/ConversationView/ConversationInputTextView.m
Signal/src/ViewControllers/ConversationView/ConversationViewController.m

Don't overwrite draft after GIF send.

---

SignalServiceKit/src/Messages/OWSMessageSender.m

This should dramatically reduce the number of requests we make for most users.

Don't send sync messages to self if no linked devices.

---

Signal/src/ViewControllers/MessageDetailViewController.swift

Fix sizing of text bubbles in message detail view.

---

Signal/src/ViewControllers/GifPicker/GifPickerViewController.swift

Reduce progressive search delay

---

SignalServiceKit/src/Messages/Attachments/TSAttachment.m
SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m

Ensure attachments always have a valid content type.

---

Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
Signal/src/ViewControllers/ConversationView/ConversationViewItem.m

Constrain the max text cell height to the height of the screen.

---

Signal/src/AppDelegate.m
Signal/src/environment/NotificationsManager.h
Signal/src/environment/NotificationsManager.m
Signal/src/network/PushManager.m

Be more defensive about handling local notifications.

---

Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m

Clarify borders of input toolbar.

---

Signal/src/ViewControllers/AttachmentApprovalViewController.swift

Fix crashes in attachment approval view.

---

Signal/src/ViewControllers/ConversationView/ConversationViewController.m
Signal/src/ViewControllers/GifPicker/GifPickerViewController.swift

approve GIFs
