signalapp/Signal-iOS

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/ConversationInputTextView.h
- Signal/src/ViewControllers/ConversationView/ConversationInputTextView.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Fixes for scrolling in conversation view.

- Signal/src/ViewControllers/ConversationView/Cells/ConversationViewCell.m
> Layout cell content when presenting the cell.

- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
- SignalServiceKit/src/Messages/OWSMessageSender.m
* Improve handling of invalid message edge cases.
* Properly handle deletion of self-sent attachments.
> Improve handling of attachment edge cases.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Evacuate the view item cache.

- SignalServiceKit/src/Devices/OWSReadReceiptsForSenderMessage.m
- SignalServiceKit/src/Messages/DeviceSyncing/OWSOutgoingSyncMessage.m
- SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncGroupsRequestMessage.m
- SignalServiceKit/src/Messages/Interactions/OWSDisappearingMessagesConfigurationMessage.m
- SignalServiceKit/src/Messages/Interactions/OWSDynamicOutgoingMessage.m
- SignalServiceKit/src/Messages/Interactions/OWSEndSessionMessage.m
- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.h
- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
- SignalServiceKit/src/Messages/OWSMessageSender.m
- SignalServiceKit/src/Messages/OWSOutgoingCallMessage.m
- SignalServiceKit/src/Messages/OWSOutgoingNullMessage.m
- SignalServiceKit/src/Messages/OWSProfileKeyMessage.m
> Fix calling; be explicit about which messages should be saved.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Update UI to reflect changes to disappearing messages configuration.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
> Show menu controller from centroid of message cells.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
> Dismiss menu controller if message cell is hidden or recycled.

- Signal/src/OWSMessagesBubbleImageFactory.swift
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/MessageDetailViewController.swift
> message details shows failed bubble when appropriate

- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
> Increase the max text message length.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/translations/en.lproj/Localizable.strings
> Reduce font size of "load more" indicator.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
> Apply dynamic type sizing to Jumbomoji.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/OWSTableViewController.m
> Fix layout of table views vs. nav bar.

- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
> Fix group creation.

- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m
> Dismiss keyboard when leaving conversation view.

- Signal/src/ViewControllers/HomeViewController.m
- Signal/src/contact/OWSContactsManager.h
- Signal/src/contact/OWSContactsManager.m
- Signal/src/contact/SystemContactsFetcher.swift
> Only show contact nag if we've denied contact access

- Signal/src/ViewControllers/OWSLinkedDevicesTableViewController.m
> Fix "sliding tables" issue in linked devices view.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
I'm not sure why we were ever dismissing here. Any reason you know of? 
> Don't dismiss keyboard when view appears

- Signal/src/ViewControllers/ConversationView/Cells/OWSAudioMessageView.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.h
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.h
- SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.m
- SignalServiceKit/src/Messages/OWSReadReceiptManager.m
> Charlesmchen/conversation update edge cases 

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Fix connected call showing as "unanswered" until view reload

- Signal/src/UserInterface/SlideOffAnimatedTransition.swift
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Make swipe-for-details RTL-safe.

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/DebugUI/DebugUISyncMessages.h
- Signal/src/ViewControllers/DebugUI/DebugUISyncMessages.m
- Signal/src/ViewControllers/DebugUI/DebugUITableViewController.m
- SignalServiceKit/src/Messages/OWSMessageManager.m
- SignalServiceKit/src/Security/OWSRecipientIdentity.m
> Fix deadlock when responding to contacts sync messages.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Update layout of "scroll down button" to reflect RTL.

- Signal/src/ViewControllers/AdvancedSettingsTableViewController.m
- Signal/src/ViewControllers/DebugUI/DebugUIMisc.m
- Signal/src/ViewControllers/RegistrationViewController.m
- Signal/src/ViewControllers/SelectRecipientViewController.m
- Signal/translations/en.lproj/Localizable.strings
- SignalServiceKit/src/Contacts/PhoneNumber.h
- SignalServiceKit/src/Contacts/PhoneNumber.m
- SignalServiceKit/src/Contacts/PhoneNumberUtil.m
> Improve robustness around unknown country codes.

- Signal/src/ViewControllers/ConversationView/Cells/ConversationViewCell.m
> Force conversation view cells to update layout immediately.

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/ConversationView/ConversationScrollButton.h
- Signal/src/ViewControllers/ConversationView/ConversationScrollButton.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Update conversation view UI to reflect unread state.

- SignalServiceKit/src/Security/OWSRecipientIdentity.m
> Use dedicated db connection for recipient identities.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/util/ThreadUtil.m
> Improve handling of unread indicator edge cases.

- Signal/src/ViewControllers/ConversationView/Cells/ConversationViewCell.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Reload adjacent rows using original indices, not final indices.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> center "Loading More Messages" label

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
Update informative pages only, hence not tested on devices
Simplify informative github pages to use updated Signal websites.
Since Bithub is not functional anymore, remove Bithub references (in line with WhisperSystems/Signal-Android@0bcf46b)
> Update contributing.ms to use signal.org URLs; remove Bithub references

- SignalServiceKit/src/Network/OWSSignalService.m
> Remove concurrency limitations from signal service.

- Signal/src/Models/SignalAttachment.swift
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> We need to change file extensions when converting data

- Signal/src/OWSMessagesBubbleImageFactory.swift
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
Shaves ~5% off of initial conversation load, and pays ongoing dividends as you scroll.
> Memoize bubble factory

- Signal.xcodeproj/project.pbxproj
- Signal/src/AppDelegate.m
- Signal/src/util/MainAppContext.h
- Signal/src/util/MainAppContext.m
- SignalServiceKit/src/Util/AppContext.h
- SignalServiceKit/src/Util/AppContext.m
> Add application context class.

- Signal.xcodeproj/project.pbxproj
- SignalShareExtension/SignalShareExtension-Bridging-Header.h
- SignalShareExtension/SignalShareExtension-Prefix.pch
- SignalShareExtension/utils/ShareAppExtensionContext.h
- SignalShareExtension/utils/ShareAppExtensionContext.m
> Add app extension context, bridging header and PCH to app extension.

- SignalShareExtension/Info.plist
We'll probably want a predicate eventually.
> Use dict to specify supported types for SAE.

- Signal.xcodeproj/project.pbxproj
- Signal/src/environment/PushRegistrationManager.swift
- Signal/test/Models/AccountManagerTest.swift
- Signal/test/Models/MesssagesBubblesSizeCalculatorTest.swift
- Signal/test/call/PeerConnectionClientTest.swift
- Signal/test/util/DisplayableTextFilterTest.swift
- Signal/test/util/ImageCacheTest.swift
- Signal/test/util/SearcherTest.swift
- Signal/test/util/UtilTest.m
- SignalMessaging/environment/Environment.h
- SignalMessaging/environment/Environment.m
- SignalMessaging/environment/Release.m
- SignalMessaging/utils/ImageCache.swift
- SignalServiceKit/src/Account/TSAttributes.m
Some important changes here... I'll call them out in comments.
> Charlesmchen/sae vs tests 

- Signal.xcodeproj/project.pbxproj
- Signal/src/AppDelegate.m
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/utils/OWSPreferences.h
- SignalMessaging/utils/OWSPreferences.m
- SignalShareExtension/SAEFailedViewController.swift
- SignalShareExtension/SAELoadViewController.swift
- SignalShareExtension/ShareViewController.swift
> Add SAE error views.

- Signal.xcodeproj/project.pbxproj
- Signal/test/util/SearcherTest.swift
- SignalMessaging/utils/Searcher.swift
- SignalMessaging/utils/SwiftSingletons.swift
- SignalServiceKit/src/Util/NSObject+OWS.h
- SignalShareExtension/ShareViewController.swift
> Convert logTag to property.

- Signal.xcodeproj/project.pbxproj
> Add Estonian and Taiwanese Chinese localizations.

- SignalServiceKit/src/Util/OWSFileSystem.m
- SignalShareExtension/ShareViewController.swift
> Fix order of operations in SAE setup.

- Signal/src/ViewControllers/NewContactThreadViewController.m
- Signal/src/contact/OWSContactsManager.h
- Signal/src/contact/OWSContactsManager.m
- Signal/src/contact/SystemContactsFetcher.swift
- SignalServiceKit/src/Contacts/Contact.h
- SignalServiceKit/src/Contacts/Contact.m
- SignalServiceKit/src/Contacts/PhoneNumber.m
> replace cache for migration

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/attachments/AttachmentApprovalViewController.swift
- SignalMessaging/attachments/SharingThreadPickerViewController.m
- SignalMessaging/utils/ThreadUtil.h
- SignalMessaging/utils/ThreadUtil.m
> attachment progress/retry

- Signal/src/ViewControllers/DebugUI/DebugUIMisc.m
> Send database action in debug UI.

- SignalServiceKit/src/Storage/OWSStorage.m
> Fix storage reset.

- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.h
- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Fix keyboard animation glitch after sending

- Signal.xcodeproj/project.pbxproj
- SignalMessaging/contacts/CountryCodeViewController.h
- SignalMessaging/contacts/CountryCodeViewController.m
- SignalMessaging/contacts/ModalActivityIndicatorViewController.swift
- SignalMessaging/contacts/NewNonContactConversationViewController.h
- SignalMessaging/contacts/NewNonContactConversationViewController.m
- SignalMessaging/contacts/SelectRecipientViewController.h
- SignalMessaging/contacts/SelectRecipientViewController.m
- SignalMessaging/contacts/SelectThreadViewController.m
- SignalMessaging/contacts/ViewControllerUtils.h
- SignalMessaging/contacts/ViewControllerUtils.m
> Let users send to non-contacts, non-threads in SAE.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/MediaDetailViewController.m
> Fix media presentation

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/HomeViewController.m
- Signal/src/ViewControllers/MessageDetailViewController.swift
- Signal/src/ViewControllers/OWSLinkedDevicesTableViewController.m
- SignalMessaging/Views/ThreadViewHelper.m
- SignalServiceKit/src/Messages/OWSBatchMessageProcessor.h
- SignalServiceKit/src/Messages/OWSBatchMessageProcessor.m
- SignalServiceKit/src/Messages/OWSDisappearingMessagesFinder.h
- SignalServiceKit/src/Messages/OWSDisappearingMessagesFinder.m
- SignalServiceKit/src/Messages/OWSFailedAttachmentDownloadsJob.h
- SignalServiceKit/src/Messages/OWSFailedAttachmentDownloadsJob.m
- SignalServiceKit/src/Messages/OWSFailedMessagesJob.h
- SignalServiceKit/src/Messages/OWSFailedMessagesJob.m
- SignalServiceKit/src/Messages/OWSIdentityManager.h
- SignalServiceKit/src/Messages/OWSMessageManager.m
- SignalServiceKit/src/Messages/OWSMessageReceiver.h
- SignalServiceKit/src/Messages/OWSMessageReceiver.m
- SignalServiceKit/src/Storage/OWSIncomingMessageFinder.h
- SignalServiceKit/src/Storage/OWSIncomingMessageFinder.m
- SignalServiceKit/src/Storage/OWSStorage.h
- SignalServiceKit/src/Storage/OWSStorage.m
- SignalServiceKit/src/Storage/TSDatabaseView.h
- SignalServiceKit/src/Storage/TSDatabaseView.m
- SignalServiceKit/src/Storage/TSStorageManager.h
- SignalServiceKit/src/Storage/TSStorageManager.m
I decided to retain more changes from the abandoned "database workaround" branch, since they'll be useful if we do user-facing backup.
> Retain changes from session database branch.

- Signal/src/ViewControllers/OWSLinkDeviceViewController.m
- Signal/src/ViewControllers/OWSLinkedDevicesTableViewController.m
- SignalServiceKit/src/Devices/OWSDevice.h
- SignalServiceKit/src/Devices/OWSDevice.m
- SignalServiceKit/src/Messages/OWSMessageManager.m
- SignalServiceKit/src/Messages/OWSMessageSender.m
> Skip redundant sync messages.

- Signal/src/util/MainAppContext.m
- SignalMessaging/Views/ThreadViewHelper.m
- SignalMessaging/contacts/SystemContactsFetcher.swift
- SignalServiceKit/src/Storage/OWSStorage.m
- SignalServiceKit/src/Util/AppContext.h
- SignalShareExtension/utils/ShareAppExtensionContext.m
> Don't use mainApplicationState in business logic.

- Podfile.lock
Updates to reflect https://github.com/WhisperSystems/GRKOpenSSLFramework/pull/2
> Update OpenSSL to new version, app extension compliant.

- Signal/src/ViewControllers/MediaDetailViewController.m
> Fix confirmation preview

- Signal/src/ViewControllers/ConversationView/Cells/OWSExpirationTimerView.m
Fixes problems where the small timer icon is initially off by a couple pixels.
i.e. fixes this:
> Fix timer offset

- Podfile.lock
See: https://github.com/WhisperSystems/GRKOpenSSLFramework/pull/3
> Update OpenSSL build.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- SignalMessaging/attachments/SignalAttachment.swift
> Add support for images as documents.

- Signal/test/util/DisplayableTextFilterTest.swift
- Signal/test/util/OWSDatabaseConverterTest.m
> Fixup some tests

- SignalShareExtension/ShareViewController.swift
> Fix SAE readiness.

- Signal/src/call/CallService.swift
Fixes https://github.com/signalapp/Signal-iOS/issues/2958
> Fix receiving calls

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/views/DirectionalPanGestureRecognizer.swift
- Signal/translations/en.lproj/Localizable.strings
Fixes https://github.com/WhisperSystems/Signal-iOS/issues/2879
> Only activate "Show detail" pan gesture when swiping left

- Signal/src/util/MainAppContext.m
- SignalMessaging/Views/ContactsViewHelper.m
- SignalMessaging/views/OWSAlerts.swift
- SignalServiceKit/src/Util/AppContext.h
- SignalShareExtension/utils/ShareAppExtensionContext.m
> Cannot open settings from share extension

- SignalMessaging/attachments/AttachmentApprovalViewController.swift
FYI filed a related bug with PureLayout: https://github.com/PureLayout/PureLayout/issues/209
and will follow up with a PR to them.
> Fix "caption toolbar not showing" for RTL

- Signal/src/AppDelegate.m
- Signal/src/util/Pastelog.h
- Signal/src/util/Pastelog.m
- Signal/translations/en.lproj/Localizable.strings
> Let users submit debug logs if app launch fails.

- Signal/src/AppDelegate.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- SignalMessaging/profiles/ProfileFetcherJob.swift
- SignalServiceKit/src/Storage/OWSStorage.h
- SignalServiceKit/src/Storage/OWSStorage.m
- SignalServiceKit/src/Util/AppVersion.h
- SignalServiceKit/src/Util/AppVersion.m
- SignalShareExtension/ShareViewController.swift
- SignalShareExtension/utils/ShareAppExtensionContext.m
> Charlesmchen/sae TODOs

- Signal/src/AppDelegate.m
> Defer handling app delegate hooks until app is ready.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
> Tweak debug logging.

- BUILDING.md
- CONTRIBUTING.md
- MAINTAINING.md
- Podfile
- Podfile.lock
- README.md
- SettingsBundle/licenses/AxolotlKit.license
- SignalMessaging/attachments/SignalAttachment.swift
- SignalServiceKit.podspec
- SignalServiceKit/CONTRIBUTING.md
- SignalServiceKit/Example/TSKitiOSTestApp/Podfile
- SignalServiceKit/README.md
- SignalServiceKit/src/Messages/OWSMessageManager.m
- SignalServiceKit/src/Messages/OWSMessageServiceParams.h
- SignalServiceKit/src/Util/NSData+messagePadding.m
This fixes almost all of the references to the old GitHub organization name. The lock files for the CocoaPods should be updated separately.
> Update to the new GitHub organization name

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/DebugUI/DebugUICalling.swift
- Signal/src/ViewControllers/DebugUI/DebugUINotifications.swift
- Signal/src/ViewControllers/DebugUI/DebugUITableViewController.m
- Signal/src/environment/NotificationsManager.m
- SignalMessaging/utils/DisplayableText.swift
Also, consolidated the notifications debug UI (and fixed it) to make testing
this a bit easier.
> Fix notification % escaping, debug UI

- Signal/src/ViewControllers/HomeViewController.m
- Signal/src/ViewControllers/NewContactThreadViewController.m
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/utils/OWSPreferences.h
- SignalMessaging/utils/OWSPreferences.m
- SignalMessaging/views/OWSAlerts.swift
- SignalServiceKit/src/Account/TSPreKeyManager.m
- SignalServiceKit/src/Contacts/OWSDisappearingMessagesConfiguration.h
- SignalServiceKit/src/Contacts/OWSDisappearingMessagesConfiguration.m
- SignalServiceKit/src/Util/NSDate+OWS.h
- SignalServiceKit/src/Util/NSDate+OWS.mm
> Aggressively nag iOS 8 users to upgrade iOS.

- SignalShareExtension/ShareViewController.swift
> Refine the SAE lifecycle.

- SignalShareExtension/ShareViewController.swift
> Don't apply signal appearance in SAE.

- Signal/src/ViewControllers/Utils/MessageRecipientStatusUtils.swift
- Signal/translations/en.lproj/Localizable.strings
> Fix failed status messages in message detail view.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Always scroll to bottom after sending attachments.

- SignalMessaging/profiles/OWSUserProfile.m
> Fix issues around profile updates.

- SignalMessaging/attachments/SharingThreadPickerViewController.m
- SignalMessaging/profiles/OWSUserProfile.m
- SignalServiceKit/src/Util/DataSource.m
- SignalShareExtension/ShareViewController.swift
> Apply Indic script fixes to SAE and master.

- SignalServiceKit/src/Network/API/TSNetworkManager.m
- SignalServiceKit/src/Network/WebSockets/TSSocketManager.m
> Improve logging around network activity.

- SignalMessaging/attachments/SignalAttachment.swift
> Fix handling of HEIF/HEIC when attaching image "as document."

- Signal/src/AppDelegate.m
- SignalMessaging/profiles/OWSProfileManager.h
- SignalMessaging/profiles/OWSProfileManager.m
- SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.h
- SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.m
- SignalServiceKit/src/Storage/TSStorageManager.h
- SignalServiceKit/src/Storage/TSStorageManager.m
- SignalServiceKit/src/Util/NSUserDefaults+OWS.m
- SignalServiceKit/src/Util/OWSAsserts.h
- SignalServiceKit/src/Util/OWSError.h
- SignalServiceKit/src/Util/OWSFileSystem.h
- SignalServiceKit/src/Util/OWSFileSystem.m
> Improve the robustness of the migration logic.

- SignalServiceKit/src/Storage/OWSStorage.m
> Use background tasks during db transactions.

- Signal/src/AppDelegate.m
> Don't clear legacy db password until conversion completes.

- Signal/src/ViewControllers/InboxTableViewCell.m
There's been a long standing low level crash here.
> Handle nil date when formatting

- Signal/src/ViewControllers/MessageDetailViewController.swift
> Fix "Share" for attachment with caption

- SignalServiceKit/src/Messages/Interactions/TSMessage.m
- SignalServiceKit/src/Messages/OWSMessageSender.m
> Improve handling of attachments with captions.

- Signal/src/AppDelegate.m
> Use background task while migrating.

- SignalServiceKit/src/Messages/OWSReadReceiptManager.m
> Convert duplicate timestamp fail to log.

- Signal/src/util/UIViewController+Permissions.m
> Fix crash presenting settings dialog off main thread

- Signal/src/AppDelegate.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- Signal/src/ViewControllers/DebugUI/DebugUIMisc.m
- Signal/src/ViewControllers/DebugUI/DebugUISyncMessages.m
- Signal/src/util/Pastelog.h
- Signal/src/util/Pastelog.m
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/profiles/OWSProfileManager.m
- SignalMessaging/utils/DebugLogger.h
- SignalMessaging/utils/DebugLogger.m
- SignalShareExtension/Info.plist
- SignalShareExtension/ShareViewController.swift
This is sort of a stop gap intended to be minimal and safe.
> Fix sharing url when text is also present

- SignalServiceKit/src/Devices/OWSGroupsOutputStream.m
Must add properties *before* build
> Fix group-sync disabling disappearing timer

- SignalServiceKit/src/Devices/OWSContactsOutputStream.m
- SignalServiceKit/src/Devices/OWSGroupsOutputStream.m
> Be explicit when disappearing messages are disabled

- Signal/src/views/RemoteVideoView.m
> Fix remote video view

- SignalServiceKit/src/Devices/OWSContactsOutputStream.m
- SignalServiceKit/src/Devices/OWSGroupsOutputStream.h
- SignalServiceKit/src/Devices/OWSGroupsOutputStream.m
- SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncGroupsMessage.m
> Be more explicit about expire timer.

- SignalMessaging/environment/OWSSounds.m
> Fix migration to work with fallback notifications as well

- Signal/src/call/CallService.swift
- SignalMessaging/environment/AppSetup.m
- SignalMessaging/environment/Release.m
- SignalServiceKit/src/Util/OWSBackgroundTask.h
- SignalServiceKit/src/Util/OWSBackgroundTask.m
> Share background tasks.

- Signal/src/ViewControllers/CodeVerificationViewController.m
- Signal/translations/en.lproj/Localizable.strings
- SignalServiceKit/src/Account/TSAccountManager.m
> Handle rate limits in registration flow.

- Signal/src/ViewControllers/OWS2FARegistrationViewController.m
- Signal/translations/en.lproj/Localizable.strings
- SignalServiceKit/src/Account/TSAccountManager.m
> Make 2FA registration screen look like the rest of registration

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/ExperienceUpgradesPageViewController.swift
- Signal/src/environment/NotificationsManager.m
- SignalMessaging/attachments/OWSVideoPlayer.swift
- SignalMessaging/environment/OWSAudioSession.swift
- SignalMessaging/environment/OWSSounds.h
- SignalMessaging/environment/OWSSounds.m
- SignalMessaging/utils/OWSAudioPlayer.h
- SignalMessaging/utils/OWSAudioPlayer.m
> In-App notifications don't pause background audio

- Signal.xcodeproj/project.pbxproj
- SignalMessaging/environment/migrations/OWS108CallLoggingPreference.h
- SignalMessaging/environment/migrations/OWS108CallLoggingPreference.m
- SignalMessaging/utils/OWSPreferences.h
- SignalMessaging/utils/OWSPreferences.m
> more conservative call logging

- SignalMessaging/environment/migrations/OWSDatabaseMigrationRunner.m
> run call settings migration

- Scripts/debug_log_upload.py
- Signal/src/util/Pastelog.m
- SignalMessaging/utils/OWSPreferences.m
- SignalServiceKit/src/Util/MIMETypeUtil.h
- SignalServiceKit/src/Util/MIMETypeUtil.m
content-type is now not only available, but required.
> Fix debuglogs.org integration

- Signal/Signal-Info.plist
- Signal/src/AppDelegate.m
> Try to keep-alive registration lock w/ bg fetch

- Signal/src/ViewControllers/DebugUI/DebugUIMisc.m
- SignalServiceKit/src/Util/OWS2FAManager.h
- SignalServiceKit/src/Util/OWS2FAManager.m
Schedule first reminder date relative to now.
> Fix first reminder too early, offset bugs.

- Signal/src/ViewControllers/OWS2FARegistrationViewController.m
- Signal/src/call/NonCallKitCallUIAdaptee.swift
- Signal/src/views/PinEntryView.m
> fix 2fa registration layout

- SignalMessaging/profiles/OWSUserProfile.m
> Fix redundant profile downloads

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/OWS2FAReminderViewController.swift
- Signal/src/views/PinEntryView.h
- Signal/src/views/PinEntryView.m
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/SignalMessaging.h
- SignalShareExtension/ShareViewController.swift
Added some details to better explain what the reminder view is.
Layout needs to be kept tight for small form factors, but it was overly
cramped on larger devices.
> Clarify reminder view, touchup layout

- SignalServiceKit/src/Util/OWSBackgroundTask.m
> Fix typo in background task.

- README.md
* iDevice A, iOS X.Y.Z
* iDevice B, iOS Z.Y
It's just the copyright year update, a pretty trivial change, so I have not tested it
> update copyright year

- Signal/src/ViewControllers/MediaDetailViewController.h
- Signal/src/ViewControllers/MediaDetailViewController.m
- Signal/src/ViewControllers/MediaGalleryViewController.swift
- Signal/src/ViewControllers/MediaPageViewController.swift
- SignalMessaging/utils/Bench.swift
> Clear PageView cache when receiving memory warning

- Signal/src/ViewControllers/MediaTileViewController.swift
> Better UI when scrolling through media tile view

- Signal/src/ViewControllers/MediaDetailViewController.m
- Signal/src/ViewControllers/MediaPageViewController.swift
> Stop any video whenever leaving PageView

- SignalMessaging/environment/OWSAudioSession.swift
Occasionally when doing things like starting a video and then immediately navigating away, we would fail to terminate our audio session.
My first change was to synchronize on self when messing with audioActivities.
Which is a good thing to do, considering we don't always manipulate the audio session on the main thread. Unfortunately, that was insufficient to avoid the crash.
Though it's not elegant, introducing a small delay before deactivation seems to do the trick.
> Avoid occasional audio crash

- Signal/src/ViewControllers/MediaDetailViewController.h
- Signal/src/ViewControllers/MediaDetailViewController.m
- Signal/src/ViewControllers/MediaPageViewController.swift
> Only try to stop video when it *is* a video

- Signal/src/Signal-Bridging-Header.h
- Signal/src/ViewControllers/MediaPageViewController.swift
- Signal/translations/en.lproj/Localizable.strings
> Dynamic gallery slider label

- Signal/src/ViewControllers/MediaTileViewController.swift
- Signal/translations/en.lproj/Localizable.strings
> Handle empty media gallery

- SignalServiceKit/src/Messages/OWSMessageSender.m
> Don't log message send errors.

- Signal/src/ViewControllers/AppSettings/PrivacySettingsTableViewController.m
- Signal/src/util/OWSScreenLock.swift
- Signal/src/util/OWSScreenLockUI.m
- Signal/translations/en.lproj/Localizable.strings
> Refine 'Screen Lock'.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- Signal/src/ViewControllers/MediaDetailViewController.h
- Signal/src/ViewControllers/MediaDetailViewController.m
- Signal/src/ViewControllers/MediaGalleryViewController.swift
- Signal/src/ViewControllers/MediaPageViewController.swift
- Signal/src/ViewControllers/MediaTileViewController.swift
- Signal/src/ViewControllers/MessageDetailViewController.swift
- Signal/translations/en.lproj/Localizable.strings
> delete from slider view

- Signal/src/ViewControllers/MediaPageViewController.swift
> Stop any video on dismiss

- Signal/src/ViewControllers/MediaGalleryViewController.swift
- Signal/src/ViewControllers/MediaPageViewController.swift
> Gallery animation fixups

- Signal/src/util/OWSScreenLockUI.m
> Fix edge cases around pincode-only unlock.

- Signal/src/util/OWSScreenLockUI.m
> Fix edge case in screen lock UI.

- Signal/src/ViewControllers/MediaDetailViewController.h
- Signal/src/ViewControllers/MediaDetailViewController.m
- Signal/src/ViewControllers/MediaPageViewController.swift
- SignalMessaging/attachments/VideoPlayerView.swift
> Improve video scrubbing UX in PageView

- Signal/src/ViewControllers/AppSettings/PrivacySettingsTableViewController.m
- SignalMessaging/attachments/SignalAttachment.swift
- SignalMessaging/utils/OWSPreferences.h
- SignalMessaging/utils/OWSPreferences.m
> Always remove metadata

- Signal/src/util/OWSScreenLock.swift
- Signal/src/util/OWSScreenLockUI.m
> Improve handling of unexpected failures in local authentication.

- Signal/src/util/OWSScreenLockUI.m
> Start screen lock countdown if app is inactive for more than N seconds.

- Signal.xcodeproj/project.pbxproj
- Signal/src/util/OWSScreenLock.swift
- Signal/src/util/UI Categories/UIResponder+OWS.swift
I tried to leave thorough comments in the code, as this is a bit arcane.
> Don't obscure "Unlock" button with keyboard

- Signal/src/AppDelegate.m
> Only resume lazy attachment restore in debug.

- Signal/src/ViewControllers/ConversationView/Cells/OWSBubbleStrokeView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSBubbleView.m
> Fix assert in bubble views.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessagesAssetLoader.h
- Signal/src/ViewControllers/DebugUI/DebugUIMessagesAssetLoader.m
- SignalServiceKit/src/Messages/Attachments/TSAttachment.h
- SignalServiceKit/src/Messages/Attachments/TSAttachment.m
> Elaborate 'quoted reply' variations in the Debug UI.

- Signal.xcodeproj/project.pbxproj
- Signal/src/environment/NotificationsManager.m
- Signal/src/network/GiphyDownloader.swift
- SignalMessaging/environment/OWSSounds.h
- SignalMessaging/environment/OWSSounds.m
- SignalMessaging/utils/LRUCache.swift
- SignalMessaging/utils/OWSAudioPlayer.h
- SignalMessaging/utils/OWSAudioPlayer.m
Fixes https://github.com/signalapp/Signal-iOS/issues/3145
> Respect system alert volume for notifications while in app

- Signal/src/ViewControllers/MediaPageViewController.swift
> Don't use dynamic text for navbar view

- Signal/src/util/OWSScreenLockUI.m
> Fix screen lock edge case.

- Signal.xcodeproj/project.pbxproj
- Signal.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Signal/src/ViewControllers/ConversationView/Cells/ConversationViewCell.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.h
- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- Signal/src/ViewControllers/DebugUI/DebugUIMisc.m
- Signal/src/ViewControllers/MessageDetailViewController.swift
- Signal/src/network/PushManager.m
- Signal/src/util/Pastelog.m
- Signal/src/views/AttachmentPointerView.swift
- Signal/src/views/GroupTableViewCell.swift
- Signal/src/views/QuotedReplyPreview.swift
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/attachments/AttachmentApprovalViewController.swift
- SignalMessaging/attachments/MessageApprovalViewController.swift
- SignalMessaging/attachments/SharingThreadPickerViewController.m
- SignalMessaging/categories/UIFont+OWS.h
- SignalMessaging/utils/ThreadUtil.h
- SignalMessaging/utils/ThreadUtil.m
- SignalServiceKit/src/Messages/Interactions/TSQuotedMessage.h
- SignalServiceKit/src/Messages/Interactions/TSQuotedMessage.m
- SignalServiceKit/src/Messages/OWSMessageUtils.h
- SignalServiceKit/src/Messages/OWSMessageUtils.m
There are several design TODO's plus some other niceties, but this is at a level of base functionality.
**New reply item in edit menu**:
**Quote other person (just text)**:
**Quote self (captioned image)**:
**Quote self (just image)**:
> Send quoted reply

- Signal/src/util/OWSScreenLock.swift
- Signal/src/util/OWSScreenLockUI.m
> Fix screen lock edge cases.

- Signal/src/ViewControllers/ConversationView/Cells/OWSContactOffersCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSSystemMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSUnreadIndicatorCell.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/InboxTableViewCell.m
- Signal/src/ViewControllers/MessageDetailViewController.swift
- Signal/src/ViewControllers/ProfileViewController.m
- Signal/src/ViewControllers/ThreadSettings/OWSConversationSettingsViewController.m
- Signal/src/views/AttachmentPointerView.swift
- Signal/src/views/GroupTableViewCell.swift
- Signal/src/views/QuotedReplyPreview.swift
- SignalMessaging/Views/ContactTableViewCell.m
- SignalMessaging/categories/UIFont+OWS.h
- SignalMessaging/categories/UIFont+OWS.m
This PR is now ready for review.
This only covers the most common text in conversation view: message bodies, status messages, etc.  I haven't done less common places (like missing attachment indicator) yet.
> Apply dynamic type in conversation view.

- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/translations/en.lproj/Localizable.strings
> Tweak design of quoted replies.

- SignalMessaging/categories/UIFont+OWS.m
> Don't use scaledFontForFont.

- Signal/src/util/OWSScreenLock.swift
> Never recycle biometric auth.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m
> Tweak message layout.

- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- SignalMessaging/Models/OWSQuotedReplyModel.m
- SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.m
* Don't let users reply to non-sent outgoing messages.
* Don't let users reply to non-downloaded incoming attachments.
> Enforce quoted reply edge cases.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/attachments/AttachmentApprovalViewController.swift
- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
> limit caption length

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
> Add white background to images in conversation view.

- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m
> Fix quoted message overflow.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.h
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
> Fix long press on quoted reply.

- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/Models/OWSQuotedReplyModel.m
> Label quoted replies to yourself as such.

- SignalMessaging/contacts/SystemContactsFetcher.swift
- SignalMessaging/profiles/ProfileFetcherJob.swift
- SignalServiceKit/src/Messages/OWSBatchMessageProcessor.m
> Reduce 0xdead10cc crashes.

- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
Regression introduced in Message factory method refactor (not in the wild).
> Fix spurious "Group Updated" message

- SignalServiceKit/protobuf/OWSSignalServiceProtos.proto
- SignalServiceKit/src/Messages/OWSSignalServiceProtos.pb.h
- SignalServiceKit/src/Messages/OWSSignalServiceProtos.pb.m
- protobuf/Makefile
> Make our QuotedAttachment protos backwards compatible with Signal-Android

- SignalServiceKit/src/Messages/OWSBatchMessageProcessor.m
> Move 'background' check in message processing logic off main thread.

- SignalServiceKit/src/Messages/OWSMessageSender.m
> Reduce oversize text size.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m
- Signal/translations/en.lproj/Localizable.strings
> Distinguish between quoting yourself and someone else quoting you

- Signal.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Signal/src/ViewControllers/AppSettings/OWSLinkedDevicesTableViewController.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/MediaDetailViewController.m
- Signal/src/ViewControllers/MessageDetailViewController.swift
- SignalMessaging/ViewControllers/OWSTableViewController.m
- SignalMessaging/categories/UIView+OWS.h
- SignalMessaging/categories/UIView+OWS.m
> Fix message details layout in iPhone X.

- Signal.xcodeproj/project.pbxproj
- Signal/test/util/StringAdditionsTest.swift
- SignalMessaging/attachments/AttachmentApprovalViewController.swift
- SignalMessaging/categories/String+OWS.swift
> Limit attachment caption length to 2k bytes

- Signal/src/util/OWSScreenLockUI.m
- SignalMessaging/categories/UIView+OWS.h
- SignalMessaging/categories/UIView+OWS.m
> Fix animation glitch in blocking window.

- Signal/src/ViewControllers/ConversationView/Cells/OWSBubbleStrokeView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSBubbleView.m
- Signal/src/views/AudioProgressView.swift
- Signal/src/views/OWSBezierPathView.m
- Signal/src/views/OWSProgressView.m
> Don't animate changes to shape layer properties.

- Signal/src/ViewControllers/CallViewController.swift
- Signal/src/util/OWSScreenLockUI.m
> Resolve conflict between keyboard and call view.

- Signal/src/ViewControllers/ConversationView/Cells/ConversationViewCell.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/MessageDetailViewController.swift
> Fix taps in message cells.

- SignalServiceKit/src/Storage/OWSPrimaryStorage.h
- SignalServiceKit/src/Storage/OWSPrimaryStorage.m
- SignalServiceKit/src/Storage/OWSStorage.h
- SignalServiceKit/src/Storage/OWSStorage.m
- SignalServiceKit/src/Storage/TSDatabaseView.h
- SignalServiceKit/src/Storage/TSDatabaseView.m
> Rework flush of registration connection(s).

- Signal/src/ViewControllers/HomeView/HomeViewCell.m
> home screen design tweaks

- Signal/src/ViewControllers/CallViewController.swift
- Signal/src/call/CallAudioService.swift
- Signal/src/call/CallService.swift
- Signal/src/call/PeerConnectionClient.swift
- Signal/src/call/SignalCall.swift
- Signal/translations/en.lproj/Localizable.strings
Video/screenshots sent out of band.
> surface call reconnecting

- Signal/src/ViewControllers/CallViewController.swift
- Signal/src/call/CallService.swift
- Signal/src/call/PeerConnectionClient.swift
- Signal/src/call/UserInterface/CallUIAdapter.swift
I'm waiting on the final button asset, but that should be a trivial drop in.
> Toggle rear camera in video call

- Signal/src/AppDelegate.m
> Show database upgrade warning while launching v2.25 or later.

- Signal/src/call/PeerConnectionClient.swift
> Fix call hangup crashes.

- Signal/src/ViewControllers/HomeView/HomeViewController.m
> Fix global reference to 'inbox' home view.

- SignalServiceKit/protobuf/OWSSignalServiceProtos.proto
- SignalServiceKit/src/Messages/OWSSignalServiceProtos.pb.h
- SignalServiceKit/src/Messages/OWSSignalServiceProtos.pb.m
See: https://github.com/signalapp/libsignal-service-java/commit/7c3fb63e53daa8c925c82b3e58a03f8a14ad04d4#diff-c525e47fbed26da2110c8a7c37a37031
> Update protos to reflect 'share contact'.

- SignalServiceKit/src/Messages/DeviceSyncing/OWSOutgoingSentMessageTranscript.m
- SignalServiceKit/src/Messages/OWSMessageSender.m
> Fix glitches in outgoing messages.

- SignalServiceKit/src/Contacts/ContactsUpdater.m
- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.h
- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
- SignalServiceKit/src/Messages/OWSMessageSender.m
> More outgoing message fixes.

- SignalServiceKit/src/Messages/Interactions/OWSContact.h
- SignalServiceKit/src/Messages/Interactions/OWSContact.m
> Rework contact normalization and validation.

- Signal/src/ViewControllers/MediaPageViewController.swift
We must specify the frame of the titleView for iOS9/10.
Previously the titleView was a stackview, but we don't want to
"stretch" the labels to fit the size of the stack view, so we wrap the
stack view in a container view which becomes the new titleView.
**iOS 9**
**iOS 10**
**iOS 11**
> Fix media page title view on iOS9/10

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- SignalServiceKit/src/Messages/Interactions/OWSContact.h
- SignalServiceKit/src/Messages/Interactions/OWSContact.m
> Add feature flag for contact sharing.

- SignalServiceKit/src/Messages/OWSMessageSender.m
> Handle completely skipped message sends.

- SignalServiceKit/src/Messages/OWSDisappearingMessagesJob.m
Fixes https://github.com/signalapp/Signal-iOS/issues/3365
> Consider off/on in addition to duration when becoming consistent

- SignalServiceKit/src/Contacts/PhoneNumberUtil.m
> PhoneNumberUtil is no longer a singleton

- Signal/src/ViewControllers/ConversationView/ConversationViewItem.h
- Signal/src/ViewControllers/MediaDetailViewController.m
> Avoid crash - reply only works from ConversationVC

- Signal/Signal-Info.plist
> Add usage description for Face ID.

- Signal/src/ViewControllers/ContactsPicker.swift
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/MediaGalleryViewController.swift
- Signal/src/util/OWSWindowManager.m
- SignalMessaging/utils/OWSScreenLock.swift
> Fix: Input Toolbar appearing over media gallery, tapping voice note hides input toolbar

- Signal/src/ViewControllers/ContactShareViewHelper.swift
- Signal/src/ViewControllers/ContactViewController.swift
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/MessageDetailViewController.swift
> remove state from contact share view helper

- Signal/src/ViewControllers/ContactViewController.swift
> return navbar after tapping message/call buttons

- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/attachments/ApproveContactShareViewController.swift
> Surface contact share errors to user.

- Signal/src/ViewControllers/ContactViewController.swift
- Signal/translations/en.lproj/Localizable.strings
- SignalServiceKit/src/Messages/Interactions/OWSContact.h
- SignalServiceKit/src/Messages/Interactions/OWSContact.m
> Refine field actions in contact view.

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/AddContactShareToExistingContactViewController.swift
- Signal/src/ViewControllers/ContactShareViewHelper.swift
- Signal/src/ViewControllers/ContactViewController.swift
- Signal/src/ViewControllers/ContactsPicker.swift
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/InviteFlow.swift
- Signal/src/ViewControllers/MessageDetailViewController.swift
- Signal/src/views/ContactCell.swift
- SignalMessaging/ViewModels/ContactShareViewModel.swift
- SignalMessaging/Views/ContactsViewHelper.m
- SignalMessaging/attachments/SharingThreadPickerViewController.m
- SignalMessaging/contacts/OWSContactsManager.h
- SignalMessaging/contacts/OWSContactsManager.m
- SignalMessaging/contacts/SystemContactsFetcher.swift
- SignalMessaging/profiles/OWSProfileManager.h
- SignalMessaging/profiles/OWSProfileManager.m
- SignalServiceKit/src/Contacts/Contact.h
- SignalServiceKit/src/Contacts/Contact.m
- SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.h
- SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.m
- SignalServiceKit/src/Messages/Interactions/OWSContact.h
- SignalServiceKit/src/Messages/Interactions/OWSContact.m
**Contact Picker**
**Add To Existing**
**Create New**
> Add to existing contact

- SignalServiceKit/src/Messages/Interactions/OWSContact.h
- SignalServiceKit/src/Messages/Interactions/OWSContact.m
- SignalServiceKit/src/Messages/Interactions/TSMessage.m
> Remove contact share avatars upon message deletion

- SignalMessaging/attachments/SharingThreadPickerViewController.m
- SignalServiceKit/src/Contacts/Contact.h
- SignalServiceKit/src/Contacts/Contact.m
- SignalServiceKit/src/Messages/Interactions/OWSContact.h
- SignalServiceKit/src/Messages/Interactions/OWSContact.m
- SignalShareExtension/ShareViewController.swift
> contact sharing via sae

- Signal/src/ViewControllers/ContactViewController.swift
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/ViewModels/ContactShareViewModel.swift
- SignalMessaging/attachments/ApproveContactShareViewController.swift
- SignalMessaging/attachments/ContactFieldView.swift
- SignalMessaging/attachments/EditContactShareNameViewController.swift
- SignalMessaging/contacts/SystemContactsFetcher.swift
- SignalServiceKit/src/Messages/Interactions/OWSContact+Private.h
- SignalServiceKit/src/Messages/Interactions/OWSContact.h
- SignalServiceKit/src/Messages/Interactions/OWSContact.m
- SignalServiceKit/src/Messages/Interactions/TSMessage.m
It's just one commit off #3407.
> Charlesmchen/contact names 

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Show "share contact" flow in single presented navigation controller.

- SignalMessaging/ViewModels/ContactShareViewModel.swift
- SignalMessaging/attachments/ApproveContactShareViewController.swift
- SignalMessaging/attachments/ContactFieldView.swift
> Show avatar in contact approval view

- Signal/src/ViewControllers/ContactViewController.swift
> Always show 'add to contacts' button.

- SignalServiceKit/src/Contacts/Contact.m
> Refine contact merging.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- SignalMessaging/ViewModels/OWSQuotedReplyModel.h
- SignalMessaging/ViewModels/OWSQuotedReplyModel.m
Simply includes the display name of the contact, adding avatars is going to be bit of work.
> quote reply to contact share (no avatar)

- Signal/src/AppDelegate.m
- Signal/src/ViewControllers/HomeView/HomeViewController.m
> Don't process multiple local notifications.

- SignalServiceKit/src/Messages/OWSMessageSender.m
> Don't echo messages sent to self 1:1.

- Signal/src/ViewControllers/HomeView/HomeViewController.m
> Fix edge cases in home view.

- SignalMessaging/ViewModels/ContactShareViewModel.swift
> Use signal id as avatar color seed if possible.

- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- Signal/translations/en.lproj/Localizable.strings
- SignalServiceKit/src/Contacts/ContactsUpdater.m
- SignalServiceKit/src/Contacts/SignalRecipient.m
- SignalServiceKit/src/Messages/Interactions/TSInfoMessage.h
- SignalServiceKit/src/Messages/Interactions/TSInfoMessage.m
- SignalServiceKit/src/Messages/OWSBlockingManager.h
- SignalServiceKit/src/Messages/OWSMessageSender.m
- SignalServiceKit/src/Protocols/ContactsManagerProtocol.h
> Improve handling of unregistered users.

- Signal/src/call/PeerConnectionClient.swift
> Rework cleanup of peer connection client delegates.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Only mark messages read in conversation view if visible.

- SignalServiceKit/src/Network/API/TSNetworkManager.m
> Build & enqueue network requests async.

- Signal/src/ViewControllers/ThreadSettings/ShowGroupMembersViewController.m
- SignalMessaging/Views/ContactTableViewCell.m
- SignalMessaging/contacts/OWSContactsManager.h
- SignalMessaging/contacts/OWSContactsManager.m
> Sort group members.

- SignalServiceKit/src/Contacts/Contact.h
- SignalServiceKit/src/Contacts/Contact.m
- SignalServiceKit/src/Messages/Interactions/OWSContact.m
> Use raw text when localization fails

- SignalMessaging/attachments/ContactShareApprovalViewController.swift
> Don't send empty contact card with just avatar

- Signal/src/views/ContactCell.swift
- SignalMessaging/contacts/OWSContactsManager.m
> Contact picker uses profile pic, when available.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Don't mark messages as read if conversation view isn't 100% visible.

- SignalMessaging/attachments/SignalAttachment.swift
> Normalize image colorspace.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- SignalMessaging/Views/AvatarImageView.swift
- SignalServiceKit/src/Contacts/Threads/TSGroupThread.h
- SignalServiceKit/src/Contacts/Threads/TSGroupThread.m
> Fix "group avatar doesn't update after local change."

- CONTRIBUTING.md
PTAL @charlesmchen-signal and @michaelkirk-signal.
> Update the contribution guidelines.

- SignalMessaging/profiles/ProfileFetcherJob.swift
> Make profile gets over websocket.

- Signal/src/ViewControllers/Utils/MessageRecipientStatusUtils.swift
- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.h
- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
> Preserve legacy outgoing message state.

- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
> start migrated disappearing timers

- Signal/src/call/CallService.swift
> Fix call termination reference.

- Signal/src/call/CallService.swift
> Show missed call when call times out

- Signal/src/ViewControllers/CallViewController.swift
- SignalMessaging/utils/OWSWindowManager.m
> Apply design for call view back button.

- SignalMessaging/contacts/OWSContactsManager.m
> Limit the scope of the 'incomplete contacts fetch' fix.

- SignalMessaging/profiles/ProfileFetcherJob.swift
- SignalServiceKit/src/Messages/OWSMessageSender.m
- SignalServiceKit/src/Network/WebSockets/TSSocketManager.h
- SignalServiceKit/src/Network/WebSockets/TSSocketManager.m
> Unify the socket manager's 'can send requests' logic.

- SignalMessaging/contacts/OWSContactsManager.m
- SignalMessaging/contacts/SystemContactsFetcher.swift
> Clear the contacts cache if access to the system contacts is revoked.

- SignalMessaging/profiles/ProfileFetcherJob.swift
- SignalServiceKit/src/Account/TSAccountManager.m
- SignalServiceKit/src/Messages/OWSMessageSender.m
- SignalServiceKit/src/Network/WebSockets/TSSocketManager.h
- SignalServiceKit/src/Network/WebSockets/TSSocketManager.m
> Include response data in 'request over websocket' failures.

- SignalMessaging/ViewControllers/OWSNavigationController.m
> Suppress animations in nav bar around call window.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Conversation load perf: Load less messages initially

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
> Conversation load perf: Reduce viewWillAppear by ~5% by optimizing loadForTextDisplay

- Libraries/iRate/iRate.h
- Libraries/iRate/iRate.m
> Avoid 0xdead10cc crashes in iRate.

- Signal/src/ViewControllers/InviteFlow.swift
- Signal/translations/az_AZ.lproj/Localizable.strings
- Signal/translations/en.lproj/Localizable.strings
> Add warning before sending group message invites.

- Signal/src/ViewControllers/ContactsPicker.swift
> Fix ordering of contacts picker.

- Signal/src/call/CallService.swift
- Signal/src/call/UserInterface/CallUIAdapter.swift
> Fix more call state edge cases.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
> Handle layout of long group name labels.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Ensure conversation view is first responder before presenting another view.

- Signal/src/AppDelegate.m
- Signal/translations/en.lproj/Localizable.strings
> notify when receiving voip before first unlock

- Scripts/reverse_integration_check.py
> Add list of tags to ignore to RI check script.

- SignalServiceKit/src/Devices/OWSBlockedPhoneNumbersMessage.h
- SignalServiceKit/src/Devices/OWSBlockedPhoneNumbersMessage.m
- SignalServiceKit/src/Devices/OWSReadReceiptsForLinkedDevicesMessage.h
- SignalServiceKit/src/Devices/OWSReadReceiptsForLinkedDevicesMessage.m
- SignalServiceKit/src/Devices/OWSVerificationStateSyncMessage.h
- SignalServiceKit/src/Devices/OWSVerificationStateSyncMessage.m
- SignalServiceKit/src/Messages/DeviceSyncing/OWSOutgoingSentMessageTranscript.h
- SignalServiceKit/src/Messages/DeviceSyncing/OWSOutgoingSentMessageTranscript.m
- SignalServiceKit/src/Messages/DeviceSyncing/OWSOutgoingSyncMessage.h
- SignalServiceKit/src/Messages/DeviceSyncing/OWSOutgoingSyncMessage.m
- SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncConfigurationMessage.h
- SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncConfigurationMessage.m
- SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncContactsMessage.h
- SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncContactsMessage.m
- SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncGroupsMessage.h
- SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncGroupsMessage.m
- SignalServiceKit/src/Messages/Interactions/OWSEndSessionMessage.h
- SignalServiceKit/src/Messages/Interactions/TSErrorMessage.h
- SignalServiceKit/src/Messages/Interactions/TSErrorMessage.m
- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.h
- SignalServiceKit/src/Messages/Interactions/TSOutgoingMessage.m
- SignalServiceKit/src/Messages/OWSProfileKeyMessage.h
- SignalServiceKit/src/Messages/OWSProfileKeyMessage.m
- SignalServiceKit/src/Storage/TSRecipient.m
> Fix build warnings: mark initWithCoder as designated.

- Podfile.lock
- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/HomeView/ConversationSearchViewController.swift
- Signal/src/ViewControllers/HomeView/HomeViewController.m
- Signal/test/Models/MesssagesBubblesSizeCalculatorTest.swift
- Signal/test/util/SearcherTest.swift
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/ViewModels/ThreadViewModel.swift
- SignalMessaging/categories/String+OWS.swift
- SignalMessaging/utils/ConversationSearcher.swift
- SignalServiceKit.podspec
- SignalServiceKit/src/Storage/FullTextSearchFinder.swift
- SignalServiceKit/src/Storage/OWSPrimaryStorage.m
- SignalServiceKit/src/Storage/OWSStorage.m
This is a rough cut of both the backend and front end for full text search. Some functionality is a little rough, while some is just missing.
While you're reviewing, I'll make sure all outstanding work is cut into separate cards.
> fts search results controller

- Signal/src/ViewControllers/HomeView/ConversationSearchViewController.swift
- Signal/src/ViewControllers/HomeView/HomeViewController.m
> Open search results.

- Signal/src/ViewControllers/HomeView/ConversationSearchViewController.swift
- SignalMessaging/utils/ConversationSearcher.swift
- SignalServiceKit/src/Storage/FullTextSearchFinder.swift
> Include contacts in FTS results

- SignalShareExtension/utils/ShareAppExtensionContext.m
> Default share app context's default application state to active.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Preserve default scroll state until conversation view is presented.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.h
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/HomeView/ConversationSearchViewController.swift
- Signal/src/ViewControllers/HomeView/HomeViewController.h
- Signal/src/ViewControllers/HomeView/HomeViewController.m
- Signal/src/call/OutboundCallInitiator.swift
- Signal/src/environment/SignalApp.h
- Signal/src/environment/SignalApp.m
- SignalMessaging/utils/ConversationSearcher.swift
- SignalMessaging/utils/ThreadUtil.h
- SignalMessaging/utils/ThreadUtil.m
> Open message search results.

- SignalMessaging/ViewControllers/OWSNavigationController.m
Don't start interactive pop gesture for root VC
> Fix unresponsive interface after swipe on root VC

- Signal/src/ViewControllers/HomeView/ConversationSearchViewController.swift
- SignalMessaging/contacts/OWSContactsManager.h
- SignalMessaging/utils/ConversationSearcher.swift
> Order the search results.

- SignalMessaging/contacts/SystemContactsFetcher.swift
> Check contacts access when notified of contacts changes.

- SignalServiceKit/src/Network/WebSockets/TSSocketManager.m
> Clean up websocket logging.

- Signal/src/ViewControllers/HomeView/ConversationSearchViewController.swift
- Signal/src/ViewControllers/HomeView/HomeViewController.m
- Signal/src/ViewControllers/MediaGalleryViewController.swift
> Update search results.

- Signal/src/ViewControllers/HomeView/HomeViewController.m
> Avoid double-scrolling.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- SignalMessaging/utils/OWSWindowManager.h
> Don't mark as read when callscreen is active

- SignalServiceKit/src/Messages/OWSMessageSender.m
> Fix assert around failing sync message sends.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- SignalServiceKit/src/Storage/OWSPrimaryStorage.h
- SignalServiceKit/src/Storage/OWSPrimaryStorage.m
> update UI DB to latest before showing CVC

- SignalMessaging/contacts/SystemContactsFetcher.swift
- SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.h
- SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.m
- SignalServiceKit/src/Storage/FullTextSearchFinder.swift
> Index oversize text for search.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Shared ui db connection v. auto load more.

- SignalServiceKit/src/Storage/TSDatabaseView.m
> Tidy up type checking in database views.

- SignalServiceKit/src/Storage/OWSStorage.m
> Return unknown object from deserializer

- Signal/src/ViewControllers/HomeView/ConversationSearchViewController.swift
- Signal/src/ViewControllers/HomeView/HomeViewController.m
* Show "cancel" button while search is active.
* Dismiss keyboard if cancel button is pressed.
* Dismiss keyboard is user scrolls home view or search results content.
> Auto-dismiss search keyboard; "cancel search" button.

- Signal/src/ViewControllers/Registration/RegistrationViewController.m
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/categories/UIDevice+featureSupport.swift
> Inform iPad users upon registration

- Signal/translations/en.lproj/Localizable.strings
> Apply copy change.

- Signal/src/ViewControllers/AppSettings/AppSettingsViewController.m
- Signal/translations/en.lproj/Localizable.strings
> Improve app settings buttons.

- SignalServiceKit/src/Storage/OWSStorage.m
> Improve logging around deserialization exceptions.

- Signal/src/ViewControllers/HomeView/HomeViewController.m
> FIX: input toolbar not immediately visible when search was active

- Signal/src/ViewControllers/HomeView/HomeViewCell.m
> FIX: mute icon corrupted in homeview

- Signal/src/ViewControllers/ConversationView/Cells/ConversationViewCell.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/ConversationLayoutInfo.swift
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.h
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
- Signal/src/ViewControllers/HomeView/HomeViewCell.m
> Tweak 'group sender' avatars.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageTextView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageTextView.m
We might not want to do that; we'll need to do a perf analysis of the cost, but we should do that after other tweaking is complete.
> Compact layout / widow reduction.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.h
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
- Signal/src/ViewControllers/HomeView/HomeViewCell.m
- SignalServiceKit/src/Network/WebSockets/TSSocketManager.m
> Tweak intra-cell spacing.

- Signal/src/ViewControllers/ConversationView/Cells/OWSBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
> Fix corner rounding.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.h
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
* Tweaks "sender names" in group conversations.
* Tweaks footer layout.
> Tweak sender names.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- SignalMessaging/categories/UIView+OWS.h
- SignalMessaging/categories/UIView+OWS.m
Tweaked to add two shadows under body media.  If perf needs improvement, this is something we could eliminate.
> Tweak message cells.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSUnreadIndicatorCell.m
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
> Tweak break spacing.

- Signal/src/ViewControllers/ConversationView/Cells/OWSAudioMessageView.m
> Fix audio message layout.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
> Fix bubble strokes.

- Signal.xcodeproj/project.pbxproj
- Signal/src/UserInterface/OWSLayerView.swift
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.m
- Signal/src/ViewControllers/CropScaleImageViewController.swift
> Tweak media view gradients.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
> Ensure body media size.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/views/AttachmentPointerView.swift
- Signal/src/views/OWSProgressView.h
- Signal/src/views/OWSProgressView.m
- SignalMessaging/Views/OWSLayerView.swift
> Tweak attachment download view.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.m
> Animate sending icon.

- Signal/src/ViewControllers/ConversationView/Cells/OWSGenericAttachmentView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSGenericAttachmentView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
> Tweak generic attachment view widths.

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/ColorPickerViewController.swift
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m
- Signal/src/ViewControllers/ConversationView/ConversationHeaderView.swift
- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.h
- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- Signal/src/ViewControllers/ThreadSettings/OWSConversationSettingsViewController.m
- Signal/src/ViewControllers/ThreadSettings/OWSConversationSettingsViewDelegate.h
- Signal/src/views/QuotedReplyPreview.swift
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/Views/AvatarImageView.swift
- SignalMessaging/Views/ContactCellView.m
- SignalMessaging/categories/UIColor+OWS.h
- SignalMessaging/categories/UIColor+OWS.m
- SignalMessaging/utils/ConversationStyle.swift
- SignalMessaging/utils/OWSAvatarBuilder.m
- SignalMessaging/utils/OWSContactAvatarBuilder.h
- SignalMessaging/utils/OWSContactAvatarBuilder.m
- SignalServiceKit/src/Contacts/TSThread.h
- SignalServiceKit/src/Contacts/TSThread.m
> tweak picker

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.m
> Tweak message contents.

- Signal/src/UserInterface/SlideOffAnimatedTransition.swift
- Signal/src/ViewControllers/AppSettings/AppSettingsViewController.m
- Signal/src/ViewControllers/CallViewController.swift
- Signal/src/ViewControllers/ContactViewController.swift
- Signal/src/ViewControllers/ConversationView/Cells/AttachmentUploadView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSContactShareView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.m
- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/HomeView/HomeViewController.m
- Signal/src/ViewControllers/MessageDetailViewController.swift
- Signal/src/ViewControllers/OWS2FAReminderViewController.swift
- Signal/src/ViewControllers/Utils/MessageRecipientStatusUtils.swift
- Signal/src/util/DateUtil.h
- Signal/src/util/DateUtil.m
- Signal/src/util/MainAppContext.m
- Signal/src/views/ReminderView.swift
- SignalMessaging/categories/NSAttributedString+OWS.h
- SignalMessaging/categories/NSAttributedString+OWS.m
- SignalMessaging/categories/NSString+OWS.h
- SignalMessaging/categories/NSString+OWS.m
- SignalMessaging/categories/UIView+OWS.h
- SignalMessaging/categories/UIView+OWS.m
- SignalMessaging/categories/UIViewController+OWS.m
- SignalMessaging/contacts/OWSContactsManager.m
- SignalMessaging/contacts/SelectRecipientViewController.m
- SignalMessaging/utils/ConversationStyle.swift
- SignalServiceKit/src/Util/AppContext.h
- SignalShareExtension/utils/ShareAppExtensionContext.m
> Rework isRTL.

- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m
- SignalMessaging/categories/UIView+OWS.h
- SignalMessaging/categories/UIView+OWS.m
> Fix quoted reply margin.

- Signal/src/ViewControllers/MediaGalleryViewController.swift
- Signal/src/ViewControllers/MessageDetailViewController.swift
> misc cleanup

- Signal/src/ViewControllers/ConversationView/ConversationInputTextView.h
- Signal/src/ViewControllers/ConversationView/ConversationInputTextView.m
- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.h
- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- SignalMessaging/attachments/AttachmentApprovalViewController.swift
> touch up compose bar

- SignalServiceKit/src/Util/NSString+SSK.m
> bump limit to allow more legit strings through

- Signal/src/ViewControllers/ThreadSettings/OWSConversationSettingsViewController.m
> smaller swatch icon

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/ConversationView/Cells/OWSContactShareButtonsView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSContactShareButtonsView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSContactShareView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSContactShareView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- SignalServiceKit/src/Messages/Interactions/OWSContact.m
> Rework contact share buttons.

- Signal/src/ViewControllers/HomeView/HomeViewController.m
> Fixes iOS10 intermittently can't see inbox

- SignalServiceKit/src/Messages/OWSMessageSender.m
> Use sending queue in websocket send failover to REST.

- SignalMessaging/contacts/OWSContactsManager.m
> Tweak styling of phone number + profile name.

- Signal/src/ViewControllers/MessageDetailViewController.swift
- SignalMessaging/Views/ContactTableViewCell.m
> Fix contact cell layout.

- Signal/src/ViewControllers/ProfileViewController.m
- Signal/src/ViewControllers/Registration/CodeVerificationViewController.m
- Signal/src/views/PinEntryView.m
> Use dismissable text views where cramped on shorter devices

- Signal/src/ViewControllers/MediaGalleryViewController.swift
I previously fixed this for presentation, but missed it for the dismiss
> match media corners on dismiss

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Only collapse footers within a cluster (from the same author)

- Signal/src/AppDelegate.m
- Signal/src/network/PushManager.h
- Signal/src/network/PushManager.m
> Fix: second reply from lockscreen doesn't send

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Fix rounding after date

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- SignalMessaging/utils/ConversationStyle.swift
> Tweak sender avatar sizes.

- Signal/src/ViewControllers/ThreadSettings/OWSConversationSettingsViewController.m
> Tweak colors flag.

- Signal/src/ViewControllers/ConversationView/Cells/OWSAudioMessageView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSAudioMessageView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSCallMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSContactShareButtonsView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSContactShareView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSContactShareView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSGenericAttachmentView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSGenericAttachmentView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m
- Signal/src/views/AttachmentPointerView.swift
- SignalMessaging/categories/UIColor+OWS.h
- SignalMessaging/categories/UIColor+OWS.m
- SignalMessaging/utils/ConversationStyle.swift
There's a few open questions here, mostly around quoted replies.  I'll be working those out with Myles soon.
> Retweak colors

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSUnreadIndicatorCell.m
- SignalMessaging/utils/ConversationStyle.swift
> Retweak date and unread messages breaks.

- Signal/src/ViewControllers/ConversationView/Cells/AttachmentUploadView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSAudioMessageView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSGenericAttachmentView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSUnreadIndicatorCell.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- Signal/src/ViewControllers/Registration/RegistrationViewController.m
- Signal/src/util/DateUtil.m
- SignalMessaging/contacts/SelectRecipientViewController.m
- SignalMessaging/utils/ConversationStyle.swift
- SignalMessaging/utils/OWSContactAvatarBuilder.m
Moving a bit closer to the spec
> fix color for outgoing failed

- Signal/src/ViewControllers/HomeView/HomeViewCell.m
- SignalMessaging/categories/UIColor+OWS.h
- SignalMessaging/categories/UIColor+OWS.m
> tweak selected color for homeview cells

- Signal/Signal-Info.plist
- Signal/src/ViewControllers/CallViewController.swift
- Signal/src/util/MainAppContext.m
- SignalMessaging/ViewControllers/OWSNavigationController.m
- SignalMessaging/utils/UIUtil.m
- SignalServiceKit/src/Util/AppContext.h
- SignalShareExtension/utils/ShareAppExtensionContext.m
Transition to VC controlled status bar style.
> Fix white status bar for call screen

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageHeaderView.m
> Tweak unread indicator + date.

- Scripts/precommit.py
- Signal/src/ViewControllers/ConversationView/Cells/ConversationViewCell.h
> Dedupe forward class declarations.

- Signal/src/ViewControllers/ConversationView/Cells/OWSGenericAttachmentView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSSystemMessageCell.m
- Signal/src/ViewControllers/HomeView/HomeViewCell.m
- Signal/src/views/AttachmentPointerView.swift
- SignalMessaging/utils/ConversationStyle.swift
> More design tweaks.

- Signal/src/ViewControllers/Registration/CodeVerificationViewController.m
- Signal/src/ViewControllers/Registration/RegistrationViewController.m
> Tweak status bar colors in registration flow.

- Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m
- SignalMessaging/Views/OWSNavigationBar.swift
> Enhance navbar blur, match input toolbar blur

- SignalServiceKit/src/TSConstants.h
> Add feature flag for contact discovery service.

- SignalMessaging/contacts/SelectThreadViewController.m
> Fix oversize accessory view.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> ScrollToBottom accounts for top inset

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageHeaderView.m
- SignalMessaging/utils/ConversationStyle.swift
Previous spacing was based on applying the "full width" gutter spacing twice.
> decrease header spacing from 32->28.

- Signal/src/ViewControllers/CallViewController.swift
- SignalMessaging/ViewControllers/OWSViewController.m
fixes black status bar after leaving and returning to app
> update status bar after screenprotection shows

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
> Remove media thumbnail shadows.

- Signal/src/ViewControllers/HomeView/HomeViewController.m
- Signal/src/ViewControllers/NewContactThreadViewController.m
> Fix compose picker content scrolls behind navbar

- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m
> per design: tweak quote corner radius

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/HomeView/HomeViewCell.m
- Signal/src/ViewControllers/HomeView/MessageStatusView.swift
Offsetting a baseline alignment required an unfortunate amount of code (there may be a better way).
> per design: MessageStatus 1pt below baseline

- SignalMessaging/Views/OWSNavigationBar.swift
- SignalMessaging/utils/OWSWindowManager.h
- SignalMessaging/utils/OWSWindowManager.m
> fix bottom blur artifact after selecting from compose

- Signal/src/ViewControllers/ConversationView/Cells/OWSSystemMessageCell.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSSystemMessageCell.m
I considered extracting this from OWSMessageCell and putting it into
ConversationCell, but that would be a pretty large change.
> Add header view to info messages.

- SignalMessaging/ViewControllers/OWSTableViewController.m
- SignalMessaging/categories/UIView+OWS.h
- SignalMessaging/categories/UIView+OWS.m
A slightly narrower version of #3696.
> Fix content insets.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
> Set sender names apart.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSSystemMessageCell.m
> Ignore gestures in date breaks and unread indicators.

- Signal/src/ViewControllers/ConversationView/Cells/OWSContactOffersCell.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageFooterView.m
> Fix message footer alignment.

- Signal/src/ViewControllers/AppSettings/OWSLinkDeviceViewController.m
- SignalServiceKit/src/Network/WebSockets/TSSocketManager.h
- SignalServiceKit/src/Network/WebSockets/TSSocketManager.m
> Cycle the socket after linking a new device.

- Signal/src/ViewControllers/MenuActionsViewController.swift
> faster message actions presentation

- SignalServiceKit/src/Contacts/TSThread.m
- SignalServiceKit/src/Storage/OWSStorage.m
> Fix NPE using mock for unknown database objects.

- SignalServiceKit/src/Contacts/ContactsUpdater.m
- SignalServiceKit/src/Contacts/OWSContactDiscoveryOperation.swift
The first commit is the change in behavior.
The second separate commit is just re-ordering the classes to reflect what I think is now more appropriate.
> Unbatch requests

- Signal/src/views/RemoteVideoView.m
> Fix letterboxed video on M68

- SignalServiceKit/src/Network/API/Requests/TSRequest.m
> Fixup CDS auth properties.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Fix lazy collapse of message cell footers.

- Signal/src/util/MainAppContext.m
- SignalServiceKit/src/Messages/OWSIncompleteCallsJob.m
- SignalServiceKit/src/Util/AppContext.h
- SignalShareExtension/utils/ShareAppExtensionContext.m
> Ignore new calls in the incomplete calls job.

- Signal/SignalUBSan.supp
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
Fixes build failure on Xcode10b5
> Add missing header file

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
> Fix crash during CollectionView thrash

- Signal/src/Models/MessageActions.swift
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.h
> Fix "save non-media attachment" crash.

- Signal/Signal-Info.plist
- Signal/src/util/OWSOrphanDataCleaner.m
- SignalServiceKit/src/Util/AppVersion.h
- SignalServiceKit/src/Util/AppVersion.m
- SignalShareExtension/Info.plist
> Converge appLaunchTime.

- Scripts/ProtoWrappers.py
- Signal/src/Generated/WebRTCProto.swift
- Signal/src/call/CallService.swift
- SignalServiceKit/src/Messages/DeviceSyncing/OWSIncomingSentMessageTranscript.m
- SignalServiceKit/src/Messages/Interactions/OWSContact.m
- SignalServiceKit/src/Messages/Interactions/TSQuotedMessage.m
- SignalServiceKit/src/Messages/OWSMessageHandler.m
- SignalServiceKit/src/Messages/OWSMessageManager.m
- SignalServiceKit/src/Protos/Generated/SSKProto.swift
- SignalServiceKit/src/Protos/Generated/WebSocketProto.swift
> Remove 'has' accessors from proto wrappers.

- SignalMessaging/ViewControllers/OWSTableViewController.m
AFAIK this only affects debug UI.
> Configure default cells.

- Signal/src/ViewControllers/ContactsPicker.swift
- Signal/src/ViewControllers/GifPicker/GifPickerViewController.swift
- Signal/src/ViewControllers/HomeView/HomeViewController.m
- Signal/src/ViewControllers/NewContactThreadViewController.m
- SignalMessaging/ViewControllers/SelectThreadViewController.m
- SignalMessaging/categories/Theme.h
- SignalMessaging/categories/Theme.m
> Theme search bars.

- SignalMessaging/utils/ConversationStyle.swift
> Remove "sending" color for outgoing messages.

- Signal/src/ViewControllers/ProfileViewController.m
- SignalMessaging/ViewControllers/OWSTableViewController.m
- SignalMessaging/Views/OWSNavigationBar.swift
- SignalMessaging/categories/Theme.h
- SignalMessaging/categories/Theme.m
> Tweak theme

- SignalServiceKit/src/Account/TSAccountManager.m
> Fix nominal race in "is registered" state.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Improve logging of conversation view exceptions.

- Signal/src/ViewControllers/MessageDetailViewController.swift
> Apply 'insets fix' correctly in message details view.

- Signal/src/ViewControllers/HomeView/HomeViewController.m
> Hide home view search by default.

- Signal/src/ViewControllers/MessageDetailViewController.swift
> Tap to copy sender timestamp to clipboard.

- Signal/src/util/DateUtil.m
> Improve message timestamp formatting.

- SignalMessaging/ViewControllers/ViewControllerUtils.m
> Fix 'can't delete formatting in phone number' issue.

- SignalServiceKit/src/Contacts/OWSContactDiscoveryOperation.swift
> Disable CDS.

- Signal/src/ViewControllers/MediaTileViewController.swift
> media  tile toolbar respects theme by using UIAppearance defaults

- SignalMessaging/utils/ConversationStyle.swift
> Theme quoted replies.

- Scripts/ProtoWrappers.py
- Signal/src/Generated/WebRTCProto.swift
- SignalServiceKit/src/Protos/Generated/FingerprintProto.swift
- SignalServiceKit/src/Protos/Generated/ProvisioningProto.swift
- SignalServiceKit/src/Protos/Generated/SSKProto.swift
- SignalServiceKit/src/Protos/Generated/SignalIOSProto.swift
- SignalServiceKit/src/Protos/Generated/SignalService.pb.swift
- SignalServiceKit/src/Protos/Generated/WebSocketProto.swift
- SignalServiceKit/src/Protos/Generated/WebSocketResources.pb.swift
> restrict debug methods

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Elaborate logging around 'perform updates' crash.

- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
- Signal/src/ViewControllers/GifPicker/GifPickerCell.swift
- SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.m
- SignalServiceKit/src/Util/NSData+Image.m
> Update logging and asserts in hotfix changes.

- Signal/src/call/CallService.swift
- Signal/src/call/PeerConnectionClient.swift
- Signal/test/call/PeerConnectionClientTest.swift
- Signal/test/util/OWSScrubbingLogFormatterTest.m
- SignalMessaging/utils/OWSScrubbingLogFormatter.m
- SignalServiceKit/src/Contacts/PhoneNumberUtil.m
> Enable sw decoders

- Signal/src/call/CallService.swift
- Signal/src/environment/PushRegistrationManager.swift
- SignalMessaging/profiles/ProfileFetcherJob.swift
A proposal.  IMO these usages weren't adding anything.  WDYT?
> Remove more usage of logTag.

- SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.m
> fix group avatar updates and quote generation

- Scripts/precommit.py
> keyword checks

- Signal/src/ViewControllers/ConversationView/Cells/OWSGenericAttachmentView.m
- Signal/src/ViewControllers/ConversationView/ConversationInputTextView.m
- Signal/src/ViewControllers/HomeView/HomeViewCell.m
- Signal/src/ViewControllers/MenuActionsViewController.swift
- SignalMessaging/ViewControllers/AttachmentApprovalViewController.swift
- SignalMessaging/categories/Theme.h
- SignalMessaging/categories/Theme.m
- SignalMessaging/categories/UIColor+OWS.h
- SignalMessaging/categories/UIColor+OWS.m
- SignalMessaging/utils/ConversationStyle.swift
Note that hairlines are now more subtle in "light theme".
> New grayscale palette.

- SignalServiceKit/src/Network/API/TSNetworkManager.m
I periodically use curl to debug service requests.  It's a bit time-consuming to construct the curl analogue for our requests.  This will log the curl command for failed requests in debug builds.
We don't have to merge this; I can just keep it in a branch.
> Log curl command for failed requests in debug builds.

- Signal/src/AppDelegate.m
- SignalMessaging/ViewControllers/OWSTableViewController.h
- SignalMessaging/environment/AppSetup.m
- SignalServiceKit/src/Contacts/Threads/TSContactThread.h
- SignalServiceKit/src/Contacts/Threads/TSContactThread.m
- SignalServiceKit/src/Messages/OWSBlockingManager.h
- SignalServiceKit/src/Messages/OWSBlockingManager.m
- SignalServiceKit/src/Messages/OWSIdentityManager.h
- SignalServiceKit/src/Messages/OWSIdentityManager.m
- SignalServiceKit/src/Messages/OWSMessageManager.h
- SignalServiceKit/src/Messages/OWSMessageManager.m
- SignalServiceKit/src/Messages/OWSMessageSender.h
- SignalServiceKit/src/Messages/OWSMessageSender.m
- SignalServiceKit/src/SSKEnvironment.h
- SignalServiceKit/src/SSKEnvironment.m
- SignalServiceKit/src/Tests/MockSSKEnvironment.h
- SignalServiceKit/src/Tests/MockSSKEnvironment.m
Pretty straightforward.  This enables the next PR which gets the SSK tests building and running (but not passing).
> Move more singletons to SSKEnvironment.

- Signal/src/ViewControllers/ConversationView/Cells/OWSContactOffersCell.m
Look at the "share profile..." button in the screenshots below.
> Fix contact offer button margins.

- Signal/src/ViewControllers/HomeView/HomeViewCell.m
> Move unread badge on home view; propose shadow.

- Signal/src/ViewControllers/HomeView/HomeViewCell.m
> Rework layout of message status in home view.

- SignalServiceKit/src/Tests/MockSSKEnvironment.m
> fix release compile

- SignalMessaging/utils/ConversationStyle.swift
> Update text colors.

- Signal/src/ViewControllers/ConversationView/Cells/OWSBubbleShapeView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSBubbleShapeView.m
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
> Add inner shadows to media thumbnails.

- Signal/src/ViewControllers/HomeView/HomeViewController.m
> Use local avatar as app settings button.

- Signal/src/ViewControllers/AppSettings/AboutTableViewController.m
> Add crash gesture to about view.

- Signal/src/ViewControllers/CallViewController.swift
- Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/ViewControllers/AttachmentApprovalViewController.swift
* Made our Title Case usage a little more consistent.
* Standardized on the ellipses special character.
* Rephrased a few buttons and descriptions.
> String cleanup

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/ColorPickerViewController.swift
- Signal/src/ViewControllers/ThreadSettings/OWSConversationSettingsViewController.m
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/ViewControllers/SheetViewController.swift
- SignalMessaging/appearance/OWSConversationColor.h
- SignalMessaging/appearance/OWSConversationColor.m
- SignalMessaging/categories/Collection+OWS.swift
- SignalMessaging/categories/UIColor+OWS.m
Note this does not include the message bubble preview.
> color picker

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- SignalServiceKit/src/Storage/TSYapDatabaseObject.h
- SignalServiceKit/src/Storage/TSYapDatabaseObject.m
> Fix: group color change doesn't immediately apply

- Signal/src/ViewControllers/HomeView/HomeViewController.m
> work around multiple review's appearing

- SignalMessaging/Views/ContactCellView.m
- SignalMessaging/utils/OWSContactAvatarBuilder.m
- SignalServiceKit/src/Contacts/TSThread.h
- SignalServiceKit/src/Contacts/TSThread.m
- SignalServiceKit/src/Contacts/Threads/TSContactThread.m
- SignalServiceKit/src/Contacts/Threads/TSGroupThread.m
- SignalServiceKit/src/Messages/DeviceSyncing/OWSSyncContactsMessage.m
> Apply new colors to new conversation

- Signal/src/ViewControllers/HomeView/HomeViewController.m
> Fix settings button glitch on iOS 10.

- Signal/src/ViewControllers/HomeView/HomeViewController.m
fixes https://github.com/signalapp/Signal-iOS/issues/3943
PTAL @charlesmchen-signal
> fix archive nav stack

- Signal/Signal-Info.plist
- SignalMessaging/categories/UIColor+OWS.m
- SignalMessaging/utils/OWSGroupAvatarBuilder.m
- SignalShareExtension/Info.plist
> feature flag for group avatar color

- SignalServiceKit/src/Messages/OWSMessageManager.m
- SignalServiceKit/src/Messages/UD/OWSRequestMaker.swift
Eventually I'd like to move this dispatch into the profile fetch job.
> Request profile fetches on main thread.

- Signal/src/AppDelegate.m
- Signal/src/ViewControllers/LoadingViewController.swift
- Signal/src/ViewControllers/MediaGalleryViewController.swift
- Signal/src/ViewControllers/MediaPageViewController.swift
- Signal/src/ViewControllers/MediaTileViewController.swift
- Signal/src/ViewControllers/MenuActionsViewController.swift
- Signal/translations/en.lproj/Localizable.strings
- SignalMessaging/ViewControllers/OWSNavigationController.m
- SignalMessaging/ViewControllers/OWSViewController.m
- SignalMessaging/ViewControllers/ReturnToCallViewController.swift
- SignalMessaging/ViewControllers/ScreenLockViewController.m
- SignalMessaging/Views/OWSNavigationBar.swift
- SignalMessaging/categories/UIDevice+featureSupport.swift
- SignalMessaging/utils/OWSWindowManager.h
- SignalMessaging/utils/OWSWindowManager.m
Part of https://github.com/signalapp/Signal-iOS/issues/937
> Landscape mode for media

- Signal/src/ViewControllers/AppSettings/PrivacySettingsTableViewController.m
- Signal/translations/en.lproj/Localizable.strings
- SignalServiceKit/src/Util/TypingIndicators.swift
> Add typing indicators setting.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/MediaGalleryViewController.swift
- Signal/src/ViewControllers/MessageDetailViewController.swift
- Signal/src/ViewControllers/ThreadSettings/OWSConversationSettingsViewController.m
- SignalMessaging/ViewControllers/OWSNavigationController.h
- SignalMessaging/ViewControllers/OWSNavigationController.m
Came across this while testing the landscape stuff, but actually unrelated.
> fix media-gallery doesn't respect call banner

- SignalMessaging/profiles/OWSProfileManager.m
> Inform linked devices about profile changes.

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/ExperienceUpgradesPageViewController.swift
- Signal/src/environment/ExperienceUpgrades/ExperienceUpgradeFinder.swift
- Signal/translations/en.lproj/Localizable.strings
> typing indicator upgrade screen

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/ConversationView/Cells/OWSBubbleView.h
- Signal/src/ViewControllers/ConversationView/Cells/OWSBubbleView.m
- Signal/src/ViewControllers/ConversationView/Cells/TypingIndicatorCell.swift
- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
- Signal/src/ViewControllers/ConversationView/ConversationViewModel.m
- Signal/src/ViewControllers/ConversationView/TypingIndicatorInteraction.swift
- Signal/src/ViewControllers/HomeView/HomeViewCell.m
- Signal/src/views/TypingIndicatorView.swift
- SignalMessaging/categories/UIView+OWS.h
- SignalServiceKit/src/Contacts/TSThread.h
- SignalServiceKit/src/Contacts/TSThread.m
- SignalServiceKit/src/Messages/Interactions/TSInteraction.h
- SignalServiceKit/src/Messages/Interactions/TSInteraction.m
- SignalServiceKit/src/Util/TypingIndicators.swift
> Charlesmchen/typing indicators5 

- Signal/Signal-Info.plist
`PlistBuddy` wants this ordering.
> Update info plist to reflect PlistBuddy ordering.

- SignalServiceKit/src/Contacts/SignalRecipient.m
- SignalServiceKit/src/Storage/TSYapDatabaseObject.h
- SignalServiceKit/src/Storage/TSYapDatabaseObject.m
> Fix failed reloads in SignalRecipient.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
- Signal/src/ViewControllers/ConversationView/ConversationViewModel.h
- Signal/src/ViewControllers/ConversationView/ConversationViewModel.m
> Fix race in CVM startup.

- Signal/src/ViewControllers/ConversationView/Cells/TypingIndicatorCell.swift
- SignalServiceKit/src/Messages/OWSMessageManager.m
Two bugs found in the bug bash.
> Fix a couple small bugs in the typing indicators.

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/ColorPickerViewController.swift
- Signal/src/ViewControllers/ConversationView/Cells/MediaAlbumCellView.swift
- Signal/src/ViewControllers/ConversationView/Cells/MediaAlbumGalleryCellView.swift
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.h
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
- Signal/src/ViewControllers/DebugUI/DebugUIMessages.m
- SignalServiceKit/src/Messages/Interactions/TSMessage.h
- SignalServiceKit/src/Messages/Interactions/TSMessage.m
> Rename to media album.

- Signal/src/ViewControllers/ConversationView/ConversationViewController.m
> Reduce typing indicators.

- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
> Remove stroke on album items.

- SignalServiceKit/src/Util/TypingIndicators.swift
> Tweak timing of typing indicators.

- Signal/src/ViewControllers/AppSettings/PrivacySettingsTableViewController.m
- Signal/translations/en.lproj/Localizable.strings
> Add footer to 'typing indicators' setting.

- Signal/src/ViewControllers/ColorPickerViewController.swift
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.h
- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
- SignalServiceKit/src/Messages/Interactions/TSMessage.m
>  Render single media as albums.

- SignalServiceKit/src/Messages/OWSOutgoingReceiptManager.m
> Discard receipts for unregistered users.

- Signal/src/Jobs/MessageFetcherJob.swift
* iDevice A, iOS X.Y.Z
* iDevice B, iOS Z.Y
> Modify MessageFetcherJob to handle incoming UD messages.

- SignalServiceKit/src/Util/AppVersion.m
> Prevent long version strings from being scrubbed in the logs.

- Signal/src/ViewControllers/ConversationView/Cells/ConversationMediaView.swift
- Signal/src/ViewControllers/ConversationView/Cells/MediaAlbumCellView.swift
- Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m
- Signal/src/ViewControllers/MediaGalleryViewController.swift
- SignalMessaging/categories/UIView+OWS.h
> Tap on album item.

- SignalMessaging/environment/migrations/OWS113MultiAttachmentMediaMessages.swift
- SignalServiceKit/src/Messages/Attachments/TSAttachment.m
> Fix missing albumMessageId.

- Signal/src/ViewControllers/ConversationView/Cells/ConversationMediaView.swift
- Signal/src/ViewControllers/ConversationView/ConversationInputTextView.h
- Signal/src/ViewControllers/ConversationView/TypingIndicatorInteraction.swift
- Signal/src/call/OutboundCallInitiator.swift
- Signal/src/call/PeerConnectionClient.swift
- Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
- Signal/src/call/UserInterface/CallUIAdapter.swift
- SignalMessaging/profiles/OWSProfileManager.m
- SignalServiceKit/src/Storage/TSYapDatabaseObject.h
- SignalServiceKit/src/Util/MessageSender+Promise.swift
- SignalShareExtension/ShareViewController.swift
> fix some compiler warnings

- SignalMessaging/profiles/OWSProfileManager.m
> fix overzealous profile key rotation

- Signal.xcodeproj/xcshareddata/xcschemes/Signal.xcscheme
- Signal/src/ViewControllers/ConversationView/Cells/ConversationMediaView.swift
> Fix glitches in conversation media view.

- SignalServiceKit/src/Messages/UD/OWSRequestMaker.swift
- SignalServiceKit/src/Network/WebSockets/OWSWebSocket.h
- SignalServiceKit/src/Network/WebSockets/OWSWebSocket.m
- SignalServiceKit/src/Network/WebSockets/TSSocketManager.h
- SignalServiceKit/src/Network/WebSockets/TSSocketManager.m
> Remove UD websocket.

- Signal.xcodeproj/project.pbxproj
- Signal/src/ViewControllers/MediaGalleryViewController.swift
- Signal/src/ViewControllers/MediaPageViewController.swift
- Signal/src/ViewControllers/MediaTileViewController.swift
- Signal/src/views/CaptionView.swift
- Signal/src/views/GalleryRailView.swift
- SignalMessaging/ViewControllers/OWSNavigationController.m
- SignalMessaging/Views/OWSNavigationBar.swift
- SignalMessaging/appearance/Theme.h
- SignalMessaging/appearance/Theme.m
- SignalMessaging/categories/UIColor+OWS.h
- SignalMessaging/categories/UIColor+OWS.m
PTAL @charlesmchen-signal 
**no caption, no album**
**short caption, in an album**
**no caption, in an album**
**long caption, no album**
> Gallery pager style changes

- Signal/src/ViewControllers/MediaGalleryViewController.swift
- Signal/src/ViewControllers/MediaPageViewController.swift
1. I broke the buttons when I added the rail
2. We need to update the rail when an item is deleted
PTAL @charlesmchen-signal
> fix delete/share from pager view

- SignalServiceKit/src/Account/TSAccountManager.m
> Fix crash around account attributes update when unregistered.

- SignalMessaging/Views/OWSNavigationBar.swift
PTAL @charlesmchen-signal 
fixes #4048
> avoid crash on iOS9/10

- SignalServiceKit/src/Devices/OWSRecordTranscriptJob.m
> only process attachments if they exist

- Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
> Ensure quoted replies with attachments are handled properly.
