signalapp/Signal-iOS

Signal/Signal-Info.plist, Signal/src/AppDelegate.m, Signal/src/Storyboard/Storyboard.storyboard, Signal/src/view controllers/CountryCodeViewController.m, Signal/src/view controllers/RegistrationViewController.h, Signal/src/view controllers/RegistrationViewController.m
fixed:
Status bar should be "Light" with white text
Keypad should be "Light" keypad.
Keypad should leave 36 points (i think) below the send code button [_1.0d] when pushing content up
Country Name ("United States") should reflect changes from selection
Tapping Country Code ("+1") should also open selector
Format input for north american numbers if you want to be stupid and make me happy => (xxx) xxx-xxxx
=>  1.0 constraints code

Signal/src/contact/Contact.h, Signal/src/contact/Contact.m, Signal/src/view controllers/MessageComposeTableViewController.m
When composing a new message, you can search through your contacts by searching by your contact's name or by their phone number(s). Since phone numbers are stored in E164, we can strip the search text of illegal characters like parentheses and spaces, and then see if the search text is "contained" in the E164 formatted phone numbers of their contacts.
=> search by contact's name or number

Signal/src/util/PhoneNumberUtil.m, Signal/src/view controllers/MessageComposeTableViewController.m
Changes made:
- updated search bar placeholder text to say "search by name or number" instead of just "search"
- alert view shows up before sending normal SMS, so a user has to confirm they want to send a normal SMS outside of signal and just through the default iMessage
- PhoneNumberUtil used to sanitize input when searching by contact number, so the same results will be displayed for "1.234.555.6789" vs "1-234-555-6789", etc
- formatted user input displayed in blue box when searching for a number using a method in PhoneNumber, so searching for "1.234.555.6789" will display as "Send SMS to: +1 234-555-6789" underneath the search bar
Important notes:
The device I have to test on is Jack's iPod touch, which doesn't support SMS. The bug where you can't cancel out of iMessage likely still …
=> Polishing up texting unknown numbers via regular SMS

Signal/src/view controllers/MessageComposeTableViewController.m
after sending the SMS successfully, the "new message" view controller is dismissed
navigation bar and status bar should have colors changed to the iOS 7 blue and white, respectively
=> polishing SMS invite

Signal/src/view controllers/MessagesViewController.m, Signal/src/view controllers/TSVideoAttachmentAdapter.h, Signal/src/view controllers/TSVideoAttachmentAdapter.m
Earlier I tried putting in the duration of each audio message, but found this was non-trivial. Even though that's difficult, I realized it's pretty easy to let the user see how much time is left on each audio message even if they can't see how long the message is before playing it.
=> can see leftover duration of audio messages

Signal/src/view controllers/RegistrationViewController.m
Currently when you fail to register, which I seem to be doing ATM, the spinner doesn't stop spinning. Also signed the contributor agreement.
=> Stop the spinner when registration fails on a RegistrationVC

Podfile, Podfile.lock, Signal/src/AppDelegate.m
* iphone 6 device
Fixup of https://github.com/WhisperSystems/Signal-iOS/commit/199ce4926566d59f6733e996d804572bb98da748
Else we just see a black screen instead of the signal branding when switching screens.
Also gave the window a solid background color in case, for some reason,
the view controller can't be instantiated, because an opaque window doesn't do any good if its "clear color".
=> After removing launch image, we need to update screen security

.travis.yml
Usually, a successful pod install takes 15 minutes on travis. But often enough Travis times out at 20 mins, failing the build.
```
The command "travis_wait pod install" failed and exited with 137 during.
Your build has been stopped.
```
e.g. https://travis-ci.org/WhisperSystems/Signal-iOS/builds/122349608
=> bump up travis timeout for pod install

Signal/src/view controllers/MessageComposeTableViewController.m
All UI updates must happen on the main thread.
This will crash if it happens off main thread (as it intermittently does for me locally).
=> show alert must happen in main thread

Signal/src/view controllers/MessagesViewController.m
Fixes problem where attaching photo from camera results in uploading a 0 length attachment. Which shows this spinner forever:
When the progress bubble is tapped (by sender or receiver), it results in a crash.
Looks like this came about with the animated GIF handling. We'll only
go down the byte-comparison-mime-type-detecting code path for attaching
existing photos, since it only exists for animated GIFs.
The [ALAssetsLibrary](https://developer.apple.com/library/ios/documentation/AssetsLibrary/Reference/ALAssetsLibrary_Class) is only for interacting with pre-existing saved assets, not for images newly captured in the image picker.
This will also revert to properly compressing our image attachements, so
long as they are taken from the camera.
Maybe fixes #1037, waiting to hear back if that …
=> Fix ability to attach photos from camera

Signal/src/view controllers/MessagesViewController.m
Since we're now re-using the message controller across threads, we have
to reset some elements to their initial state when switching threads.
Missed this one.
Fixes: #1150
// FREEBIE
=> reset "Load Earlier Messages" when switching threads

Podfile
Following security advisory
(https://www.openssl.org/news/secadv/20160503.txt), OpenSSL removed
sources of previous version.
//FREEBIE
=> OpenSSL dependency update.

Podfile.lock, Signal/src/view controllers/MessagesViewController.m
Before (this was introduced since last release, so you won't see it in app store version):
After:
Before (this was introduced since last release, so you won't see it in app store version):
Judged to be too jarring for a part of the interface which shouldn't be attention grabbing.
After:
// FREEBIE
=> [UI] smaller group action menu icon, revert edit divider to neutral color

Signal/Signal-Info.plist, Signal/src/view controllers/MessageComposeTableViewController.m
FIXES: #1182 (unable unable to send invite via sms)
Could not present the sms invite alert controller because we were already presenting the UISearchController.
//FREEBIE
=> Fix unable to send invite via sms

Signal/Signal-Info.plist, Signal/src/view controllers/MessageComposeTableViewController.m
Fix SMS Invite edge cases
- Fix SMS invite on empty inbox. This was broken with https://github.com/WhisperSystems/Signal-iOS/commit/da6597118ae8336aab0ce546fe431d8338013577
- Fix SMS invite when device *can* send SMS but is not iPhone
- Don't allow SMS invite when device *is* iPhone but can't send SMS (otherwise crashing)
- Use existing localizable text for Cancel button.
closes #1191
=> Fix invite crashing without sms

.github/ISSUE_TEMPLATE.md
* Firefox 46.0.1
Looks like someone just blindly copied the debug log hint from the Android repo's template.
This makes it more clear for iOS users.
=> Improve debug log hint in issue template

Signal/src/contact/ContactsManager.m
Seeing some intermittent segfaults with latestContacts in the crash reporter.
```
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000eb0
Triggered by Thread:  1
```
```
Thread 1 name:
Thread 1 Crashed:
0   CoreFoundation                	0x000000018182df24 -[__NSDictionaryM getObjects:andKeys:count:] + 112 (NSDictionary.m:609)
1   CoreFoundation                	0x000000018186ffe4 -[NSDictionary allKeys] + 180 (NSDictionary.m:1165)
2   Signal                        	0x000000010003ef74 -[ContactsManager allContacts] + 124 (ContactsManager.m:406)
3   Signal                        	0x000000010003fd70 -[ContactsManager nameStringForPhoneIdentifier:] + 96 (ContactsManager.m:502)
4   Signal                        	0x000000010025d224 …
```
=> Initialize latestContacts to empty dict

Podfile, Podfile.lock, Signal.xcworkspace/xcshareddata/Signal.xcscmblueprint, Signal/Signal-Info.plist
Rebased OWS fork of SocketRocket against upstream
Pulling in SocketRocket directly from OWS Github rather than going
through the motions of publishing a pod that only we use.
// FREEBIE
=> attempt to fix intermittent SEGFAULT in SocketRocket (Maybe Fixes #1196)

Signal/src/view controllers/InboxTableViewCell.m
This seems to be responsible for about 3% of crashes.
=> hide UI element must happen on main thread

Signal/src/view controllers/MessagesViewController.m
FIXES #1222
Maybe this code was a vestige of a former way we were customizing the
back button. In any case, it's no longer required for swipe-to-pop
functionality.
Thanks for the good reproduction steps @big-r81! 
// FREEBIE
=> Prevent freeze when swiping back twice.

Signal/src/view controllers/MessagesViewController.m
Quick fix for #1227 
We can do a more robust resizing to enforce our limits more explicitly and gracefully, as described here: #1233
=> Failure to send images

.travis.yml, Podfile, Podfile.lock, Signal/src/network/http/RPServerRequestsManager.m
So long forked version of SocketRocket!
We got our security policy needs merged upstream at: https://github.com/facebook/SocketRocket/pull/429. 🎉 
The real impetus is a bunch of crashes we're seeing in SocketRocket. Not as many as with <2.3.2, but still our most popular source of crashes. As crash fixes get incorporated into SocketRocket now keeping up to date will be much easier.
=> Get back on upstream SocketRocket

Signal/Signal-Info.plist, Signal/src/view controllers/MessagesViewController.m
Fixes #1245 
There is a new string required, explaining *why* we need access to a users media library.
Since this is the result of a user pressing "Choose from Library..." it shouldn't be a big surprise.
=> Ios10 crash on attaching media

Libraries/FLAnimatedImage/FLAnimatedImage.m, Signal/Signal-Info.plist, Signal/src/audio/AppAudioManager.h
* Fix compiler warnings by explicitly casting to int (CGPoint floats are being shuffled into a bitmap)
* Show a better permissions message when viewing attachments.
* Fix comment.
// FREEBIE
=> IOS9 Fixes

Signal/Signal-Info.plist, Signal/src/view controllers/MessagesViewController.m, Signal/src/views/OWSDisplayedMessageCollectionViewCell.m, Signal/src/views/OWSDisplayedMessageCollectionViewCell.xib
FIXES #1266 
We were occasionally seeing extra tall error messages. This is because,
when appropriate, we were adding the space for a timestamp, but then
never actually rendering the timestamp.
So now:
- Error Messages get a printed timestamp when appropriate
- Which means Error Messages aren't rendered too-tall
// FREEBIE
=> Fix extra tall error messages by rendering timestamp

Signal/src/view controllers/MessagesViewController.m
This is closer to the 2.3 version.
Seems like upstream sizing has changed since our upgrade. This wider size calculation makes sense if you're losing space to the avatar, but since we're not using avatars the full width bubbles can make the whole view seem a bit crowded when you have large blobs of text.
Previously this:
Has been changed to this:
// FREEBIE
=> Narrow the bubbles a bit.

Signal/src/view controllers/MessagesViewController.m
* iPhone 6, iOS 9.3.3
If we hide the input toolbar, we should hide the keyboard too
//FREEBIE
=> FIX: Leaving group should dismiss keyboard #1274

Podfile.lock
FIXES #1277
Previously, if you tapped in the white space adjacent to the text bubble,
the bubble would highlight. No menu was show or interaction made
available. This is confusing.
It was fixed upstream, so this was as simple as:
pod update JSQMessagesViewController
// FREEBIE
=> Don't highlight text bubble when long pressing adjacent to text bubble

Signal/src/Models/TSMessageAdapaters/TSPhotoAdapter.m
=> Prevent crash when copying corrupted image attachment.

Signal.xcodeproj/project.pbxproj, Signal/src/view controllers/MessagesViewController.m
FIXES #1272
The root of the problem is we were using the deprecated ALAssetsLibrary
framework, which couldn't find certain assets.
By using the photos framework not only are we able to find these
assets, but it also cleans up our code:
* no more copying byte buffers
* no more detecting file type
// FREEBIE
=> Fix "can't reattach saved GIF" (and others)

Podfile.lock, Signal/Signal-Info.plist, Signal/src/Models/TSMessageAdapaters/TSMessageAdapter.m, Signal/src/call/RecentCallManager.m, Signal/src/environment/VersionMigrations.m, Signal/src/network/PushManager.m, Signal/src/view controllers/MessagesViewController.m, Signal/src/view controllers/NewGroupViewController.m, Signal/src/view controllers/SignalsViewController.m
Incorporating https://github.com/WhisperSystems/SignalServiceKit/pull/20. Description/Motivation copied from there: 
Description
-----------
Ensures a deleted thread actually deletes it's interactions and attachments. Also a cleanup helper to remove any dangling interactions and attachments hanging around after their thread has been deleted.
Motivation
-----------
Occasionally we are seeing messages from deleted threads reappear in new threads. Spooky stuff. :eyes:
This is because though the thread is deleted, some of the thread's interactions are not, leaving them with a dangling reference to the thread's contact ID. When the thread is recreated, the references are no longer dangling, and they reappear in the thread.
This could also cause any large attachments associated with those …
=> Fix delete attachments

Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m
* iPhone Simulator 6S, 9.3
The object is already cached & the waveform view constructed when scrolling,
so there's no need to re-create the view.
This doesn't fix the problem with the wave-form generation on the first
view of the message.  That is a more critical problem in the underlying
SCWaveformView class which renders on the main thread instead of doing
it asynchronously.
I've verified by hacking (due to being on the simulator) a large 6-minute mp3
into the chat conversation & then scrolling back & forth.  The first display still
hangs until SCWaveformView is done, but further scrolling remains smooth.
FIXES #1258
=> Improve audio waveform scrolling performance

Signal/Signal-Info.plist, Signal/src/environment/VersionMigrations.m
On older devices with lots of data, the orphan data cleaner can time
out. Here we're trading certainty that the migration completed for
confidence that the boot process doesn't time out.
// FREEBIE
=> Orphan-data cleanup no longer causes timeout

Signal/src/Models/TSMessageAdapaters/TSAnimatedAdapter.m
* iPhone 6, iOS 9.3.3
TSAnimatedAdapter is used when rendering GIFs. TSAnimatedAdapter
inherits from JSQMediaItem but does not provide a custom implementation
of the hash method. The default implementation of hash in JSQMediaItem
results in all messages of a given interaction type (incoming,
outgoing) sharing a cached bubble size. For this reason, JSQMediaItem
subclasses are required to implement hash (see
https://github.com/jessesquires/JSQMessagesViewController/issues/631).
This commit fixes #1275 by implementing hash in TSAnimatedAdapter
the same way TSPhotoAdapter does.
=> Fix incorrect GIF message bubble sizing

Podfile.lock
FIXES #1296
Our pod SSKeychain was renamed to -> SAMKeychain to avoid collision with
the iOS10 library SSKeychain.
* log failure to write keychain (this seems to only happen on simulator)
* ensure we exit if we fail to set DB cipher key
// FREEBIE
=> Avoid collision with iOS10 SSKeychain framework

Signal/Signal-Info.plist, Signal/src/environment/VersionMigrations.m
Otherwise we'll never run future migrations.
// FREEBIE
=> Set current migration version on first run.

Signal/src/view controllers/CodeVerificationViewController.m
* iPhone 6S, iOS 9.3
The verification code for registering a new phone number comes as 6 digits number in two groups separated by a dash: 123-456. When typing in the received verification code, the user expects to type a dash after the first three digits, which is not possible. Prior to this commit, the dash would automatically appear after typing in the fourth digit.
With this commit, the dash is introduced after typing the third digit, resulting in a smoother user experience.
=> verification code field: improved user experience

Podfile.lock, Signal/Signal-Info.plist, Signal/src/view controllers/MessagesViewController.m
- Group updates were appearing as "unsupported attachment"
- Couldn't message in a new group unless it had attachment.
// FREEBIE
=> Fix groups breaking without avatar

Podfile.lock, Signal/Signal-Info.plist, Signal/src/AppDelegate.m, Signal/src/environment/VersionMigrations.m
I botched a migration 6 months ago and left some lingering TSRecipients serialized in
our data store, laying in wait to explode the next time we enumerate every
object in the database (e.g. when we add an index). Sigh.
fixes #1348
// FREEBIE
=> Fix crash on boot =/

Podfile, Podfile.lock, Signal.xcodeproj/project.pbxproj, Signal/Signal-Info.plist, Signal/src/AppDelegate.m, Signal/src/environment/Migrations/OWS100RemoveTSRecipientsMigration.h, Signal/src/environment/Migrations/OWS100RemoveTSRecipientsMigration.m, Signal/src/environment/Migrations/OWSDatabaseMigration.h, Signal/src/environment/Migrations/OWSDatabaseMigration.m, Signal/src/environment/Migrations/OWSDatabaseMigrationRunner.h, Signal/src/environment/Migrations/OWSDatabaseMigrationRunner.m, Signal/src/environment/VersionMigrations.m
fixes #1358 
Slow launching:
1. ) is frustrating UX
2. ) leads to a crash if longer than 20 seconds.
To address this:
1. ) DB has been moved to async wherever possible in the path of app launching.
2.) New migration template allows most migrations to be run async, while still tracking that they eventually get run.
=> Faster startup, easier migrations

Signal/Signal-Info.plist, Signal/src/Models/OWSMessagesBubblesSizeCalculator.m, Signal/src/view controllers/MessagesViewController.m
fixes #1368
(rebased on #1369)
Apple switched emoji fonts from AppleColorEmoji to AppleColorEmojiUI.
The new font doesn't compute it's size correctly, causing containing
rectangles to be too small.
This commit scrubs strings of the new emoji font, and replaces it with
the old.
// FREEBIE
=> fix ios10 emoji clipping

Signal/src/view controllers/CodeVerificationViewController.m
* iPhone 6S, iOS 9.3
During account creation in the verification code step the user should be presented with his complete international phone number (including country code), entered in the previous step.
=> code verification: show complete phone number

Podfile, Podfile.lock, Signal/Signal-Info.plist, Signal/src/view controllers/MessagesViewController.m, Signal/src/views/OWSExpirableMessageView.h, Signal/src/views/OWSExpirationTimerView.h, Signal/src/views/OWSExpirationTimerView.m, Signal/src/views/OWSIncomingMessageCollectionViewCell.m, Signal/src/views/OWSOutgoingMessageCollectionViewCell.m
If you continuously exit and re-enter a conversation with disappearing message timers, you'll notice things gradually get slo o o o  o wer. 
Due to a memory leak fixed in this PR.
=> fix slow loading conversation screen with disappearing messages

Signal/src/view controllers/MessagesViewController.m
An existing related crash is much more common after 33f6a9552058747d016a788f7de29144e598788e.
Partial revert of 33f6a9552058747d016a788f7de29144e598788e
This was the only change proximate to the crash.
Crash looks like this:
Last Exception Backtrace:
0   CoreFoundation                  0x189c601c0 __exceptionPreprocess + 124 (NSException.m:165)
1   libobjc.A.dylib                 0x18869855c objc_exception_throw + 56 (objc-exception.mm:521)
2   CoreFoundation                  0x189c60094 +[NSException raise:format:arguments:] + 104 (NSException.m:131)
3   Foundation                      0x18a6ea82c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112 (NSException.m:157)
4   UIKit                           0x1903a534c -[UICollectionView …
=> partial fix for crash in database modified

Podfile, Podfile.lock
Hack to fix https://github.com/jessesquires/JSQMessagesViewController/issues/1885
This doesn't happen often, but is reproducible under simulated message churn (~50 insert/update/deletes randomly spaced over 10 seconds).
During performBatchUpdates, the collectionViewLayout can call layoutAttributesForElementsInRect which can reference the just-deleted item's view. (The view presumably hasn't been deleted yet, but will be by the time performBatchUpdates is complete).
It's opaque how layoutAttributesForElementsInRect get's it's list of views. I can only speculate how this works based on debugging, but it seems that the CollectionFlowLayout keeps an internal list of item frames, which when crashing still contain items corresponding to the to-be-deleted items.
In any case, it seems like a bug …
=> [JSQMVC] Fix crash on delete when under load.

Signal/src/view controllers/MessagesViewController.m
HACK to work around radar #28167779
"UICollectionView performBatchUpdates can trigger a crash if the collection view is flagged for layout"
more: https://github.com/PSPDFKit-labs/radar.apple.com/tree/master/28167779%20-%20CollectionViewBatchingIssue
I have never reproduced the crash, but it's appearing in about 0.05% of
<=2.6.2 sessions and an alarming ~5.0% of beta sessions >=2.6.3.8.
// FREEBIE
=> Attempt to fix intermittent crash in messages view controller

Signal/src/view controllers/MessagesViewController.m
* iPhone 6s Plus, iOS 10.1
This PR makes it so that the "outgoing message sent" sound effect will not play if the "Notification Sounds" toggle is set to OFF in the Settings -> Notification menu, as per #1373. 
Manually tested on my phone. It looked like there weren't already automated tests in place for this view controller, so figuring out how to write a test against my 3-line change when I don't already have familiarity with the codebase seemed a bit much.
1. Make sure your device sound is on and volume is up.
2. Send a message. It should play an outgoing message sound.
3. Go to Settings -> Notifications, and disable "Notification Sounds"
4. Send another message. It shouldn't play a sound.
=> Outgoing message sound respects Settings toggle (#1373)

Signal.xcodeproj/project.pbxproj, Signal/src/Models/OWSMessagesBubblesSizeCalculator.h, Signal/src/Models/OWSMessagesBubblesSizeCalculator.m, Signal/src/view controllers/MessagesViewController.m, Signal/test/Models/MesssagesBubblesSizeCalculatorTest.swift, Signal/test/SignalTests-Bridging-Header.h
fixes #1422 
partial revert of: a28fea8384c6d67b26931bde3e056a62f02e48e0
The earlier fix for the broken ios10 emoji font ended up breaking some messages for users with tall fonts (at least Chinese/Japanese).
Here we have a lighter touch - ensuring we don't touch messages that don't use emoji.
Also, introduce a different approach to the fix, rather than trying to compute the bounding rect of an appropriately attributed string, just add an extra bit of height per line.
This approach isn't ideal for long messages with only one emoji line in them, but the previous approach was incompatible with Chinese messages that also contain emoji. See the new `MesssagesBubblesSizeCalculatorTest.swift` for test cases considered.
// FREEBIE
=> Fix cropped Chinese/Japanese messages

Signal/src/view controllers/SignalsViewController.m
New installs are getting smashed with three popups at once. It's really gross.
This is still gross, but a little less terrible. What we really need is a better on boarding process explaining the need for these permissions.
// FREEBIE
=> Don't show permissions pop-up until user has seen contact disclaimer

Signal/src/Models/OWSMessagesBubblesSizeCalculator.m, Signal/test/Models/MesssagesBubblesSizeCalculatorTest.swift
This is an expedient, but not good, "fix". Some messages are going to
have extra space at the bottom of the bubble. But, for the time being,
that's preferable to getting messages clipped.
// FREEBIE
=> Address some lingering emoji cropping

Signal/src/view controllers/MessagesViewController.m
* iPhone 7, iOS 10.1
* iOS Simulator 6, 7, 7 Plus, iOS 10.0
- This addresses some of the concerns raised #1453. While the chat screen does respond to dynamic type, it only does so currently if the user leaves the chat screen and return. This makes it so that the screen size adjusts as soon as the user changes the text size settings.
=> Automatically adjust message bubble text size on dynamic text changes.

Podfile, Podfile.lock
Revert 50abf4d02d2c95b11fe2248e57a571c6389f7317 as it was fixing a crash we weren't actually seeing in the wild.
The real problem was addressed (or, worked around) here:
1eb234e8baf7a585def1668013c1cf26bf6dbca8
// FREEBIE
=> revert JSQMVC patch

Signal/Signal-Info.plist, Signal/src/contact/OWSContactsManager.m
Restore contactsComparator which is still being used in the group member
listing
partial revert of 81e1ec4b9ed58e282e1d02a8c3a5b82e65f0cb4b
// FREEBIE
=> Fix crash in group member listing

Signal/src/view controllers/MessagesViewController.m, Signal/src/view controllers/NewGroupViewController.m, Signal/translations/en.lproj/Localizable.strings
* iPhone SE, 10.1.1
This is a start at #864 and #1210. Any feedback on how well this conveys meaning to the user/fits with Apple's HIG would be appreciated. Major missing pieces that still need to happen:
- [] We have to localize the Storyboards and I'm not sure how to do that - a number of the confusing buttons are built in IB and while I can set runtime defined `accessibilityLabel`s and such it doesn't localize into files without additional Xcode black magic
- [] I want to do magic tap at least on phone calls, just need to work out the state logic properly
- [] We can make things like reading out the message a lot nicer where it says things like "sent on" instead of just spitting out the date (WhatsApp does it well)
- [] I couldn't figure out a way to tap on the name …
=> Improve accessibility a bit

Libraries/iRate/iRate.h, Libraries/iRate/iRate.m, Signal/src/AppDelegate.m, Signal/src/util/AppStoreRating.h, Signal/src/util/AppStoreRating.m
* iPhone5,2, iOS Version: 9.3.5
Local notification prevents iRate prompt. I added a flag to prevent the next prompt to be presented.
Should fix #1530
Testing was a bit tricky as notifications are hard to generate. When the app was going to the background I created a new message and a local notification to ensure that:
- no prompt was presented when clicking on the notification
- a prompt was presented when clicking directly on the icon
I originally implemented another strategy that prevented useCount increment but the limiting condition may not be the useCount so I changed to the pushed alternatives.
I thought about an alternative adding a delay as a condition, for instance: Can't prompt in less than 30 seconds. That would delay the prompt to the next …
=> Prevent iRate prompt when handling local notifications

Signal/src/Models/TSMessageAdapaters/TSMessageAdapter.m
Previously we had our "queued" and "failed" logic backwards.
// FREEBIE
=> Fix show error message when download fails

Signal/src/util/Launch Screen.storyboard
The previous launch screen was initially built on iphone5, but we never
scaled the logo to have the same proportions on iphone6 and larger
screens. Now it's scaled proportional to the screen width.
// FREEBIE
=> Bump up launch screen logo size on iPhone6 and larger

Signal/src/Storyboard/Main.storyboard, Signal/src/call/CallService.swift, Signal/src/call/NonCallKitCallUIAdaptee.swift, Signal/src/call/PeerConnectionClient.swift, Signal/src/call/SignalCall.swift, Signal/src/call/Speakerbox/CallKitCallManager.swift, Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift, Signal/src/call/UserInterface/CallUIAdapter.swift, Signal/src/view controllers/CallViewController.swift
**note:** this isn't targeting master.
Fixes a problem where the system call screen (CallKit) mute button could get out of sync with the in-app call screen's mute button.
This includes a refactor which, I think, better separates concerns and consequently reduces dependencies in the CallViewController.
=> Sync CallKit mute button state with in app mute button.

Signal.xcodeproj/project.pbxproj, Signal/src/call/CallService.swift, Signal/src/call/PeerConnectionClient.swift, Signal/src/call/Speakerbox/CallKitCallManager.swift, Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift, Signal/test/call/PeerConnectionClientTest.swift
This is primarily a refactor to move WebRTC integration code from the CallService to the PeerConnectionClient.
- PeerConnectionClient is already the primary point of WebRTC integration
- CallService is too big.
Also snuck  in
https://github.com/WhisperSystems/Signal-iOS/commit/24baa027c2cd30c6c42465715eaa6e43e6083721 which is a useful feature both for offline testing and in the hypothetical case where SignalService doesn't return ICEServers.
=> test peerconnectionclient

Libraries/WebRTC/README.md, Libraries/WebRTC/RTCAudioSession.h, MAINTAINING.md, Signal.xcodeproj/project.pbxproj, Signal/src/Signal-Bridging-Header.h, Signal/src/call/CallAudioSession.swift, Signal/src/call/CallService.swift, Signal/src/call/NonCallKitCallUIAdaptee.swift, Signal/src/call/PeerConnectionClient.swift, Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift, Signal/src/call/UserInterface/CallUIAdapter.swift, Signal/src/view controllers/CallViewController.swift, Signal/test/Models/AccountManagerTest.swift, Signal/test/call/CallAudioSessionTest.swift
In the upcoming webrtc branch, previously we were recording before the call was completely established, causing the user to be inexplicably prompted for recording permissions before they could see an incoming call.
Bulk of the work in: https://github.com/WhisperSystems/Signal-iOS/commit/dbb29d7d7ef7635e22e8e737f9a0a94d86a052cb
> Don't require recording permissions until call is ringing.
> We do this by manually managing the RTCAudioSession.
> Unfortunately to do this we have to include a couple of RTC headers not
> exported by the default build of WebRTC.framework (see: Libraries/WebRTC)
and the first two commits are just included for expedience.
=> Don't start recording until call is visible

Podfile.lock, Signal/Signal-Info.plist
Current implementation is blocked in Cuba, plus there are reports of
Signal working w/o domain fronting anyway.
// FREEBIE
=> [SSK] remove Cuba from domain fronting

Podfile, Podfile.lock, Signal.xcodeproj/project.pbxproj, Signal/Signal-Info.plist, Signal/src/AppDelegate.m, Signal/src/environment/Migrations/OWS102MoveLoggingPreferenceToUserDefaults.h, Signal/src/environment/Migrations/OWS102MoveLoggingPreferenceToUserDefaults.m, Signal/src/environment/Migrations/OWSDatabaseMigrationRunner.m, Signal/src/environment/PropertyListPreferences.h, Signal/src/environment/PropertyListPreferences.m
Most likely this would be  because the user hasn't unlocked their device
since last restart.
This behavior existed once before, but the startup ordering is pretty
delicate. So, we're now redundantly checking in SSK in case this
delicate startup logic gets mis-ordered again.
Also fixed the AppDelegate method to check for the proper
applicationState, since it will never be "active" in didFinishLaunching.
fixes https://github.com/WhisperSystems/Signal-iOS/issues/1627
corresponding SSK: https://github.com/WhisperSystems/SignalServiceKit/pull/99
// FREEBIE
=> Bail on startup if DB password is inaccessible

Signal.xcodeproj/project.pbxproj, Signal/src/call/CallService.swift, Signal/src/call/NonCallKitCallUIAdaptee.swift, Signal/src/call/PeerConnectionClient.swift, Signal/src/call/Speakerbox/CallKitCallManager.swift, Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift, Signal/src/call/UserInterface/CallUIAdapter.swift, Signal/src/view controllers/CallViewController.swift
Distinguish between localHangup, remoteHangup, and call failure.
This allows us to put CallKit in the proper state, ready to receive new
calls without having a backlog of phantom calls which haven't been
properly removed.
Note the "call error" occurs at the point ICE fails, which takes a
while. Anecdotally, like 10 seconds, which feels like a long to be
talking into the ether.
I briefly considered failing at 'disconnected', which happens much
sooner, but that's actually a recoverable state. E.g. if you toggle
airplane mode you can see that you bounce into `disconnected` and then
back to `connected`, so I don't think we'd want to fail the call as long
as WebRTC considers it "recoverable".
=> Recover CallKit state when remote client fails to hangup

Signal/Signal-Info.plist, Signal/src/Signal-Bridging-Header.h, Signal/src/call/CallAudioService.swift, Signal/src/call/CallService.swift, Signal/src/call/NonCallKitCallUIAdaptee.swift, Signal/src/call/PeerConnectionClient.swift, Signal/src/call/SignalCall.swift, Signal/src/view controllers/CallViewController.swift
Roughs out the video-related views.
* Adds views for local and remote video to call view.
* Adds plumbing for the local and remote video tracks from the `PeerConnectionClient` to `CallService`.
* Adds plumbing for the local and remote video tracks from the `CallService` to `CallViewController`.
* Ensures observers of `SignalCall` and `CallService` are always invoked on main thread.
* Improve thread safety of `SignalCall` and `CallService`.
=> Charlesmchen/webrtc/video2 

Signal/src/call/PeerConnectionClient.swift
Without this, I get a SEGFAULT on iOS 9.3 device 1 in 3 calls when
accessing the RTC extern constants. Swift bug?
Currently using XCode 8.2
// FREEBIE
=> Working around a bizarre crash on iOS 9

Signal/src/call/SignalCall.swift, Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
This addresses a couple issues related to receiving calls when already on a call. 
So. previously, when you initiated a Signal Call to Possum, connected and started talking. Then received a non-Signal call from Squirrel, you'd see this:
Which is weird, because you shouldn't be able to  "Accept" the new call without specifying what to do with the old call (e.g. "Hold" or "End" the existing call).
Turns out, we never marked the outgoing SignalCall as connected, so that's fixed in e425d35
With that, the interrupting call screen looks like this:
Note the "hold & accept" option. We didn't intend on supporting hold initially, but I took a stab at it, just to see how difficult it would be in: https://github.com/WhisperSystems/Signal-iOS/commit/969b73cad8ed3fb542848e398a4620a9f1d40f9e
It worked, …
=> Better concurrent call handling

Signal/src/view controllers/CallViewController.swift
The "decline" and "accept" were too close together. Added a spacer, the
same size as an extra button between the two.
before:
after:
// FREEBIE
=> More space for non-callkit incoming call buttons

Signal/src/call/CallService.swift, Signal/src/call/PeerConnectionClient.swift
This work prevents crashes due to a number of edge cases, mostly concurrency-related.
* Adds asserts that `CallService. peerConnectionClient` is nil when we create a new `PeerConnectionClient`.  This isn't always true.  These asserts should help us identify a repro.
* `PeerConnectionClient` does a lot of dispatching to the signaling queue and the main thread. I've  used weak references and added checks in these places around termination.
* The exact order of operations during termination matters, as noted by the existing comment in `terminateInternal()`.  I've slightly reworked this logic.
It's quite easy to repro crashes before this branch that are not reproducible after this branch.  Just start & stop many calls to another device without even accepting the call on the second device.  It …
=> Avoid crashes when closing peer connection client.

Signal/src/call/CallService.swift, Signal/src/call/PeerConnectionClient.swift
Eliminates a last class of edge cases around receiving "did add stream" events after a PCC has been torn down.
=> Be even more cautious when tearing down a PeerConnectionClient.

Signal/src/call/UserInterface/CallUIAdapter.swift
This shouldn't assert; it's not a bug, just an edge case that we want to handle properly.
=> Don’t assert when two devices call each other simultaneously.

Signal/src/call/CallService.swift, Signal/src/call/UserInterface/CallUIAdapter.swift, Signal/src/view controllers/CallViewController.swift
Previously, `CallUIAdapter` ensured that `CallAudioService` was always wired up to observe any call by doing so in the "only two" pathways for new calls: `reportIncomingCall()` and `startOutgoingCall()`.  The problem is that `OutboundCallInitiator` now uses a new pathway: `startAndShowOutgoingCall()`.  Rather than adding the right wiring there, I decided to DRY this up and by making `CallUIAdapter` observe `CallService` and setting up the observation anytime `CallService`'s call property is set.  That should handle all of these cases and future-proof us as well.
=> Ensure audio service observation of call is always correctly wired up.

Signal/src/call/PeerConnectionClient.swift
Yet another attempt to get this right.  Achieving thread safety by dispatching async to threads/queues introduces delays wherein a remote video track may be deallocated after its associated `RTCPeerConnection`, which causes exceptions to be thrown in its destructor.  Therefore, we use synchronization to access PCC's `remoteVideoTrack` property synchronously.
=> Synchronize access to remoteVideoTrack.

Signal/src/call/OutboundCallInitiator.swift
Now that it's easier to start a thread with a non-contact recipient this
is more relevant.
// FREEBIE
=> contact can be nil for outgoing redphone call

Signal/src/call/CallService.swift, Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
- Previously only incoming calls had their timeout promise fulfilled
- Previously we'd stop the timeout once ringing started, but we
should continue the timeout clock until the users are speaking.
// FREEBIE
=> Fix call timeout

Signal/src/AppDelegate.m, Signal/src/contact/OWSContactsManager.m, Signal/src/environment/Environment.m, Signal/src/environment/VersionMigrations.m
Builds upon: https://github.com/WhisperSystems/Signal-iOS/pull/1763
=> Flush logs before exiting the app.

.gitmodules, Signal/test/call/PeerConnectionClientTest.swift
partial revert of 8b3b283
Easier for travis to fetch from https URL. If you as a developer want to
push to the submodule via git (maintainers only) you'll have to modify
your local git remotes after checkout:
cd Carthage
git remote origin set-url git@github.com:WhisperSystems/Signal-Carthage.git
=> fix tests / CI

Signal/src/view controllers/FingerprintViewController.m
* iPhone 6, iOS 10.2.1
This pull request should provide a solution to issue #1602 
The new behaviour is kept very simple and works as follows:
- When the keys are successfully scanned, the fingerprintViewController is dismissed
- When the key verification fails, the original layout is restored, so that the keys can be rescanned
This includes a small bugfix: When camera access is denied, then the share button will be disabled. This should be fixed by disabling the share button only after permissions are checked.
This is my first contribution. It is kept very simple, so there should be no problems merging this.
=> Issue1602 + small bug fix FREEBIE

Podfile.lock, Signal/src/view controllers/MessageComposeTableViewController.m
https://github.com/WhisperSystems/SignalServiceKit/pull/130
* Modify `PhoneNumber` to identify possibly multiple phone numbers for given user input by trying to prepend:
* "+" 
* The country code for the current user's phone number.
* The country code that corresponds to the phone's default region.
* Surface multiple possible matches as "invite via SMS".
* Check multiple possible matches for Signal accounts and show "start conversation with X".
Note that these screenshots were all taken on a device registered in UK (+44).
Fixes: https://github.com/WhisperSystems/Signal-iOS/issues/1833
=> Fix non-contact lookup for non-US users.

Signal/src/view controllers/MessagesViewController.m, Signal/translations/en.lproj/Localizable.strings
Easy way to test to send some large text (e.g. http://norvig.com/big.txt ) from desktop, copy & paste in iOS, try to send.
=> Limit size of outgoing text messages.

Signal/src/call/PeerConnectionClient.swift, Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
It's not clear why we were ever dispatching `sync` here.
Before this:
Place a call
See "connecting..."
Hang up
UI hangs for ~5 seconds
See "call failed" on CallKit screen
Press "cancel" on CallKit screen
returned to responsive app.
=> Fix "Call failed" due to deadlock when immediately terminating call

Signal/src/view controllers/AdvancedSettingsTableViewController.m, Signal/src/view controllers/PrivacySettingsTableViewController.m
There's more than one way to flip a switch.
Might fix https://github.com/WhisperSystems/Signal-iOS/issues/1865
=> Fix switches for those who like to "slide"

Signal/src/view controllers/CountryCodeViewController.h, Signal/src/view controllers/CountryCodeViewController.m, Signal/src/view controllers/RegistrationViewController.m
Previously, our registration view would show a "country code" label (without a country name) when using the default country (derived from the device's region setting) and show the "country name" if the country was changed.  
I've changed this to always show the "country code" label and to always show the actual country code after the calling code.  Country names tend to be long, so there isn't enough space to show the "country code" label, the country name and the calling code.
The goal is to be more consistent and to always indicate to the user their current state.
=> Rework country views in registration view.

Signal/src/Models/TSMessageAdapaters/TSPhotoAdapter.m, Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m
This is why copy & paste of images on iOS 9 isn't working.
=> Copy images to pasteboard as data, not UIImage.

Signal/src/Models/TSMessageAdapaters/AttachmentUploadView.m, Signal/src/views/OWSProgressView.m
It was too fat, which looks fine when the progress bar is empty but looks "chubby" as the progress completes.
=> Slightly tweak the appearance of the attachment upload progress bar.

Signal/src/Storyboards/Registration.storyboard
@NicolasCGN commented an hour ago:
> The string 'Already have a Signal account?' doesn't get translated in the localised app. Is there a type in the string key?
=> Fix translation of “already have an account?” button.

Signal/src/view controllers/SignalAttachment.swift
Per convo with Moxie, we're bumping this up even higher.
=> Bump maximum animated GIF file size to 25mb.

Signal/src/ViewControllers/RegistrationViewController.m
We need to separate "view state" from "view model state" in registration view, i.e. the current calling code (e.g. "+44") from how it is presented (e.g. "+44 (UK)").  We should be used the raw calling code when constructing the phone number to verify.  
This bug doesn't have any effect in production which is how it slipped through testing, but it's not right.
=> Add explicit calling code state to registration view.

Signal/src/ViewControllers/CodeVerificationViewController.m
No need for special phone characters like: *, -, +
=> Use numeric pad for verifiation code entry

Signal/src/ViewControllers/CodeVerificationViewController.m, Signal/translations/en.lproj/Localizable.strings
Two simple changes to make our verification screen a little more intuitive and useful.
5c
7+
=> registration: clarify verification process

Signal/src/contact/OWSContactsManager.m
`[SignalsViewController didAppearForNewlyRegisteredUser]` is doing its work every time the user returns to the home view.  It should probably only be called once.  
This PR only resolves the worse symptom - every time a newly-registered user returns to the home view, a new contacts store was being created.  I've opened a card for the bigger issue.
=> Don’t load contact store twice.

Signal/translations/bin/auto-genstrings
Otherwise it's really easy to generate strings from the wrong branch
=> when generating strings verify that SSK is on master

Signal/src/ViewControllers/FullImageViewController.m, Signal/src/ViewControllers/MessagesViewController.m, Signal/translations/en.lproj/Localizable.strings
`UIMenuController` has a horrible API.  Which menu items _might_ appear is a function of the last value written to its `menuItems` property, but which menu items you want to appear is contextual, so it's last-writer-wins without any good hook to update the menu items based on the context of the current user action.  
I've made MessagesVC a bit more defensive and made the media view a bit more polite.
=> Resolve the menu item conflicts between message view and media view.

Signal/src/Models/SyncPushTokensJob.swift
When we don't have an active set of push credentials for a user, we consider them "not a signal user". So if someone fails to upload push credentials, no one will be able to message them.
fixes https://github.com/WhisperSystems/Signal-iOS/issues/1618
This was a retention bug - nothing was retaining the promise returned by PushTokensJob, so it might be GC'd before it was completed.
I suspect there are more of these, so going to do an audit of our Promise usage.
=> unregistered user aka "one way messaging"

Signal/src/ViewControllers/CallViewController.swift, Signal/src/call/CallAudioService.swift, Signal/src/call/CallService.swift, Signal/src/call/UserInterface/CallUIAdapter.swift
* Speakerphone is being disabled around the time that the video and audio tracks become active. It's not on our side. I'm guessing that WebRTC sets the category for AVAudioSession and - not knowing that speaker phone has been enabled - disables speakerphone.  It's an unfortunate side effects of AVAudioSession's "last writer wins" API.  The solution is to update AVAudioSession after the video tracks become active.
* If you enable mute or video while in connecting, you would hit an assert. In production the call would be hung up.  
=> Fix speakerphone vs. WebRTC AND Fix CallService edge cases.

Signal/src/call/PeerConnectionClient.swift
=> Insist upon an "ordered" TCP data channel for delivery reliability.

Signal/src/ViewControllers/OWSTableViewController.m
The problem with the `commonInit` pattern is that if a superclass and subclass both use the pattern, the subclass's implementation won't know to call superclass's implementation since it's a private implementation detail.
=> Fix assert in conversation settings view.

Signal/src/contact/OWSContactsManager.m
previously if you had a contact, but no saved name
there would be a blank entry in your compose picker
=> show number for no-name contacts

Signal/src/ViewControllers/ContactsViewHelper.h, Signal/src/ViewControllers/ContactsViewHelper.m, Signal/src/ViewControllers/MessageComposeTableViewController.m, Signal/src/contact/OWSContactsManager.h, Signal/src/contact/OWSContactsManager.m
The previous check was a little too early. There is a brief window between when the contacts manager has updated it's contacts and when the contactsHelper (which is where our viewcontroller accesses it's contacts) has updated.
=> Fix flicker of "no contacts" screen on message compose

Signal/src/views/JSQMessagesCollectionViewCell+OWS.m
The actions offered by the phone number data detectors are confusing
within the context of a messaging app - e.g. people might assume that
the "call" action corresponds to a Signal call.
=> do not use phone data detectors

Signal/src/AppDelegate.m
ignore white space: https://github.com/WhisperSystems/Signal-iOS/pull/2152/files?w=1
* code cleanup
* Prefer dispatch_async vs. dispatch_sync when possible
I didn't personally experience a problem here, but if we end the background task before we're done with the work, we run the risk of not completing the work.
=> Make sure screen protection is applied before ending bg task

Podfile.lock, Signal/src/ViewControllers/MessagesViewController.m, Signal/translations/en.lproj/Localizable.strings
Based on #2153, so feel free to review that first, but the changes can be seen pretty clearly in: 
https://github.com/WhisperSystems/Signal-iOS/commit/c34462fb540f3671bde131e13644c40da81fd89d
requisite SSK: https://github.com/WhisperSystems/SignalServiceKit/pull/232
=> confirm before sending to untrusted identity

Signal/src/ViewControllers/SignalsViewController.m, Signal/src/ViewControllers/ThreadViewHelper.m
`yapDatabaseModified:` methods are expensive.  Home view doesn't need to observe database changes when its not the frontmost view or when the app is in the background.  
=> Streamline observation of database modifications in home view.

Signal/src/ProfileFetcherJob.swift
identity.
This allows us to view someone's SN before messaging them.
=> Save identity from profile fetch even if there's no pre-existing

Signal/src/ViewControllers/ConversationView/MessagesViewController.m, Signal/src/ViewControllers/ConversationView/OWSMessagesComposerTextView.h, Signal/src/ViewControllers/ConversationView/OWSMessagesComposerTextView.m
Previously tapping the input would pop the keyboard, which would hide the last couple messages, until you tapped a key, which would scroll to bottom.
Instead we should scroll to bottom when the keyboard is popped.
=> Fix: tapping input obscures last messages

Signal/src/Signal-Bridging-Header.h, Signal/src/Storyboard/Main.storyboard, Signal/src/ViewControllers/CallViewController.swift, Signal/src/ViewControllers/SignalsViewController.m, Signal/src/call/CallService.swift, Signal/src/call/NonCallKitCallUIAdaptee.swift, Signal/src/call/UserInterface/CallUIAdapter.swift
Problem Motivation:
tap-swipe-kill Signal
go to contacts app
choose to signal-call a signal contact Alice.
expected: 
see a call started with Alice
hear a call started with Alice
actual:
do *not* see a call started with Alice.
but worse yet, hear a call started with Alice.
The problem was we were triggering the call presentation logic with a notification, but when the app is being started cold. the observer hasn't started observing by the time we processed the activity.
Now that we're all gungho on programmatic VC's, I think we're better off avoiding the notification passing paradigm all together in favor of explicit presentation.
=> fix cold call from contacts

Signal/src/ViewControllers/ConversationView/MessagesViewController.m, Signal/src/views/OWSSystemMessageCell.h, Signal/src/views/OWSSystemMessageCell.m
The reason this doesn't "just work" with our collection view, is JSQ does a hit test based on the "messageBubbleContainerView" which we don't use in the system message. 
I considered adding one, just to satisfy the hit test in a consistent way, but I think I actually prefer this approach.
Plus doing layout with a container view when we're not using autolayout is a bunch of lines of code I'd rather not mess up.
=> delete system messages

Signal/src/ViewControllers/SignalsViewController.m
I'm actually not sure how I got my simulator wedged into this state -
but my contacts access was "undetermined" and I had several messages.
Maybe they appeared while the app was closed?
I verified that the banner appears as expected when access is denied.
=> Make sure we're requesting access for contacts before checking access

Signal/src/environment/NotificationsManager.m
Previously we weren't playing alert sounds for any of the following:
- missed call due to no longer verified
- missed call due to recent SN change
- regular ole' missed call
=> Play audible alert for missed call

Signal/translations/en.lproj/Localizable.strings
Just hit this for the first time using a debug build, and had a thought - because system alerts can sometimes pop up without providence, I think it's good to name the app in the alert to be clear what we're asking to update.
=> copy tweaks

Signal/src/Models/AccountManager.swift, Signal/src/ProfileFetcherJob.swift, Signal/src/call/CallAudioService.swift, Signal/src/call/CallService.swift, Signal/src/call/PeerConnectionClient.swift, Signal/src/call/WebRTCCallMessageHandler.swift, Signal/src/contact/SystemContactsFetcher.swift, Signal/src/util/DeviceSleepManager.swift, Signal/src/views/OWSExpirationTimerView.m
- make some logging clearer
- remove noisy unhelpful logging
- clearer method names
While debugging some call connectivity issues, I tried to clean up some of our logging and code. I wanted to separate this from the actual connectivity changes so that PR can be more focused.
The log statements I removed were kind of arbitrary - don't hesitate to veto any that you'd like to keep in. Comments in line...
=> Log/Code Cleanup

Signal/src/ViewControllers/CallViewController.swift, Signal/src/call/CallAudioService.swift, Signal/translations/en.lproj/Localizable.strings
- Nicer labels for devices in route picker
- Fix issue with audio not being routed to receiver if picked too early
=> audio route cleanup

Signal/src/ViewControllers/SignalsViewController.m
Might be redundant in some cases but `reloadData` should be cheap. Might help with the "empty home view" issue and also future-proofs us when refactoring home view in the future.
=> Always reload home view table when changing grouping.

Signal/src/util/ThreadUtil.m, SignalServiceKit/src/Messages/InvalidKeyMessages/TSInvalidIdentityKeyErrorMessage.h, SignalServiceKit/src/Messages/InvalidKeyMessages/TSInvalidIdentityKeyErrorMessage.m, SignalServiceKit/src/Messages/InvalidKeyMessages/TSInvalidIdentityKeyReceivingErrorMessage.m, SignalServiceKit/src/Messages/InvalidKeyMessages/TSInvalidIdentityKeySendingErrorMessage.m
This is increasingly irrelevant due to changes around safety number handling, but older clients with legacy messages can still run into this.
FIXES: https://github.com/WhisperSystems/Signal-iOS/issues/2346
=> ensure blocking keychange message has identityKey before proceeding

Signal/src/Models/TSMessageAdapaters/TSVideoAttachmentAdapter.m, Signal/src/Signal-Bridging-Header.h, Signal/src/ViewControllers/CodeVerificationViewController.m, Signal/src/ViewControllers/FingerprintViewController.m, Signal/src/ViewControllers/FingerprintViewScanController.m, Signal/src/ViewControllers/OWSConversationSettingsViewController.m, Signal/src/ViewControllers/OWSLinkDeviceViewController.m, SignalServiceKit/Example/TSKitiOSTestApp/Podfile.lock, SignalServiceKit/src/Account/TSAccountManager.h, SignalServiceKit/src/Account/TSAccountManager.m, SignalServiceKit/src/Account/TSAttributes.m, SignalServiceKit/src/Contacts/SignalRecipient.m, SignalServiceKit/src/Messages/OWSIdentityManager.m, SignalServiceKit/src/Messages/OWSMessageSender.m, SignalServiceKit/src/Network/WebSockets/TSSocketManager.m, SignalServiceKit/src/Security/OWSFingerprintBuilder.h, SignalServiceKit/src/Security/OWSFingerprintBuilder.m, SignalServiceKit/src/Storage/TSStorageHeaders.h, SignalServiceKit/src/Storage/TSStorageKeys.h, SignalServiceKit/src/Storage/TSStorageManager+keyingMaterial.h, SignalServiceKit/src/Storage/TSStorageManager+keyingMaterial.m, SignalServiceKit/tests/Contacts/SignalRecipientTest.m, SignalServiceKit/tests/Messages/OWSMessageSenderTest.m
The primary goal was to cache `localNumber` and `isRegistered`
In doing so I was compelled to gather some of the TSAccount concerns out of one of the myriad StorageManager extensions, which I think simplified things a bit.
note I updated all tests broken by these changes, but there are a couple failing SSK tests in master which remain broken in this branch.
=> cache local number

Signal/src/AppDelegate.m, Signal/src/environment/Migrations/OWS103EnableVideoCalling.m, Signal/src/util/OWSContactsSyncing.m, SignalServiceKit/src/Account/TSAccountManager.h, SignalServiceKit/src/Account/TSAccountManager.m, SignalServiceKit/src/Account/TSPreKeyManager.m
Now that `localNumber` is read from a dedicated dbConnection we don't have to worry about it blocking launch.
This has the side effect of making sure we pre-populate the cache for other uses of localNumber.
=> Simplify code / pre-cache localNumber

Signal/src/Models/OWSAvatarBuilder.m, Signal/src/Models/OWSContactAvatarBuilder.h, Signal/src/Models/OWSContactAvatarBuilder.m, Signal/src/contact/OWSContactsManager.m, Signal/src/views/ContactCell.swift, Signal/src/views/ContactTableViewCell.m
In the process, refactored the ContactAvatarBuilder to clarify intent of the two
methods. One is only used for non-signal contacts in the Invite flow.
The other should be used for any signal contacts so we have a single
consistent way of generating the avatar initials.
=> Use profile name/image when available.

SignalServiceKit/src/Protocols/ProtoBuf+OWS.m
followup to: ee613e48895855240ebc08f0a58aef970df0c101
Again, this solves a crash, but we'll want to revisit the perf
implications.
=> White listing must happen on main thread

Signal/src/ViewControllers/ConversationView/MessagesViewController.m
Let me preface this by saying I'm not married to this solution, but that I think we need to do something about this. It doesn't prevent anyone from using our app and it's been around for a long time (forever), but it's something that all our users see all the time.
When we send the nth message, we retain the footer for the n-1th message until the nth message is successfully sent.
Rendering process looks roughly like this:
1. render the footer on the n-1th message ("delivered")
2. draw the nth message with the "..." footer
3. update the nth message with the "sent" footer (and then "delivered) and hide the footer for
the n-1th message
In the normal case this all happens very quickly, which results in some unpleasant flicker every time you send a message due to the height of the footer …
=> Fix jolting animation after sending a message

Signal/src/Profiles/OWSProfileManager.m
whitelist cache are a bunch of NSNumber's, we need to check their `boolValue` rather than their presence.
Also, we shouldn't worry too much about creating an unnecessary db read when the cache is empty, because the alternative is that we'd create an unnecessary db write, which is much more expensive.
=> Fix whitelist

Signal/src/ViewControllers/ConversationView/MessagesViewController.m
We weren't always updating the "last visible timestamp" state when it should have changed.
=> Fix scroll down button state.

Signal.xcodeproj/project.pbxproj, Signal/src/Profiles/OWSProfileManager.h, Signal/src/Profiles/OWSProfileManager.m, Signal/src/Profiles/ProfileFetcherJob.swift, Signal/src/Signal-Bridging-Header.h, Signal/src/ViewControllers/ConversationView/MessagesViewController.m, Signal/src/ViewControllers/DebugUI/DebugUIMisc.m, Signal/src/ViewControllers/DebugUI/DebugUIProfile.swift, Signal/src/ViewControllers/DebugUI/DebugUITableViewController.m, Signal/src/ViewControllers/OWSConversationSettingsViewController.m, Signal/translations/en.lproj/Localizable.strings, SignalServiceKit/protobuf/OWSSignalServiceProtos.proto, SignalServiceKit/src/Messages/OWSProfileKeyMessage.h, SignalServiceKit/src/Messages/OWSProfileKeyMessage.m, SignalServiceKit/src/Messages/OWSSignalServiceProtos.pb.h, SignalServiceKit/src/Messages/OWSSignalServiceProtos.pb.m, SignalServiceKit/src/Messages/TSMessagesManager.m, SignalServiceKit/src/Protocols/ProtoBuf+OWS.h, SignalServiceKit/src/Protocols/ProtoBuf+OWS.m
1. Send an empty message upon whitelisting someone so they get our key right away.
2. Handle said messages.
3. Do not create a text message if there is no message body.
At present (1.) is implemented but disabled behind a feature flag so that we can let handling these messages roll out first.
(3.) exists so that we don't need to do this staged release dance in the future. 
=> profile key message

SignalServiceKit/src/Messages/TSMessagesManager.m, SignalServiceKit/src/Protocols/ProfileManagerProtocol.h
Since clients only include the `profileKey` for synced group messages when that group is whitelisted, it's presence is sufficient to deduce the group is whitelisted.
=> infer when group has been whitelisted on linked device

Signal/src/ViewControllers/CallViewController.swift
Using the existing `isViewLoaded` defined in UIKit will actually already do what we need without having to define a new var.
I could have made a new var with a name distinct from `isViewLoaded`, but this approach seems slightly more inline with UIKit - i.e. `loadView` is where the views are created.
=> Use existing isViewLoaded var

Signal/src/Profiles/OWSProfileManager.m
This shouldn't matter in most cases, but it can only help profiles sync faster in case of delivery problems or unreliable networks.
=> Add group members individual to profile whitelist when adding group.

Signal/src/Signal-Bridging-Header.h, Signal/src/ViewControllers/AppSettingsViewController.h, Signal/src/ViewControllers/AppSettingsViewController.m, Signal/src/ViewControllers/CallViewController.swift, Signal/src/ViewControllers/ExperienceUpgradesPageViewController.swift, Signal/src/ViewControllers/ShowGroupMembersViewController.m, Signal/src/ViewControllers/SignalsViewController.m
For 2.16
We were using UINavigationController in a couple of places.
=> Always present settings from OWSNavigationController

Signal.xcodeproj/project.pbxproj, Signal/src/AppDelegate.m, Signal/src/ViewControllers/AppSettingsViewController.m, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/HomeViewController.h, Signal/src/ViewControllers/HomeViewController.m, Signal/src/ViewControllers/ModalActivityIndicatorViewController.swift, Signal/src/ViewControllers/NewGroupViewController.m, Signal/src/ViewControllers/SelectRecipientViewController.m
Add a reusable "modal activity indicator" view that can be used during long-running blocking operations to:
* Block user interactions.
* Give visual indication to the user of the app state.
* Optionally offer a cancel button.
Note:
* The modal blocks UI immediately but hides for a second to avoid showing up during short-lived operations.
* The modal fades into view.
* We could add a label indicating what the app is doing, but this should be clear from context.
=> Add modal activity indicator view.

Signal/src/AppDelegate.m, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/HomeViewController.m, Signal/src/ViewControllers/NewContactThreadViewController.m, Signal/src/ViewControllers/NewGroupViewController.m, Signal/src/ViewControllers/SendExternalFileViewController.m, Signal/src/ViewControllers/ShowGroupMembersViewController.m, Signal/src/call/UserInterface/CallUIAdapter.swift, Signal/src/environment/Environment.h, Signal/src/environment/Environment.m, Signal/src/network/PushManager.m
Goal: ensure we never navigate to a conversation that we're already in.
Along the way I cleaned up the code significantly.
Bug Repro:
* On phone A, Navigate to group B, lock phone.
* Send message to group B from member.
* On phone A, swipe on notification to open Signal.
Expected: App is already in conversation view for group B.
Observed: App leaves and re-enters group B.
=> Normalize conversation presentation logic.

Signal/src/ViewControllers/ConversationView/ConversationViewController.m
We don't want to register our notification listeners until the conversation view loads, otherwise profile change events in particular can fire before the view is loaded and NPEs are easy to hit.
// FREEBIE
=> Fix NPEs when profiles change while entering conversation view.

Signal/src/AppDelegate.h, Signal/src/AppDelegate.m
didBecomeActive is too late in the case of launching from a
notification.
Also, start tracking when app setup is complete, and prevent certain
actions from occurring in that case. Eventually we'll enqueue these
actions rather than ignoring them, but we'll want to do more testing
before releasing that. In the meanwhile, if the environment isn't setup
at this point, a crash would be eminent anyway.
=> Fix 1-time crash when launching 2.16 from notification

Signal/src/Profiles/OWSProfileManager.m
Otherwise there's an unnecessary initial (innocuous) failed HTTP attempt on first launch for unregistered users.
For those users we'll see a [log] line like this shortly after first launch: 
"[MultiDeviceProfileKeyUpdateJob] localNumber was unexpectedly nil"
But shouldn't be a problem.
[log] example log of installing 2.16.1.3:
https://gist.github.com/anonymous/c45decfc8524fb62d5384be6df41e066#file-org-whispersystems-signal-2017-09-21-15-14-log-L48
=> Don't attempt to sync profile until registered.

Signal/src/ViewControllers/ConversationView/ConversationViewController.m
We weren't updating the "offers" to reflect changes to contacts.
=> Fix wrongful "add to contacts offer" issue, pt. 1.

SignalServiceKit/src/Messages/OWSMessageSender.m
This is really helpful when cross referencing debug logs with the
recipient. (We already log timestamps on the receiving side).
=> Log timestamp of sent messages

Signal.xcodeproj/project.pbxproj, Signal/src/AppDelegate.m, Signal/src/Jobs/MessageFetcherJob.swift, Signal/src/UserInterface/Strings.swift, Signal/src/ViewControllers/ContactsPicker.swift, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/HomeViewController.m, Signal/src/ViewControllers/InboxTableViewCell.m, Signal/src/ViewControllers/InviteFlow.swift, Signal/src/ViewControllers/NewContactThreadViewController.m, Signal/src/ViewControllers/NewGroupViewController.m, Signal/src/ViewControllers/OWSConversationSettingsViewController.m, Signal/src/ViewControllers/OWSTableViewController.h, Signal/src/ViewControllers/OWSTableViewController.m, Signal/src/contact/OWSContactsManager.h, Signal/src/contact/OWSContactsManager.m, Signal/src/environment/Environment.h, Signal/src/environment/Environment.m, Signal/src/environment/NotificationsManager.m, Signal/src/network/PushManager.m, Signal/src/util/Searcher.swift, Signal/src/views/ContactTableViewCell.h, Signal/src/views/ContactTableViewCell.m, Signal/src/views/GroupTableViewCell.swift, Signal/test/util/SearcherTest.swift, Signal/translations/en.lproj/Localizable.strings, SignalServiceKit/src/Messages/OWSMessageSender.m, SignalServiceKit/src/Messages/TSGroupModel.h, SignalServiceKit/src/Messages/TSGroupModel.m
- whispersystems.org -> signal.org
- nav color was wrong since iOS10
- update search results after clearing post SMS invite
This is related to the SMS feature that appears in the search suggestions when what you're searching for looks like a phone number but doesn't correspond to a signal contact.
=> Fix invite via SMS in search

Signal.xcodeproj/project.pbxproj, Signal/src/UserInterface/Strings.swift, Signal/src/ViewControllers/ContactsPicker.swift, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/InboxTableViewCell.m, Signal/src/ViewControllers/NewContactThreadViewController.m, Signal/src/ViewControllers/NewGroupViewController.m, Signal/src/ViewControllers/OWSConversationSettingsViewController.m, Signal/src/ViewControllers/OWSTableViewController.h, Signal/src/ViewControllers/OWSTableViewController.m, Signal/src/contact/OWSContactsManager.h, Signal/src/contact/OWSContactsManager.m, Signal/src/environment/Environment.h, Signal/src/environment/Environment.m, Signal/src/environment/NotificationsManager.m, Signal/src/util/Searcher.swift, Signal/src/views/ContactTableViewCell.h, Signal/src/views/ContactTableViewCell.m, Signal/src/views/GroupTableViewCell.swift, Signal/test/util/SearcherTest.swift, Signal/translations/en.lproj/Localizable.strings, SignalServiceKit/src/Messages/TSGroupModel.h, SignalServiceKit/src/Messages/TSGroupModel.m
If you are not searching, we now show a table index so you can quickly navigate to all your (e.g.) contacts whose name starts with an "R".
If you are searching, we do not show the table index, but we do separate results into sections, and include groups (only when searching).
=> compose screen uses table index and search includes groups

Signal/src/ViewControllers/AppSettingsViewController.m
* iPhone SE Simulator, iOS 10.3
Prevents disclosure indicator in profile row of settings from collapsing when the profile name is too long.
Fixes #2515.
=> Increase profile disclosure compression resistance

Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
This is closer to the previous behavior, at least on 5 and 6 sized devices.
Do you feel like this is *too* wide on your plus sized device @charlesmchen ?
=> Make message bubbles a bit wider.

Signal/src/ViewControllers/ConversationView/ConversationViewController.m
This is a normal case and should not cause assertion failure.
=> remove overzealous assert

Podfile, Podfile.lock
This PR is intended as a proposal.  
* Working through build errors is so much easier without the huge quantity of warnings from our pods.
* We're less likely to miss/ignore a warning from our own codebase amid the noise.
=> Suppress build warnings for Cocoapods dependencies.

Signal/src/ViewControllers/ConversationView/ConversationViewController.m
Voice memo file sizes seem reasonable.  A little more than 1 MB/minute.
=> Log voice memo durations.

Signal/src/ViewControllers/ConversationView/ConversationViewController.m
I might go a step farther and skip animations related to status changes of new outgoing messages, but that won't be necessary if we adopt a more Android-like conversation view style with footers on every message.
=> Don't animate message sends.

Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
There's a similar issue in "message detail" view, but I can't find a way to get links working in a way that's compatible with our "render UITextView using proxy view" solution.  And I don't see any alternative to using that.
=> Fix text message links in conversation view.

Cartfile, Cartfile.resolved
Avoid PromiseKit 5 for now.
> PromiseKit 5 has been released, but is not yet fully documented, so we advise sticking with version 4 for the time being.
=> Update dependencies via Carthage

Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m
The attachment button should be easier to hit _AND_ visually symmetrical with the voice memo button.
=> Increase content insets of attachment button.

Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/MessageDetailViewController.swift
On first load, message details for longer messages often get scrolled off the top of the screen.
We should only scroll as far as necessary.
**Before**
**After**
=> Scroll only as far as necessary

Signal/src/ViewControllers/OWSTableViewController.m
https://stackoverflow.com/questions/45573829/weird-uitableview-behaviour-in-ios11-cells-scroll-up-with-navigation-push-anima
=> Fix "sliding table content" issue on iOS 11.

Signal/src/ViewControllers/ConversationView/ConversationViewController.m
I'm hoping that it's now safe to remove the "1 ms animation" hack now that we've made other fixes in the `performBatchUpdates` logic.
=> Skip animations in conversation view.

Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
On iOS10 there was a default "..." button, but now we need our own. PTAL @charlesmchen
=> App icon for system call screen

Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m
This isn't safe unless show the menu controlled from the centroid of the portion of the cell _which is onscreen_, which is non-trivial.  
=> Revert "Show menu controller from centroid of message cells."

Signal/Signal-Info.plist
https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html
=> Fix the add photo permission crash on iOS 11.

SignalServiceKit/src/Messages/Attachments/TSAttachment.m, SignalServiceKit/src/Messages/OWSMessageSender.m, SignalServiceKit/src/Storage/OWSOrphanedDataCleaner.m
Open to other approaches on this as well. 
e.g. a heavier weight solution would add a createdAt date to the Attachment model, which we could use to exclude too-young models from consideration. (similar to the `kMinimumOrphanAge` logic)
=> Avoid overzealous assert

SignalServiceKit/src/TSPrefix.h, SignalServiceKit/src/Util/NSDate+OWS.mm
make SSK compatible with c++ by using non-modular imports, which
requires disambiguating our ddLog variable.
=> restore chrono timestamp

Podfile, Podfile.lock, SignalServiceKit.podspec
Based on #2815, so review that one first.
See the corresponding branch at https://github.com/WhisperSystems/GRKOpenSSLFramework/pull/1
=> Use up-to-date framework friendly OpenSSL

SignalShareExtension/ShareViewController.swift
The first usable screen is the conversation picker, that's the first
thing we want to show the user, and the modal presentation feels like
the right way to introduce this new context.
Long load times should be the exception, not the normal flow, so we
delay it's presentation in hopes that it will generally never be seen.
=> Modal conversation picker, hide loading screen when possible

SignalMessaging/contacts/SelectThreadViewController.m
Move search bar outside of table content.
Fixes issues like this:
=> Keep header affixed to navbar.

Signal.xcodeproj/xcshareddata/xcschemes/Signal.xcscheme
Outputs some statistics about linking time in xcode debug log when app or extension is launched.
=> track dyload time

Signal/Signal-Info.plist, Signal/src/AppDelegate.m, Signal/src/ViewControllers/OWSConversationSettingsViewController.m, Signal/src/contact/OWSContactsManager.h, Signal/src/contact/OWSContactsManager.m, Signal/src/util/ThreadUtil.m, SignalServiceKit/src/Contacts/Contact.h, SignalServiceKit/src/Contacts/SignalAccount.h, SignalServiceKit/src/Contacts/SignalAccount.m
Fixes seeing an empty contact list when launching compose view too soon.
Fixes the flickering contact avatar seen when first launching Signal.
=> persist signal accounts

Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.h, Signal/src/ViewControllers/ConversationView/ConversationViewController.m
Using the CollectionView's frame to determine if we're at the bottom
doesn't make sense unless the collection view is correctly layed out.
This fixes the issue we were reproducing yesterday wherein picking someone from the content picker would obscure content behind the input toolbar if the keyboard was popped when you tapped their name.
=> Fix intermittent content offset problem

Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.h, Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/GifPicker/GifPickerViewController.swift, Signal/src/util/MainAppContext.m, SignalMessaging/attachments/AttachmentApprovalViewController.swift, SignalServiceKit/src/Util/AppContext.h, SignalShareExtension/utils/ShareAppExtensionContext.m
Reuse the approval view form the share extension as a captioning screen in the main app.
To me there is one glaring issue with this approach as it currently stands affecting picking videos:
After picking a video, the UIImagePicker shows it's own a playback/confirmation screen before notifying the delegate of the picked media. (it only does this with video/GIFs, not static images). 
After confirming the video selection in that ImagePicker screen, our delegate is notified, and we show our own approval view (with captioning). The first screen is redundant. It would be nice to just skip the UIImagePicker confirmation screen, and use the caption/approval view as the single confirmation. But it doesn't seem possible, short of creating our own custom image picker experience, which could have …
=> fullscreen approval/captioning view

SignalServiceKit/src/Storage/OWSStorage.m, SignalServiceKit/src/Util/OWSFileSystem.h, SignalServiceKit/src/Util/OWSFileSystem.m
Having looked at the callers of this method, I don't think we need this warning.  I didn't realize we had an `OWSFail()` within the method itself.
=> Remove spurious warning.

SignalServiceKit/src/Account/TSAccountManager.m, SignalShareExtension/ShareViewController.swift
SAE should stop work immediately if user unregisters in main app.
=> Handle unregistration in SAE.

SignalMessaging/contacts/SelectThreadViewController.m
We were showing a "blocked" label, but not actually preventing the user from trying to send to a blocked conversation. What would happen is that after captioning the attachment when you actually tried to send, you'd get a dialog like "Can't send to Michael because he is blocked."
Now when you tap a blocked conversation, you are met with the familiar "Unblock?" actionsheet before you can proceed.
=> block vs share

SignalMessaging/attachments/AttachmentApprovalViewController.swift, SignalMessaging/contacts/SelectThreadViewController.m
convert captioning toolbar to autolayout in the process
Respecting the margins of the root view is key to iPhoneX layout, since they vary be device.
**before:**
**after:**
**before**
**after**
=> Fix attachment approval layout on iPhoneX

Signal/src/ViewControllers/MessageDetailViewController.swift
We re-create some constraints when `updateContent` is called, so
we need to ensure those constraints are configured by calling
`updateTextLayout`
=> Fix "bubble disappears" when receiving read receipt

Signal/src/ViewControllers/DebugUI/DebugUIMessages.m, Signal/src/ViewControllers/MessageDetailViewController.swift, Signal/src/ViewControllers/Utils/MessageRecipientStatusUtils.swift, Signal/src/util/DateUtil.h, Signal/src/util/DateUtil.m, Signal/translations/en.lproj/Localizable.strings, SignalMessaging/categories/NSString+OWS.h, SignalMessaging/categories/NSString+OWS.m
* Always show time on "read".
* Remove redundant messages (e.g. read) from status lines - they're redundant with the section title.
* Show time on "delivered" if possible - but we won't have that until we start sending new-style delivery receipts.
* We don't track "sent" times.  We could.
=> Refine message date/time formatting.

Signal/src/ViewControllers/MessageDetailViewController.swift
TextView size depends on the VC.view size, so it must be updated when
view is done laying out or changes bounds.
// FREEBIE
=> Fix bubble layout in message details

SignalServiceKit/src/Devices/OWSRecordTranscriptJob.m
Note: For test devices running HEAD, there may have already been some
redundant captions created for sync'd transcripts.
However the existing `TSMessage#initWithCoder:` [migration](https://github.com/signalapp/Signal-iOS/blob/master/SignalServiceKit/src/Messages/Interactions/TSMessage.m#L143) will address
this for our production users, so I'm not going to bother with a second
migration just for our test devices.
=> Don't create redundant caption for sync'd transcripts.

Signal/src/ViewControllers/MediaDetailViewController.m
On iOS11, when looking at the full-screen media details, if you'd zoomed
far enough that the media content is behind the status bar, tapping to
hide the status bar would cause an undesirable change in content offset.
=> Don't adjust inset when fully zoomed in.

SignalServiceKit/src/Util/AppReadiness.m, SignalServiceKit/src/Util/Threading.h, SignalServiceKit/src/Util/Threading.m
OWSReadReceiptManager is not `init` on the main thread; however, because
it "schedules" it's own processing during init, it crashes.
https://github.com/signalapp/Signal-iOS/blob/master/SignalServiceKit/src/Messages/OWSReadReceiptManager.m#L181
I considered dispatching to main, but since AppReadiness already *can*
resolve async if the app isn't yet ready, it should be no less safe to
also dispatch async when it's off the main thread.
=> Fix crash on launch in debug.

Signal/Signal-Info.plist, SignalServiceKit/src/Util/AppContext.h, SignalServiceKit/src/Util/AppContext.m, SignalShareExtension/Info.plist, SignalShareExtension/ShareViewController.swift
We also need to audit share view controller to ensure that we're only accessing UIKit entities on the main thread.
=> Exit SAE when complete.

SignalServiceKit/src/Util/OWSFileSystem.h, SignalServiceKit/src/Util/OWSFileSystem.m
A migrated DB file has the NSFileProtectionClassComplete, meaning it's never accessible while the device is locked. We want it to be accessible after first unlock.
Applying a data protection class to a directory only affects newly created files, not existing files in that directory nor files moved to that directory.
Presumably this has been an issue for a while in the 2.20 branch, but you'd only notice when receiving voip notifications.
PTAL: @charlesmchen
=> Fix "lose messages received while in background"

Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/SafetyNumberConfirmationAlert.swift, Signal/src/call/OutboundCallInitiator.swift
This affects iOS 8, 9, and to a lesser degree iOS10.
On iOS11, presenting an alert causes the keyboard/inputAccessoryView to
temporarily dismiss.
=> Ensure inputAccessory doesn't obscure the SN alert

Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/ConversationView/ConversationViewItem.m
Sharing media is still possible from the full screen media view and the message detail view. Sharing text would be accomplished via copy/paste.
Motivation:
Showing the share UI *from* the conversation view conflicts with the conversation view's input toolbar, and can cause behavior like:
- input toolbar not visible after completing share (must leave and re-enter thread)
- input toolbar is visible *over* the share sheet
I believe this is an iOS bug and will be filing a radar.
Specifically:
- long pressing shows the edit menu, which entails the message cell acquiring first responder status (meaning the conversation view controller is no longer the first responder)
- tapping share presents the activity view
- at this point, the input toolbar is hidden
- launching a share extension hides the …
=> Remove "Share" from edit menu

SignalMessaging/attachments/SharingThreadPickerViewController.m
For 2.20.0
We must call these completion handlers whenever we exit the SAE
=> Fix freeze in host app after "dismissing" select thread VC

Signal/src/call/Speakerbox/CallKitCallUIAdaptee.swift
If CallKit privacy is enabled, we'll always use the system default ringtone.
If CallKit privacy is *not* enabled we'll use any ringtone specified for that contact in the address book, else fall back to the default.
I know we haven't yet agreed to this approach, but wanted to put it up for proposal, as it contradicts some of the work in https://github.com/signalapp/Signal-iOS/pull/3048.
=> Respect system contact ringtones

SignalServiceKit/src/Messages/OWSReadReceiptManager.m
Not for 2.20.0
These messages are always already read.
Reminder, there are two types of read receipts:
1. One informs our linked devices that we've read a message on another
device.
2. The other informs the sender that we've read their message.
This change is about the latter, we'll continue to send the former to
ourself.
The proximate cause for this change was a failing assert in
OWSMessageSender#handleSendToMyself:(TSOutgoingMessage *)outgoingMessage
The assert was failing because we were sending a message to ourself
which had no body or attachment (the sender-read receipt). Rather than
filtering them out from the message sender, we should never ask the
message sender to do nonsense work (send a senderReadReceipt to ourself)
=> Don't enqueue sender read receipts from self-sent messages

Signal/src/call/CallService.swift, Signal/src/call/PeerConnectionClient.swift
Sending ICE updates immediately will allow calls
to connect without having to wait for an additional serialized round
trip between the caller and call recipient.
For legacy reasons, the call sender used to wait until after receiving
the call answer before sending the ICE updates. The primary motivation
was that if the receiving user hadn't accepted a new identity change,
rather than just seeing one "Tap to Accept New Safety Number" messages
for a call, they'd see one for the call offer and then a dozen more as
ICE updates trickled in.
We changed that behavior long ago, and effected clients have been mostly phased out.
=> Send ICE updates immediately after sending CallOffer for faster call connection

Signal/src/ViewControllers/HomeViewController.m
Wait until app is in the foreground to show upgrade splashes
Otherwise we'll inadvertently upgrade users into the new tone as a result of receiving the voip push.
=> Don't "show" upgrade splash when receiving a voip notification

Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/OWSSoundSettingsViewController.m, Signal/src/call/CallAudioService.swift, Signal/src/environment/NotificationsManager.m, SignalMessaging/environment/OWSSounds.h, SignalMessaging/environment/OWSSounds.m, SignalMessaging/utils/OWSAudioPlayer.h, SignalMessaging/utils/OWSAudioPlayer.m
The audio player was setting the AudioCategory to playback.
The new API is a little more cumbersome, but I think we *should* be forcing ourselves to think about the category context whenever we're playing audio.
=> Notification sounds should respect silent switch

Signal/src/ViewControllers/ExperienceUpgradesPageViewController.swift, Signal/src/ViewControllers/HomeViewController.m, SignalMessaging/environment/OWSSounds.h, SignalMessaging/environment/OWSSounds.m, SignalMessaging/environment/migrations/OWS107LegacySounds.m
There used to be a migration that ran when the experience upgrade view controller became visible. In an effort to make sure that didn't happen until the user actually had the app in the foreground, I inadvertently suppressed the presentation of the experience upgrade for users explicitly launching the app (until they backgrounded and re-foregrounded the app).
Now that the migration has been removed, I've reverted the presentation logic of the upgrade experience VC to occur when HomeViewController.viewDidAppear.
=> Show migration screen at first launch.

Signal/src/AppDelegate.m, Signal/src/ViewControllers/CallViewController.swift, Signal/src/call/CallService.swift, Signal/src/network/PushManager.m, SignalMessaging/utils/OWSPreferences.m
callUIAdapter is not a singleton (for better or for worse)
No one should hold a reference directly to it, but rather via the
CallService, which is a singleton
Wait a bit longer for initial call screen before terminating. Especially
first call can hit this limit.
When call *does* take too long to show, terminate properly to ensure
we're not left with a phantom call
=> Call connection fixups

Signal/src/AppDelegate.m, Signal/src/call/NonCallKitCallUIAdaptee.swift, Signal/src/environment/SignalApp.m, SignalMessaging/utils/OWSPreferences.h, SignalMessaging/utils/OWSPreferences.m
Though it should be fine, reloading the callUIAdapter is a bit heavy
handed. And the current implementation is prone to being broken, since
we sometimes forget not to treat callUIAdapter as a singleton.
Longer term we can find a way to either: make callUIAdapter a true
singleton or possibly make callUIAdapter a private member of something
which *is* a true singleton.
Since we only *need* it to be reloaded the one time the migration runs
(or when a user changes settings which should be rare) it makes sense to
remove it from the happy path.
=> A lighter touch for the fix-call connect.

Signal.xcodeproj/project.pbxproj, Signal/src/Signal-Bridging-Header.h, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/MediaDetailViewController.h, Signal/src/ViewControllers/MediaDetailViewController.m, Signal/src/ViewControllers/MediaPageViewController.swift, Signal/src/ViewControllers/MessageDetailViewController.swift, SignalMessaging/attachments/OWSVideoPlayer.swift, SignalMessaging/categories/Collection+OWS.swift, SignalServiceKit/src/Messages/Interactions/TSInteraction.h, SignalServiceKit/src/Messages/Interactions/TSInteraction.m, SignalServiceKit/src/Messages/Interactions/TSMessage.h, SignalServiceKit/src/Messages/Interactions/TSMessage.m, SignalServiceKit/src/Storage/OWSMediaGalleryFinder.h, SignalServiceKit/src/Storage/OWSMediaGalleryFinder.m, SignalServiceKit/src/Storage/OWSPrimaryStorage.m
First pass at a swipe-through media view for conversations.
Future work could include (there's a card tracking these):
- title label per item with sender name, date/time
- photo rail
- overlay caption when available
- using Mapping so we don't have to keep a copy of all mediaMessages for a thread in memory
- reaping GalleryItemCache
It's intended to be visually identical to the existing full screen media view, but now you can page through multiple.
One thing, I intentionally omitted the dbModified machinery under the assumption that people in the gallery don't expect new media to appear as messages trickle in while viewing the gallery. I could be wrong about this, but it simplified the implementation.
=> Swipe through media attachments

Signal/src/ViewControllers/MediaGalleryViewController.swift, Signal/src/ViewControllers/MediaPageViewController.swift
Make sure to add/remove the video "play" button from the detail footer when bouncing around between the media tile view and the detail pager.
=> Update footer when returning to details via Tile view

Signal/src/network/GiphyAPI.swift
This will reduce the max number of search results in half (from 200 -> 100), but:
* search results with load faster.
* we'll be less likely to stumble across bugs that only affect queries with lots of results (as we did this week).
* I suspect most users only look at the first ~20 results anyway.
=> Reduce Giphy page size.

SignalServiceKit/src/Messages/Attachments/TSAttachmentStream.m
Otherwise the file hasn't been written to disk yet.
=> Don't generate thumbnail until attachment has been saved

Signal/src/ViewControllers/MediaGalleryViewController.swift, Signal/src/ViewControllers/MediaPageViewController.swift
We weren't doing a good job of cleaning up state upon dismissing the DetailView when presented *from* the tile view.
Basically the repro was:
Go to Conversation Settings -> All Media
Tap on a tile, swipe to a different piece of media, dismiss
That dismiss would be fine.
However, when tapping on a *subsequent* tile. That presentation (and eventual dismissal) would not show the presentationView.
And another similar problem, if you'd dismissed the detail view while the navbar was hidden, the next presentation of the detail view would be missing the navbar.
=> Fix Tile -> Detail -> Swipe -> Dismiss -> Detail flow.

Signal/src/util/OWSScreenLock.swift, Signal/src/util/OWSScreenLockUI.m
I added this code, took it out, and now I'm putting it back in.  Michael's log from today seems to indicate that the best way to handle these "unexpected" (or at least so far inexplicable) errors is to simply retry again until it works.  
=> Improve handling of local authentication errors.

Signal/src/ViewControllers/ConversationView/Cells/OWSBubbleView.m, Signal/src/ViewControllers/HomeViewController.m
We need a simplified bubble shape path to avoid stroking media content.
=> Simplify bubble edge.

Signal/src/ViewControllers/ProfileViewController.m, Signal/src/ViewControllers/ThreadSettings/OWSConversationSettingsViewController.m, Signal/src/views/AttachmentPointerView.swift, Signal/src/views/GroupTableViewCell.swift, SignalMessaging/Views/ContactTableViewCell.m
I was too aggressive with applying dynamic text in some cases.  Fixing these issues is out of scope for this sprint, so reverting.
=> Fix small text usage.

Signal/src/Signal-Bridging-Header.h, Signal/src/ViewControllers/ConversationView/Cells/ConversationViewCell.h, Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.h, Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m, Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.h, Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/ConversationView/ConversationViewItem.m, Signal/src/ViewControllers/MessageDetailViewController.swift, SignalMessaging/SignalMessaging.h, SignalMessaging/attachments/MediaMessageView.swift
Fixes image, video, and audio interactions in the message detail view.
The basic problem was that these interactions were being handled on the OWSMessageCell, so I've moved them to the OWSMessageBubbleView, which allowed simplifying a few things elsewhere.
=> fix message details media

Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m
=> truncate tail for both preview and message bubble

Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m, SignalMessaging/contacts/OWSContactsManager.m, SignalServiceKit/src/Contacts/SignalAccount.h, SignalServiceKit/src/Contacts/SignalAccount.m
Turned out to not be *quite* a one line change =/
=> Use profile name in quoted messages, fix "multi account" label

Signal/src/ViewControllers/ConversationView/Cells/OWSSystemMessageCell.m
=> Fix system cell layout.

SignalServiceKit/src/Contacts/PhoneNumber.m, SignalServiceKit/src/Contacts/PhoneNumberUtil.h, SignalServiceKit/src/Contacts/PhoneNumberUtil.m
The thread locals won't share a cache, but I don't think that'll be too expensive in terms of memory (it caches a set of short strings) or perf (each system contact fetch will take place on a single thread so cache will quickly warm).
=> Ensure thread safety in phone parsing logic.

SignalMessaging/contacts/OWSContactsSyncing.m, SignalServiceKit/src/Account/TSAccountManager.h
It's largely a redundant check anyway, but the previous typo was a
no-op.
=> cleanup contact syncing

Signal/translations/en.lproj/Localizable.strings, SignalMessaging/attachments/SignalAttachment.swift
We need to this thoroughly since we don't know exactly why using UIGraphicsBeginImageContext() crashes in share extension after using auth UI, but under some light testing this approach seems to resolve the issue.
=> Fix crash converting images in SAE.

SignalMessaging/contacts/OWSContactsManager.m
We manipulate case when rendering contact names but not when sorting them, which leads to surprising results.
=> Use case-insensitive comparison when sorting contacts.

Signal/src/ViewControllers/ContactViewController.swift, Signal/src/ViewControllers/MessageDetailViewController.swift
Text of the exception is:
"Impossible to set up layout with view hierarchy unprepared for constraint"
Since their container view is pinned to the top layout guide, this
should not change the layout.
=> Fix crash after canceling "Add New Contact"

Signal/src/ViewControllers/ContactShareViewHelper.swift, Signal/src/ViewControllers/ContactViewController.swift, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/MessageDetailViewController.swift
Two issues:
1. Make sure we always return the navbar to the correct style. There were certain ways to leave the contact flow yet see navbar labels rendered black.
The issue occurs when mutating NavBar appearance when a navbar is hidden. i.e. if we weren't hiding the navbars in the OWS ContactViewController, this wouldn't occur (obviously for the design we want to hide these navbars, but it explains why we haven't seen this before.)
2. Present the "add a contact" modally. Since the "Add a contact" view needs to use the navbar (for the "done" and "cancel" buttons), animating the navbar back in for this view controller looks janky. 
Tested on iOS 9.4, 10.3, and 11.3
=> contact flow vs. navbar style issues

Signal/src/ViewControllers/ContactViewController.swift
I removed this earlier - but turns out we still need this dedicated
reference, even though we're now using willDisappear instead of
didDisappear.
=> Fix navbar after using message button in contact card

Signal/src/views/ContactCell.swift
previously you would just see a "#" avatar with no name
=> Fall back to phone number for picker cell display name

Signal/src/ViewControllers/Registration/RegistrationViewController.m
Eventually we should convert this view to use dynamic type everywhere, but that would involve a bunch of work that we don't have time for before this release.
=> Don't use dynamic type in registration view... yet.

Signal/translations/en.lproj/Localizable.strings
Changed "Activate This Device" to "Register" to be at parity with Signal Android
Changed one comment from "deactivated" to "unregistered"
* iDevice A, iOS X.Y.Z
* iDevice B, iOS Z.Y
Changed "Activate This Device" to "Register" to be at parity with Signal Android.
Changed one comment from "deactivated" to "unregistered"
=> Update Localizable.strings for minor copy change to Registration view

SignalServiceKit/src/TSConstants.h
We could remove all the ifdef, but let's wait until this feature is actually in the wild in case we have to pull it again.
=> Show legal terms link

SignalMessaging/Views/ContactCellView.m
I haven't dug in much to find out what's different with our homebrew margin pinning method, but since it's used all over the place, I'd be hesitant to make any changes to that method during stabilization anyway.
=> Fix: iOS10 was not respecting margins with our homebrew pin method

Signal/src/ViewControllers/HomeView/HomeViewController.m, Signal/src/views/ReminderView.swift, SignalMessaging/contacts/OWSContactsManager.h, SignalMessaging/contacts/OWSContactsManager.m, SignalMessaging/contacts/SystemContactsFetcher.swift
fixes: 
After:
Also fixes our "no contacts" banner which was not being displayed.
=> archive banner

SignalServiceKit/src/Network/OutageDetection.swift
MessageSender completion queue is not the main queue.
=> Fix failing assert: only set state on main thread

Signal/src/views/GroupTableViewCell.swift
We switched sizing to automatic, but group cell wasn't autolayout ready.
**before**
**after**
=> FIX: compose search group cell

Signal/src/ViewControllers/HomeView/HomeViewController.m
When navigating back from a conversation, we could be scrolled down a ways.
Since the search bar lives in the inbox table view, we need to make sure the
inbox table view is scrolled all the way up to keep the search bar visible.
=> FIX: obscured searchbar upon returning

Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m, Signal/src/ViewControllers/ConversationView/Cells/OWSMessageTextView.h, Signal/src/ViewControllers/ConversationView/Cells/OWSMessageTextView.m, SignalMessaging/categories/UIView+OWS.h
It turns out this technique works for `UILabel` but not `UITextArea`.  I tried to fix it using `UITextArea` container and layout properties, but couldn't.
=> Disable compact text layout.

Signal/src/ViewControllers/AppSettings/OWSQRCodeScanningViewController.m, Signal/src/ViewControllers/ConversationView/Cells/OWSContactShareButtonsView.m, Signal/src/ViewControllers/ConversationView/Cells/OWSContactShareView.m, Signal/src/ViewControllers/ConversationView/Cells/OWSMessageBubbleView.m, Signal/src/ViewControllers/ConversationView/Cells/OWSMessageTimerView.m, Signal/src/ViewControllers/ConversationView/Cells/OWSQuotedMessageView.m, Signal/src/ViewControllers/ConversationView/ConversationInputToolbar.m, Signal/src/ViewControllers/GifPicker/GifPickerCell.swift, Signal/src/ViewControllers/MediaDetailViewController.m, Signal/src/ViewControllers/MenuActionsViewController.swift, Signal/src/ViewControllers/MessageDetailViewController.swift, Signal/src/ViewControllers/ThreadSettings/FingerprintViewController.m, Signal/src/views/ReminderView.swift, SignalMessaging/Views/OWSFlatButton.swift, SignalMessaging/attachments/VideoPlayerView.swift, SignalMessaging/categories/UIView+OWS.h, SignalMessaging/categories/UIView+OWS.m
On iOS9/10 the ContactCell is not respecting it's wrapper's margin.
We have some methods that are named very similarly to PureLayout methods.
`PureLayout#autoPinEdgesToSuperviewEdges` pins to leading/trailing/top/left
`OWS#autoPinToSuperviewEdges` now renamed to `ows_autoPinToSuperviewEdges` pinned to left/right/top/left.
I think it's probably rare that we want to use this one, but didn't want to make a broad sweeping change during stabilization.
`PureLayout#autoPinEdgesToSuperviewMargin` vs
`OWS#autoPinToSuperviewMargins` uses our own constraint adding logic,
and behaves differently in some cases. In the case of this PR, using PureLayout's flavor results in the margins being respected on iOS9 and 10 (both work with iOS11).
I haven't dug into exactly why this method is behaving …
=> fix contact cell

Signal/src/ViewControllers/ThreadSettings/OWSConversationSettingsViewController.m, Signal/src/ViewControllers/ThreadSettings/ShowGroupMembersViewController.m
must specify rowHeight automatic
However, mixing static and automatic sizing within a single tableView on iOS9/10 caused some our cells to be too small, since they were previously relying on their static size.  To address this, I've converted the affected cells to be sizeable using autolayout.
=> fix squashed cells on ios9/10

BUILDING.md
Per discussion [here](https://community.signalusers.org/t/not-able-to-build-in-xcode-9-3-9-4/3498/12).
Using `--recurse-submodules` will init and update all submodules, so you can do everything at once. I find this a bit nicer.
(Also, it seems like it might be more reliable with GitHub forks?)
I realize `make dependencies` runs `git submodule update --init`. It will just be a no-op if you clone this way.
=> [Build] Update clone instructions

Signal/src/Jobs/MessageFetcherJob.swift, Signal/test/SSKTests/ParamParserTest.swift, SignalServiceKit/src/Contacts/ContactsUpdater.m, SignalServiceKit/src/Contacts/OWSContactDiscoveryOperation.swift, SignalServiceKit/src/Util/ParamParser.swift
For empty base64Encoded data, sometimes the server sends "null" (which is represented as NSNull) and sometimes the server sends an empty string. 🤷‍♂️ 
In both cases we represent this as nil - which will fail if it's a required field.
=> Fixup parser: Robust to servers various "empty" types

Signal/src/ViewControllers/HomeView/HomeViewController.m, SignalMessaging/ViewControllers/OWSNavigationController.m, SignalMessaging/Views/OWSNavigationBar.swift
Reconciles safeAreaInsets with *additional*SafeAreaInsets now that we have a translucent navbar.
=> Fix too-much-space when call banner is present

Signal/src/ViewControllers/ConversationView/Cells/ConversationViewCell.h, Signal/src/ViewControllers/ConversationView/Cells/ConversationViewCell.m, Signal/src/ViewControllers/ConversationView/Cells/OWSContactOffersCell.m, Signal/src/ViewControllers/ConversationView/Cells/OWSMessageCell.m, Signal/src/ViewControllers/ConversationView/Cells/OWSSystemMessageCell.m, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/ConversationView/ConversationViewItem.h, Signal/src/ViewControllers/ConversationView/ConversationViewItem.m, Signal/src/ViewControllers/ConversationView/ConversationViewLayout.h, Signal/src/ViewControllers/ConversationView/ConversationViewLayout.m
Something that we've talked about for a while.  By caching system message text, we can skip opening a ton of read transactions in the conversation view.
=> Cache system message text.

Signal/src/ViewControllers/MenuActionsViewController.swift
For 2.29
Tweak message actions transparency in dark theme.
**before**
**after**
=> Darken message actions overlay in dark theme

Signal/src/ViewControllers/ContactShareViewHelper.swift, Signal/src/ViewControllers/ContactViewController.swift, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/DebugUI/DebugUIContacts.m, Signal/src/ViewControllers/DebugUI/DebugUIStress.m, Signal/src/ViewControllers/HomeView/ConversationSearchViewController.swift, Signal/src/ViewControllers/HomeView/HomeViewController.h, Signal/src/ViewControllers/HomeView/HomeViewController.m, Signal/src/ViewControllers/NewContactThreadViewController.m, Signal/src/ViewControllers/NewGroupViewController.m, Signal/src/ViewControllers/ProfileViewController.h, Signal/src/ViewControllers/ProfileViewController.m, Signal/src/ViewControllers/ThreadSettings/ShowGroupMembersViewController.m, Signal/src/environment/SignalApp.h, Signal/src/environment/SignalApp.m, Signal/src/network/PushManager.m
Current after picking a conversation we first dismiss the keyboard, the current view (contact picker) then animate pushing the conversation view.
This PR pushes (without animation) the conversation view *before* dismissing the contact picker, allowing us to skip:
1. the keyboard dismiss animation
2. the conversation push animation
You might want to build and run this and compare it to prod to get a feel for the difference.
=> faster conversation presentation after contact picking

Signal/src/AppDelegate.m, Signal/src/ViewControllers/AppSettings/AboutTableViewController.m, Signal/src/ViewControllers/AppSettings/AdvancedSettingsTableViewController.m, Signal/src/ViewControllers/AppSettings/NotificationSettingsOptionsViewController.m, Signal/src/ViewControllers/AppSettings/NotificationSettingsViewController.m, Signal/src/ViewControllers/AppSettings/PrivacySettingsTableViewController.m, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/HomeView/HomeViewController.m, Signal/src/ViewControllers/NewContactThreadViewController.m, Signal/src/call/UserInterface/CallUIAdapter.swift, Signal/src/environment/NotificationsManager.m, Signal/src/environment/SignalApp.m, Signal/src/util/OWSScreenLockUI.m, Signal/src/util/RegistrationUtils.m, SignalMessaging/SignalMessaging.h, SignalMessaging/Views/OWSAlerts.swift, SignalMessaging/environment/Environment.h, SignalMessaging/environment/Environment.m, SignalMessaging/environment/migrations/OWS108CallLoggingPreference.m
We should access `preferences` like the other singletons that hang on `Environment` - via `Environment.shared`.
=> Simplify OWSPreferences access.

SignalServiceKit/src/Storage/KeychainStorage.swift
* iPhone X (simulator), iOS 11.4 (15F79)
* iPhone X, iOS 11.4.1 (15G77)
If `SSKDefaultKeychainStorage.remove(service:key:)` fails to remove a keychain item because the specified item does not exist, treat the operation as having succeeded instead of throwing an error.
Fixes https://github.com/signalapp/Signal-iOS/issues/3876. With these changes, the app no longer crashes on launch when installed on a clean device and run for the first time.
=> Treat failure to delete a non-existent password as success

Signal.xcodeproj/project.pbxproj, Signal/src/ViewControllers/ColorPickerViewController.swift, Signal/src/ViewControllers/ConversationView/ConversationViewController.m, Signal/src/ViewControllers/ConversationView/ConversationViewItem.h, Signal/src/ViewControllers/ConversationView/ConversationViewItem.m, Signal/src/ViewControllers/ConversationView/ConversationViewModel.h, Signal/src/ViewControllers/ConversationView/ConversationViewModel.m
Pulls out a VM for the conversation view.  It corresponds to "the conversation".  
For clarity, we could eventually rename the existing `ConversationViewItem` to `ConversationViewModelItem`, since they are sub-viewmodels, representing items in the conversation.
=> Add ConversationViewModel.

Signal/src/AppDelegate.m, Signal/src/Jobs/SessionResetJob.swift, Signal/src/network/PushManager.m, Signal/src/util/OWSScreenLockUI.m, SignalMessaging/contacts/OWSContactsManager.h, SignalMessaging/contacts/OWSContactsManager.m, SignalMessaging/contacts/OWSSyncManager.m, SignalMessaging/contacts/SystemContactsFetcher.swift, SignalMessaging/profiles/OWSProfileManager.m, SignalServiceKit/src/Account/TSAccountManager.m, SignalServiceKit/src/Messages/OWSBatchMessageProcessor.h, SignalServiceKit/src/Messages/OWSBatchMessageProcessor.m, SignalServiceKit/src/Messages/OWSBlockingManager.m, SignalServiceKit/src/Messages/OWSDisappearingMessagesJob.m, SignalServiceKit/src/Messages/OWSIdentityManager.m, SignalServiceKit/src/Messages/OWSMessageManager.m, SignalServiceKit/src/Messages/OWSMessageReceiver.h, SignalServiceKit/src/Messages/OWSMessageReceiver.m, SignalServiceKit/src/Messages/OWSOutgoingReceiptManager.m, SignalServiceKit/src/Messages/OWSReadReceiptManager.m, SignalServiceKit/src/Messages/UD/OWSUDManager.swift, SignalServiceKit/src/Network/MessageSenderJobQueue.swift, SignalServiceKit/src/Network/WebSockets/OWSWebSocket.m, SignalServiceKit/src/Util/AppReadiness.h, SignalServiceKit/src/Util/AppReadiness.m, SignalServiceKit/src/Util/JobQueue.swift, SignalServiceKit/src/Util/TypingIndicators.swift, SignalShareExtension/ShareViewController.swift
I've wanted to do something like this for a while, but I'm doing it now to resolve a real race on startup around the new durable message queues.
The proposal is to avoid races on startup by distinguishing "will become ready" (which doesn't depend on any other components except primary storage) and "did become ready" (which might use other components) work.  
After the "will" blocks, all of the components in the system should be ready to interact with other components - they can ensure that with a "will" block.  
```
// If the app is ready, the block is called immediately;
// otherwise it is called when the app becomes ready.
//
// This method should only be called on the main thread.
// The block will always be called on the main thread.
//
// * The "will become ready" blocks are called …
```
=> Charlesmchen/app will become ready 

SignalMessaging/profiles/OWSProfileManager.m
Fixes https://github.com/signalapp/Signal-iOS/issues/4021
=> use latest key when verifying the local profile from the service

BUILDING.md
This is admittedly less thorough than the previous doc, but it's less likely to be out of date / confusing while still containing the required information.
PTAL @charlesmchen-signal
=> removed outdated build instructions.

SignalServiceKit/src/Contacts/Threads/TSContactThread.h, SignalServiceKit/src/Contacts/Threads/TSContactThread.m, SignalServiceKit/src/Messages/Interactions/TSIncomingMessage.h, SignalServiceKit/src/Messages/Interactions/TSIncomingMessage.m, SignalServiceKit/src/Messages/Interactions/TSQuotedMessage.m, SignalServiceKit/src/Messages/OWSDisappearingMessagesJob.m, SignalServiceKit/src/Messages/OWSReadReceiptManager.m
Long ago authorId was only set on incoming **group** messages - the idea was that you should only ever use `messageAuthorId` which would derive the author's id if necessary.
In at least one case,  when getting author color, we were incorrectly using `authorId` instead of `messageAuthorId`.
So now, we migrate the data in initWithCode, and no longer have a method we shouldn't ever call.
=> Fix crash due to empty authorId on old messages

.github/FUNDING.yml
Displays the Sponsor button on top of the GitHub interface. This file is similar to the [FUNDING.yml](https://github.com/signalapp/Signal-Desktop/blob/development/.github/FUNDING.yml) file on the Signal-Desktop repository.
=> Add FUNDING.yml to display sponsor button in GitHub
